
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Oct 14 2025 19:20:39 IST (Oct 14 2025 13:50:39 UTC)

// Verification Directory fv/FIFO 

module FIFO_memory_DATA_SIZE8_ADDR_SIZE4(rdata, wdata, waddr, raddr,
     wclk_en, wfull, wclk);
  input [7:0] wdata;
  input [3:0] waddr, raddr;
  input wclk_en, wfull, wclk;
  output [7:0] rdata;
  wire [7:0] wdata;
  wire [3:0] waddr, raddr;
  wire wclk_en, wfull, wclk;
  wire [7:0] rdata;
  wire [7:0] \mem[12] ;
  wire [7:0] \mem[11] ;
  wire [7:0] \mem[0] ;
  wire [7:0] \mem[5] ;
  wire [7:0] \mem[10] ;
  wire [7:0] \mem[9] ;
  wire [7:0] \mem[4] ;
  wire [7:0] \mem[3] ;
  wire [7:0] \mem[8] ;
  wire [7:0] \mem[2] ;
  wire [7:0] \mem[1] ;
  wire [7:0] \mem[7] ;
  wire [7:0] \mem[6] ;
  wire [7:0] \mem[14] ;
  wire [7:0] \mem[13] ;
  wire [7:0] \mem[15] ;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125;
  NAND4XL g2012(.A (n_106), .B (n_105), .C (n_103), .D (n_125), .Y
       (rdata[2]));
  NAND4XL g2013(.A (n_94), .B (n_89), .C (n_54), .D (n_119), .Y
       (rdata[6]));
  NAND4XL g2014(.A (n_72), .B (n_108), .C (n_65), .D (n_123), .Y
       (rdata[7]));
  NAND4XL g2015(.A (n_95), .B (n_93), .C (n_91), .D (n_122), .Y
       (rdata[1]));
  NAND4XL g2016(.A (n_56), .B (n_107), .C (n_104), .D (n_124), .Y
       (rdata[5]));
  NAND4XL g2017(.A (n_80), .B (n_78), .C (n_77), .D (n_121), .Y
       (rdata[0]));
  NAND4XL g2018(.A (n_86), .B (n_84), .C (n_79), .D (n_120), .Y
       (rdata[4]));
  NAND4XL g2019(.A (n_63), .B (n_62), .C (n_60), .D (n_118), .Y
       (rdata[3]));
  AOI221X1 g2020(.A0 (\mem[12] [2]), .A1 (n_40), .B0 (\mem[11] [2]),
       .B1 (n_49), .C0 (n_116), .Y (n_125));
  AOI221X1 g2021(.A0 (\mem[0] [5]), .A1 (n_53), .B0 (\mem[5] [5]), .B1
       (n_39), .C0 (n_115), .Y (n_124));
  AOI221X1 g2022(.A0 (\mem[10] [7]), .A1 (n_38), .B0 (\mem[9] [7]), .B1
       (n_48), .C0 (n_114), .Y (n_123));
  AOI221X1 g2023(.A0 (\mem[0] [1]), .A1 (n_53), .B0 (\mem[5] [1]), .B1
       (n_39), .C0 (n_117), .Y (n_122));
  AOI221X1 g2024(.A0 (\mem[4] [0]), .A1 (n_47), .B0 (\mem[3] [0]), .B1
       (n_45), .C0 (n_111), .Y (n_121));
  AOI221X1 g2025(.A0 (\mem[8] [4]), .A1 (n_50), .B0 (\mem[11] [4]), .B1
       (n_49), .C0 (n_113), .Y (n_120));
  AOI221X1 g2026(.A0 (\mem[2] [6]), .A1 (n_41), .B0 (\mem[1] [6]), .B1
       (n_44), .C0 (n_112), .Y (n_119));
  AOI221X1 g2027(.A0 (\mem[0] [3]), .A1 (n_53), .B0 (\mem[7] [3]), .B1
       (n_52), .C0 (n_110), .Y (n_118));
  NAND4XL g2028(.A (n_88), .B (n_87), .C (n_85), .D (n_83), .Y (n_117));
  NAND4XL g2029(.A (n_101), .B (n_100), .C (n_98), .D (n_97), .Y
       (n_116));
  NAND4XL g2030(.A (n_99), .B (n_96), .C (n_92), .D (n_90), .Y (n_115));
  NAND4XL g2031(.A (n_109), .B (n_64), .C (n_58), .D (n_102), .Y
       (n_114));
  NAND4XL g2032(.A (n_74), .B (n_71), .C (n_68), .D (n_66), .Y (n_113));
  NAND4XL g2033(.A (n_69), .B (n_67), .C (n_61), .D (n_59), .Y (n_112));
  NAND4XL g2034(.A (n_76), .B (n_75), .C (n_73), .D (n_70), .Y (n_111));
  NAND4XL g2035(.A (n_57), .B (n_55), .C (n_81), .D (n_82), .Y (n_110));
  AOI22XL g2036(.A0 (n_41), .A1 (\mem[2] [7]), .B0 (n_45), .B1
       (\mem[3] [7]), .Y (n_109));
  AOI22XL g2037(.A0 (n_40), .A1 (\mem[12] [7]), .B0 (n_49), .B1
       (\mem[11] [7]), .Y (n_108));
  AOI22XL g2038(.A0 (n_44), .A1 (\mem[1] [5]), .B0 (n_51), .B1
       (\mem[6] [5]), .Y (n_107));
  AOI22XL g2039(.A0 (n_43), .A1 (\mem[14] [2]), .B0 (n_46), .B1
       (\mem[13] [2]), .Y (n_106));
  AOI22XL g2040(.A0 (n_50), .A1 (\mem[8] [2]), .B0 (n_42), .B1
       (\mem[15] [2]), .Y (n_105));
  AOI22XL g2041(.A0 (n_47), .A1 (\mem[4] [5]), .B0 (n_45), .B1
       (\mem[3] [5]), .Y (n_104));
  AOI22XL g2042(.A0 (n_48), .A1 (\mem[9] [2]), .B0 (n_38), .B1
       (\mem[10] [2]), .Y (n_103));
  AOI22XL g2043(.A0 (n_53), .A1 (\mem[0] [7]), .B0 (n_44), .B1
       (\mem[1] [7]), .Y (n_102));
  AOI22XL g2044(.A0 (n_51), .A1 (\mem[6] [2]), .B0 (n_52), .B1
       (\mem[7] [2]), .Y (n_101));
  AOI22XL g2045(.A0 (n_47), .A1 (\mem[4] [2]), .B0 (n_39), .B1
       (\mem[5] [2]), .Y (n_100));
  AOI22XL g2046(.A0 (n_43), .A1 (\mem[14] [5]), .B0 (n_42), .B1
       (\mem[15] [5]), .Y (n_99));
  AOI22XL g2047(.A0 (n_41), .A1 (\mem[2] [2]), .B0 (n_45), .B1
       (\mem[3] [2]), .Y (n_98));
  AOI22XL g2048(.A0 (n_53), .A1 (\mem[0] [2]), .B0 (n_44), .B1
       (\mem[1] [2]), .Y (n_97));
  AOI22XL g2049(.A0 (n_40), .A1 (\mem[12] [5]), .B0 (n_46), .B1
       (\mem[13] [5]), .Y (n_96));
  AOI22XL g2050(.A0 (n_41), .A1 (\mem[2] [1]), .B0 (n_52), .B1
       (\mem[7] [1]), .Y (n_95));
  AOI22XL g2051(.A0 (n_51), .A1 (\mem[6] [6]), .B0 (n_39), .B1
       (\mem[5] [6]), .Y (n_94));
  AOI22XL g2052(.A0 (n_44), .A1 (\mem[1] [1]), .B0 (n_51), .B1
       (\mem[6] [1]), .Y (n_93));
  AOI22XL g2053(.A0 (n_38), .A1 (\mem[10] [5]), .B0 (n_49), .B1
       (\mem[11] [5]), .Y (n_92));
  AOI22XL g2054(.A0 (n_47), .A1 (\mem[4] [1]), .B0 (n_45), .B1
       (\mem[3] [1]), .Y (n_91));
  AOI22XL g2055(.A0 (n_50), .A1 (\mem[8] [5]), .B0 (n_48), .B1
       (\mem[9] [5]), .Y (n_90));
  AOI22XL g2056(.A0 (n_47), .A1 (\mem[4] [6]), .B0 (n_45), .B1
       (\mem[3] [6]), .Y (n_89));
  AOI22XL g2057(.A0 (n_43), .A1 (\mem[14] [1]), .B0 (n_42), .B1
       (\mem[15] [1]), .Y (n_88));
  AOI22XL g2058(.A0 (n_40), .A1 (\mem[12] [1]), .B0 (n_46), .B1
       (\mem[13] [1]), .Y (n_87));
  AOI22XL g2059(.A0 (n_40), .A1 (\mem[12] [4]), .B0 (n_42), .B1
       (\mem[15] [4]), .Y (n_86));
  AOI22XL g2060(.A0 (n_38), .A1 (\mem[10] [1]), .B0 (n_49), .B1
       (\mem[11] [1]), .Y (n_85));
  AOI22XL g2061(.A0 (n_48), .A1 (\mem[9] [4]), .B0 (n_43), .B1
       (\mem[14] [4]), .Y (n_84));
  AOI22XL g2062(.A0 (n_50), .A1 (\mem[8] [1]), .B0 (n_48), .B1
       (\mem[9] [1]), .Y (n_83));
  AOI22XL g2063(.A0 (n_50), .A1 (\mem[8] [3]), .B0 (n_48), .B1
       (\mem[9] [3]), .Y (n_82));
  AOI22XL g2064(.A0 (n_38), .A1 (\mem[10] [3]), .B0 (n_49), .B1
       (\mem[11] [3]), .Y (n_81));
  AOI22XL g2065(.A0 (n_51), .A1 (\mem[6] [0]), .B0 (n_39), .B1
       (\mem[5] [0]), .Y (n_80));
  AOI22XL g2066(.A0 (n_38), .A1 (\mem[10] [4]), .B0 (n_46), .B1
       (\mem[13] [4]), .Y (n_79));
  AOI22XL g2067(.A0 (n_53), .A1 (\mem[0] [0]), .B0 (n_52), .B1
       (\mem[7] [0]), .Y (n_78));
  AOI22XL g2068(.A0 (n_41), .A1 (\mem[2] [0]), .B0 (n_44), .B1
       (\mem[1] [0]), .Y (n_77));
  AOI22XL g2069(.A0 (n_43), .A1 (\mem[14] [0]), .B0 (n_42), .B1
       (\mem[15] [0]), .Y (n_76));
  AOI22XL g2070(.A0 (n_38), .A1 (\mem[10] [0]), .B0 (n_49), .B1
       (\mem[11] [0]), .Y (n_75));
  AOI22XL g2071(.A0 (n_51), .A1 (\mem[6] [4]), .B0 (n_52), .B1
       (\mem[7] [4]), .Y (n_74));
  AOI22XL g2072(.A0 (n_40), .A1 (\mem[12] [0]), .B0 (n_46), .B1
       (\mem[13] [0]), .Y (n_73));
  AOI22XL g2073(.A0 (n_43), .A1 (\mem[14] [7]), .B0 (n_46), .B1
       (\mem[13] [7]), .Y (n_72));
  AOI22XL g2074(.A0 (n_47), .A1 (\mem[4] [4]), .B0 (n_39), .B1
       (\mem[5] [4]), .Y (n_71));
  AOI22XL g2075(.A0 (n_50), .A1 (\mem[8] [0]), .B0 (n_48), .B1
       (\mem[9] [0]), .Y (n_70));
  AOI22XL g2076(.A0 (n_43), .A1 (\mem[14] [6]), .B0 (n_42), .B1
       (\mem[15] [6]), .Y (n_69));
  AOI22XL g2077(.A0 (n_41), .A1 (\mem[2] [4]), .B0 (n_45), .B1
       (\mem[3] [4]), .Y (n_68));
  AOI22XL g2078(.A0 (n_38), .A1 (\mem[10] [6]), .B0 (n_49), .B1
       (\mem[11] [6]), .Y (n_67));
  AOI22XL g2079(.A0 (n_53), .A1 (\mem[0] [4]), .B0 (n_44), .B1
       (\mem[1] [4]), .Y (n_66));
  AOI22XL g2080(.A0 (n_50), .A1 (\mem[8] [7]), .B0 (n_42), .B1
       (\mem[15] [7]), .Y (n_65));
  AOI22XL g2081(.A0 (n_47), .A1 (\mem[4] [7]), .B0 (n_39), .B1
       (\mem[5] [7]), .Y (n_64));
  AOI22XL g2082(.A0 (n_47), .A1 (\mem[4] [3]), .B0 (n_45), .B1
       (\mem[3] [3]), .Y (n_63));
  AOI22XL g2083(.A0 (n_41), .A1 (\mem[2] [3]), .B0 (n_44), .B1
       (\mem[1] [3]), .Y (n_62));
  AOI22XL g2084(.A0 (n_40), .A1 (\mem[12] [6]), .B0 (n_46), .B1
       (\mem[13] [6]), .Y (n_61));
  AOI22XL g2085(.A0 (n_51), .A1 (\mem[6] [3]), .B0 (n_39), .B1
       (\mem[5] [3]), .Y (n_60));
  AOI22XL g2086(.A0 (n_50), .A1 (\mem[8] [6]), .B0 (n_48), .B1
       (\mem[9] [6]), .Y (n_59));
  AOI22XL g2087(.A0 (n_51), .A1 (\mem[6] [7]), .B0 (n_52), .B1
       (\mem[7] [7]), .Y (n_58));
  AOI22XL g2088(.A0 (n_43), .A1 (\mem[14] [3]), .B0 (n_42), .B1
       (\mem[15] [3]), .Y (n_57));
  AOI22XL g2089(.A0 (n_41), .A1 (\mem[2] [5]), .B0 (n_52), .B1
       (\mem[7] [5]), .Y (n_56));
  AOI22XL g2090(.A0 (n_40), .A1 (\mem[12] [3]), .B0 (n_46), .B1
       (\mem[13] [3]), .Y (n_55));
  AOI22XL g2091(.A0 (n_53), .A1 (\mem[0] [6]), .B0 (n_52), .B1
       (\mem[7] [6]), .Y (n_54));
  AND2X1 g2092(.A (n_37), .B (n_30), .Y (n_53));
  NOR2XL g2093(.A (n_35), .B (n_32), .Y (n_52));
  NOR2BX1 g2094(.AN (n_30), .B (n_35), .Y (n_51));
  NOR2BX1 g2095(.AN (n_37), .B (n_36), .Y (n_50));
  NOR2XL g2096(.A (n_31), .B (n_29), .Y (n_49));
  NOR2BX1 g2097(.AN (n_37), .B (n_29), .Y (n_48));
  AND2X1 g2098(.A (n_33), .B (n_30), .Y (n_47));
  NOR2XL g2099(.A (n_34), .B (n_29), .Y (n_46));
  NOR2XL g2100(.A (n_31), .B (n_32), .Y (n_45));
  NOR2BX1 g2101(.AN (n_37), .B (n_32), .Y (n_44));
  NOR2XL g2102(.A (n_35), .B (n_36), .Y (n_43));
  NOR2XL g2103(.A (n_35), .B (n_29), .Y (n_42));
  NOR2BX1 g2104(.AN (n_30), .B (n_31), .Y (n_41));
  NOR2XL g2105(.A (n_34), .B (n_36), .Y (n_40));
  NOR2XL g2106(.A (n_34), .B (n_32), .Y (n_39));
  NOR2XL g2107(.A (n_31), .B (n_36), .Y (n_38));
  INVX1 g2108(.A (n_33), .Y (n_34));
  NOR2XL g2109(.A (raddr[2]), .B (raddr[1]), .Y (n_37));
  NAND2BX1 g2110(.AN (raddr[0]), .B (raddr[3]), .Y (n_36));
  NAND2XL g2111(.A (raddr[2]), .B (raddr[1]), .Y (n_35));
  NOR2BX1 g2112(.AN (raddr[2]), .B (raddr[1]), .Y (n_33));
  NAND2BX1 g2113(.AN (raddr[3]), .B (raddr[0]), .Y (n_32));
  NAND2BX1 g2114(.AN (raddr[2]), .B (raddr[1]), .Y (n_31));
  NOR2XL g2115(.A (raddr[3]), .B (raddr[0]), .Y (n_30));
  NAND2XL g2116(.A (raddr[3]), .B (raddr[0]), .Y (n_29));
  SDFFQXL \mem_reg[0][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[0] [0]),
       .SE (n_28), .Q (\mem[0] [0]));
  SDFFQXL \mem_reg[0][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[0] [1]),
       .SE (n_28), .Q (\mem[0] [1]));
  SDFFQXL \mem_reg[0][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[0] [2]),
       .SE (n_28), .Q (\mem[0] [2]));
  SDFFQXL \mem_reg[0][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[0] [3]),
       .SE (n_28), .Q (\mem[0] [3]));
  SDFFQXL \mem_reg[0][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[0] [4]),
       .SE (n_28), .Q (\mem[0] [4]));
  SDFFQXL \mem_reg[0][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[0] [5]),
       .SE (n_28), .Q (\mem[0] [5]));
  SDFFQXL \mem_reg[0][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[0] [6]),
       .SE (n_28), .Q (\mem[0] [6]));
  SDFFQXL \mem_reg[0][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[0] [7]),
       .SE (n_28), .Q (\mem[0] [7]));
  SDFFQXL \mem_reg[1][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[1] [0]),
       .SE (n_21), .Q (\mem[1] [0]));
  SDFFQXL \mem_reg[1][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[1] [1]),
       .SE (n_21), .Q (\mem[1] [1]));
  SDFFQXL \mem_reg[1][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[1] [2]),
       .SE (n_21), .Q (\mem[1] [2]));
  SDFFQXL \mem_reg[1][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[1] [3]),
       .SE (n_21), .Q (\mem[1] [3]));
  SDFFQXL \mem_reg[1][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[1] [4]),
       .SE (n_21), .Q (\mem[1] [4]));
  SDFFQXL \mem_reg[1][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[1] [5]),
       .SE (n_21), .Q (\mem[1] [5]));
  SDFFQXL \mem_reg[1][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[1] [6]),
       .SE (n_21), .Q (\mem[1] [6]));
  SDFFQXL \mem_reg[1][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[1] [7]),
       .SE (n_21), .Q (\mem[1] [7]));
  SDFFQXL \mem_reg[2][0] (.CK (wclk), .D (\mem[2] [0]), .SI (wdata[0]),
       .SE (n_13), .Q (\mem[2] [0]));
  SDFFQXL \mem_reg[2][1] (.CK (wclk), .D (\mem[2] [1]), .SI (wdata[1]),
       .SE (n_13), .Q (\mem[2] [1]));
  SDFFQXL \mem_reg[2][2] (.CK (wclk), .D (\mem[2] [2]), .SI (wdata[2]),
       .SE (n_13), .Q (\mem[2] [2]));
  SDFFQXL \mem_reg[2][3] (.CK (wclk), .D (\mem[2] [3]), .SI (wdata[3]),
       .SE (n_13), .Q (\mem[2] [3]));
  SDFFQXL \mem_reg[2][4] (.CK (wclk), .D (\mem[2] [4]), .SI (wdata[4]),
       .SE (n_13), .Q (\mem[2] [4]));
  SDFFQXL \mem_reg[2][5] (.CK (wclk), .D (\mem[2] [5]), .SI (wdata[5]),
       .SE (n_13), .Q (\mem[2] [5]));
  SDFFQXL \mem_reg[2][6] (.CK (wclk), .D (\mem[2] [6]), .SI (wdata[6]),
       .SE (n_13), .Q (\mem[2] [6]));
  SDFFQXL \mem_reg[2][7] (.CK (wclk), .D (\mem[2] [7]), .SI (wdata[7]),
       .SE (n_13), .Q (\mem[2] [7]));
  SDFFQXL \mem_reg[3][0] (.CK (wclk), .D (\mem[3] [0]), .SI (wdata[0]),
       .SE (n_24), .Q (\mem[3] [0]));
  SDFFQXL \mem_reg[3][1] (.CK (wclk), .D (\mem[3] [1]), .SI (wdata[1]),
       .SE (n_24), .Q (\mem[3] [1]));
  SDFFQXL \mem_reg[3][2] (.CK (wclk), .D (\mem[3] [2]), .SI (wdata[2]),
       .SE (n_24), .Q (\mem[3] [2]));
  SDFFQXL \mem_reg[3][3] (.CK (wclk), .D (\mem[3] [3]), .SI (wdata[3]),
       .SE (n_24), .Q (\mem[3] [3]));
  SDFFQXL \mem_reg[3][4] (.CK (wclk), .D (\mem[3] [4]), .SI (wdata[4]),
       .SE (n_24), .Q (\mem[3] [4]));
  SDFFQXL \mem_reg[3][5] (.CK (wclk), .D (\mem[3] [5]), .SI (wdata[5]),
       .SE (n_24), .Q (\mem[3] [5]));
  SDFFQXL \mem_reg[3][6] (.CK (wclk), .D (\mem[3] [6]), .SI (wdata[6]),
       .SE (n_24), .Q (\mem[3] [6]));
  SDFFQXL \mem_reg[3][7] (.CK (wclk), .D (\mem[3] [7]), .SI (wdata[7]),
       .SE (n_24), .Q (\mem[3] [7]));
  SDFFQXL \mem_reg[4][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[4] [0]),
       .SE (n_18), .Q (\mem[4] [0]));
  SDFFQXL \mem_reg[4][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[4] [1]),
       .SE (n_18), .Q (\mem[4] [1]));
  SDFFQXL \mem_reg[4][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[4] [2]),
       .SE (n_18), .Q (\mem[4] [2]));
  SDFFQXL \mem_reg[4][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[4] [3]),
       .SE (n_18), .Q (\mem[4] [3]));
  SDFFQXL \mem_reg[4][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[4] [4]),
       .SE (n_18), .Q (\mem[4] [4]));
  SDFFQXL \mem_reg[4][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[4] [5]),
       .SE (n_18), .Q (\mem[4] [5]));
  SDFFQXL \mem_reg[4][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[4] [6]),
       .SE (n_18), .Q (\mem[4] [6]));
  SDFFQXL \mem_reg[4][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[4] [7]),
       .SE (n_18), .Q (\mem[4] [7]));
  SDFFQXL \mem_reg[5][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[5] [0]),
       .SE (n_26), .Q (\mem[5] [0]));
  SDFFQXL \mem_reg[5][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[5] [1]),
       .SE (n_26), .Q (\mem[5] [1]));
  SDFFQXL \mem_reg[5][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[5] [2]),
       .SE (n_26), .Q (\mem[5] [2]));
  SDFFQXL \mem_reg[5][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[5] [3]),
       .SE (n_26), .Q (\mem[5] [3]));
  SDFFQXL \mem_reg[5][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[5] [4]),
       .SE (n_26), .Q (\mem[5] [4]));
  SDFFQXL \mem_reg[5][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[5] [5]),
       .SE (n_26), .Q (\mem[5] [5]));
  SDFFQXL \mem_reg[5][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[5] [6]),
       .SE (n_26), .Q (\mem[5] [6]));
  SDFFQXL \mem_reg[5][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[5] [7]),
       .SE (n_26), .Q (\mem[5] [7]));
  SDFFQXL \mem_reg[6][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[6] [0]),
       .SE (n_23), .Q (\mem[6] [0]));
  SDFFQXL \mem_reg[6][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[6] [1]),
       .SE (n_23), .Q (\mem[6] [1]));
  SDFFQXL \mem_reg[6][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[6] [2]),
       .SE (n_23), .Q (\mem[6] [2]));
  SDFFQXL \mem_reg[6][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[6] [3]),
       .SE (n_23), .Q (\mem[6] [3]));
  SDFFQXL \mem_reg[6][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[6] [4]),
       .SE (n_23), .Q (\mem[6] [4]));
  SDFFQXL \mem_reg[6][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[6] [5]),
       .SE (n_23), .Q (\mem[6] [5]));
  SDFFQXL \mem_reg[6][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[6] [6]),
       .SE (n_23), .Q (\mem[6] [6]));
  SDFFQXL \mem_reg[6][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[6] [7]),
       .SE (n_23), .Q (\mem[6] [7]));
  SDFFQXL \mem_reg[7][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[7] [0]),
       .SE (n_15), .Q (\mem[7] [0]));
  SDFFQXL \mem_reg[7][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[7] [1]),
       .SE (n_15), .Q (\mem[7] [1]));
  SDFFQXL \mem_reg[7][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[7] [2]),
       .SE (n_15), .Q (\mem[7] [2]));
  SDFFQXL \mem_reg[7][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[7] [3]),
       .SE (n_15), .Q (\mem[7] [3]));
  SDFFQXL \mem_reg[7][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[7] [4]),
       .SE (n_15), .Q (\mem[7] [4]));
  SDFFQXL \mem_reg[7][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[7] [5]),
       .SE (n_15), .Q (\mem[7] [5]));
  SDFFQXL \mem_reg[7][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[7] [6]),
       .SE (n_15), .Q (\mem[7] [6]));
  SDFFQXL \mem_reg[7][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[7] [7]),
       .SE (n_15), .Q (\mem[7] [7]));
  SDFFQXL \mem_reg[8][0] (.CK (wclk), .D (\mem[8] [0]), .SI (wdata[0]),
       .SE (n_14), .Q (\mem[8] [0]));
  SDFFQXL \mem_reg[8][1] (.CK (wclk), .D (\mem[8] [1]), .SI (wdata[1]),
       .SE (n_14), .Q (\mem[8] [1]));
  SDFFQXL \mem_reg[8][2] (.CK (wclk), .D (\mem[8] [2]), .SI (wdata[2]),
       .SE (n_14), .Q (\mem[8] [2]));
  SDFFQXL \mem_reg[8][3] (.CK (wclk), .D (\mem[8] [3]), .SI (wdata[3]),
       .SE (n_14), .Q (\mem[8] [3]));
  SDFFQXL \mem_reg[8][4] (.CK (wclk), .D (\mem[8] [4]), .SI (wdata[4]),
       .SE (n_14), .Q (\mem[8] [4]));
  SDFFQXL \mem_reg[8][5] (.CK (wclk), .D (\mem[8] [5]), .SI (wdata[5]),
       .SE (n_14), .Q (\mem[8] [5]));
  SDFFQXL \mem_reg[8][6] (.CK (wclk), .D (\mem[8] [6]), .SI (wdata[6]),
       .SE (n_14), .Q (\mem[8] [6]));
  SDFFQXL \mem_reg[8][7] (.CK (wclk), .D (\mem[8] [7]), .SI (wdata[7]),
       .SE (n_14), .Q (\mem[8] [7]));
  SDFFQXL \mem_reg[9][0] (.CK (wclk), .D (\mem[9] [0]), .SI (wdata[0]),
       .SE (n_22), .Q (\mem[9] [0]));
  SDFFQXL \mem_reg[9][1] (.CK (wclk), .D (\mem[9] [1]), .SI (wdata[1]),
       .SE (n_22), .Q (\mem[9] [1]));
  SDFFQXL \mem_reg[9][2] (.CK (wclk), .D (\mem[9] [2]), .SI (wdata[2]),
       .SE (n_22), .Q (\mem[9] [2]));
  SDFFQXL \mem_reg[9][3] (.CK (wclk), .D (\mem[9] [3]), .SI (wdata[3]),
       .SE (n_22), .Q (\mem[9] [3]));
  SDFFQXL \mem_reg[9][4] (.CK (wclk), .D (\mem[9] [4]), .SI (wdata[4]),
       .SE (n_22), .Q (\mem[9] [4]));
  SDFFQXL \mem_reg[9][5] (.CK (wclk), .D (\mem[9] [5]), .SI (wdata[5]),
       .SE (n_22), .Q (\mem[9] [5]));
  SDFFQXL \mem_reg[9][6] (.CK (wclk), .D (\mem[9] [6]), .SI (wdata[6]),
       .SE (n_22), .Q (\mem[9] [6]));
  SDFFQXL \mem_reg[9][7] (.CK (wclk), .D (\mem[9] [7]), .SI (wdata[7]),
       .SE (n_22), .Q (\mem[9] [7]));
  SDFFQXL \mem_reg[10][0] (.CK (wclk), .D (\mem[10] [0]), .SI
       (wdata[0]), .SE (n_17), .Q (\mem[10] [0]));
  SDFFQXL \mem_reg[10][1] (.CK (wclk), .D (\mem[10] [1]), .SI
       (wdata[1]), .SE (n_17), .Q (\mem[10] [1]));
  SDFFQXL \mem_reg[10][2] (.CK (wclk), .D (\mem[10] [2]), .SI
       (wdata[2]), .SE (n_17), .Q (\mem[10] [2]));
  SDFFQXL \mem_reg[10][3] (.CK (wclk), .D (\mem[10] [3]), .SI
       (wdata[3]), .SE (n_17), .Q (\mem[10] [3]));
  SDFFQXL \mem_reg[10][4] (.CK (wclk), .D (\mem[10] [4]), .SI
       (wdata[4]), .SE (n_17), .Q (\mem[10] [4]));
  SDFFQXL \mem_reg[10][5] (.CK (wclk), .D (\mem[10] [5]), .SI
       (wdata[5]), .SE (n_17), .Q (\mem[10] [5]));
  SDFFQXL \mem_reg[10][6] (.CK (wclk), .D (\mem[10] [6]), .SI
       (wdata[6]), .SE (n_17), .Q (\mem[10] [6]));
  SDFFQXL \mem_reg[10][7] (.CK (wclk), .D (\mem[10] [7]), .SI
       (wdata[7]), .SE (n_17), .Q (\mem[10] [7]));
  SDFFQXL \mem_reg[11][0] (.CK (wclk), .D (\mem[11] [0]), .SI
       (wdata[0]), .SE (n_19), .Q (\mem[11] [0]));
  SDFFQXL \mem_reg[11][1] (.CK (wclk), .D (\mem[11] [1]), .SI
       (wdata[1]), .SE (n_19), .Q (\mem[11] [1]));
  SDFFQXL \mem_reg[11][2] (.CK (wclk), .D (\mem[11] [2]), .SI
       (wdata[2]), .SE (n_19), .Q (\mem[11] [2]));
  SDFFQXL \mem_reg[11][3] (.CK (wclk), .D (\mem[11] [3]), .SI
       (wdata[3]), .SE (n_19), .Q (\mem[11] [3]));
  SDFFQXL \mem_reg[11][4] (.CK (wclk), .D (\mem[11] [4]), .SI
       (wdata[4]), .SE (n_19), .Q (\mem[11] [4]));
  SDFFQXL \mem_reg[11][5] (.CK (wclk), .D (\mem[11] [5]), .SI
       (wdata[5]), .SE (n_19), .Q (\mem[11] [5]));
  SDFFQXL \mem_reg[11][6] (.CK (wclk), .D (\mem[11] [6]), .SI
       (wdata[6]), .SE (n_19), .Q (\mem[11] [6]));
  SDFFQXL \mem_reg[11][7] (.CK (wclk), .D (\mem[11] [7]), .SI
       (wdata[7]), .SE (n_19), .Q (\mem[11] [7]));
  SDFFQXL \mem_reg[12][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[12]
       [0]), .SE (n_27), .Q (\mem[12] [0]));
  SDFFQXL \mem_reg[12][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[12]
       [1]), .SE (n_27), .Q (\mem[12] [1]));
  SDFFQXL \mem_reg[12][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[12]
       [2]), .SE (n_27), .Q (\mem[12] [2]));
  SDFFQXL \mem_reg[12][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[12]
       [3]), .SE (n_27), .Q (\mem[12] [3]));
  SDFFQXL \mem_reg[12][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[12]
       [4]), .SE (n_27), .Q (\mem[12] [4]));
  SDFFQXL \mem_reg[12][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[12]
       [5]), .SE (n_27), .Q (\mem[12] [5]));
  SDFFQXL \mem_reg[12][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[12]
       [6]), .SE (n_27), .Q (\mem[12] [6]));
  SDFFQXL \mem_reg[12][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[12]
       [7]), .SE (n_27), .Q (\mem[12] [7]));
  SDFFQXL \mem_reg[13][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[13]
       [0]), .SE (n_20), .Q (\mem[13] [0]));
  SDFFQXL \mem_reg[13][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[13]
       [1]), .SE (n_20), .Q (\mem[13] [1]));
  SDFFQXL \mem_reg[13][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[13]
       [2]), .SE (n_20), .Q (\mem[13] [2]));
  SDFFQXL \mem_reg[13][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[13]
       [3]), .SE (n_20), .Q (\mem[13] [3]));
  SDFFQXL \mem_reg[13][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[13]
       [4]), .SE (n_20), .Q (\mem[13] [4]));
  SDFFQXL \mem_reg[13][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[13]
       [5]), .SE (n_20), .Q (\mem[13] [5]));
  SDFFQXL \mem_reg[13][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[13]
       [6]), .SE (n_20), .Q (\mem[13] [6]));
  SDFFQXL \mem_reg[13][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[13]
       [7]), .SE (n_20), .Q (\mem[13] [7]));
  SDFFQXL \mem_reg[14][0] (.CK (wclk), .D (\mem[14] [0]), .SI
       (wdata[0]), .SE (n_25), .Q (\mem[14] [0]));
  SDFFQXL \mem_reg[14][1] (.CK (wclk), .D (\mem[14] [1]), .SI
       (wdata[1]), .SE (n_25), .Q (\mem[14] [1]));
  SDFFQXL \mem_reg[14][2] (.CK (wclk), .D (\mem[14] [2]), .SI
       (wdata[2]), .SE (n_25), .Q (\mem[14] [2]));
  SDFFQXL \mem_reg[14][3] (.CK (wclk), .D (\mem[14] [3]), .SI
       (wdata[3]), .SE (n_25), .Q (\mem[14] [3]));
  SDFFQXL \mem_reg[14][4] (.CK (wclk), .D (\mem[14] [4]), .SI
       (wdata[4]), .SE (n_25), .Q (\mem[14] [4]));
  SDFFQXL \mem_reg[14][5] (.CK (wclk), .D (\mem[14] [5]), .SI
       (wdata[5]), .SE (n_25), .Q (\mem[14] [5]));
  SDFFQXL \mem_reg[14][6] (.CK (wclk), .D (\mem[14] [6]), .SI
       (wdata[6]), .SE (n_25), .Q (\mem[14] [6]));
  SDFFQXL \mem_reg[14][7] (.CK (wclk), .D (\mem[14] [7]), .SI
       (wdata[7]), .SE (n_25), .Q (\mem[14] [7]));
  SDFFQXL \mem_reg[15][0] (.CK (wclk), .D (\mem[15] [0]), .SI
       (wdata[0]), .SE (n_16), .Q (\mem[15] [0]));
  SDFFQXL \mem_reg[15][1] (.CK (wclk), .D (\mem[15] [1]), .SI
       (wdata[1]), .SE (n_16), .Q (\mem[15] [1]));
  SDFFQXL \mem_reg[15][2] (.CK (wclk), .D (\mem[15] [2]), .SI
       (wdata[2]), .SE (n_16), .Q (\mem[15] [2]));
  SDFFQXL \mem_reg[15][3] (.CK (wclk), .D (\mem[15] [3]), .SI
       (wdata[3]), .SE (n_16), .Q (\mem[15] [3]));
  SDFFQXL \mem_reg[15][4] (.CK (wclk), .D (\mem[15] [4]), .SI
       (wdata[4]), .SE (n_16), .Q (\mem[15] [4]));
  SDFFQXL \mem_reg[15][5] (.CK (wclk), .D (\mem[15] [5]), .SI
       (wdata[5]), .SE (n_16), .Q (\mem[15] [5]));
  SDFFQXL \mem_reg[15][6] (.CK (wclk), .D (\mem[15] [6]), .SI
       (wdata[6]), .SE (n_16), .Q (\mem[15] [6]));
  SDFFQXL \mem_reg[15][7] (.CK (wclk), .D (\mem[15] [7]), .SI
       (wdata[7]), .SE (n_16), .Q (\mem[15] [7]));
  NAND2XL g828(.A (n_12), .B (n_0), .Y (n_28));
  NAND2XL g829(.A (n_9), .B (n_5), .Y (n_27));
  NAND2XL g830(.A (n_11), .B (n_0), .Y (n_26));
  NOR2BX1 g831(.AN (n_9), .B (n_6), .Y (n_25));
  NOR2XL g832(.A (n_10), .B (n_1), .Y (n_24));
  NAND2XL g833(.A (n_9), .B (n_2), .Y (n_23));
  NOR2XL g834(.A (n_10), .B (n_4), .Y (n_22));
  NAND2BX1 g835(.AN (n_10), .B (n_0), .Y (n_21));
  NAND2XL g836(.A (n_11), .B (n_5), .Y (n_20));
  NOR2XL g837(.A (n_10), .B (n_6), .Y (n_19));
  NAND2XL g838(.A (n_9), .B (n_0), .Y (n_18));
  NOR2BX1 g839(.AN (n_12), .B (n_6), .Y (n_17));
  NOR2BX1 g840(.AN (n_11), .B (n_6), .Y (n_16));
  NAND2XL g841(.A (n_11), .B (n_2), .Y (n_15));
  AND2X1 g842(.A (n_12), .B (n_5), .Y (n_14));
  AND2X1 g843(.A (n_12), .B (n_2), .Y (n_13));
  NOR2BX1 g844(.AN (n_7), .B (waddr[0]), .Y (n_12));
  NOR2BX1 g845(.AN (waddr[0]), .B (n_8), .Y (n_11));
  NAND2XL g846(.A (n_7), .B (waddr[0]), .Y (n_10));
  NOR2XL g847(.A (n_8), .B (waddr[0]), .Y (n_9));
  NAND2XL g848(.A (n_3), .B (waddr[2]), .Y (n_8));
  NOR2BX1 g849(.AN (n_3), .B (waddr[2]), .Y (n_7));
  INVX1 g850(.A (n_4), .Y (n_5));
  NAND2XL g851(.A (waddr[3]), .B (waddr[1]), .Y (n_6));
  NAND2BX1 g852(.AN (waddr[1]), .B (waddr[3]), .Y (n_4));
  INVX1 g853(.A (n_1), .Y (n_2));
  NOR2BXL g854(.AN (wclk_en), .B (wfull), .Y (n_3));
  NAND2BX1 g855(.AN (waddr[3]), .B (waddr[1]), .Y (n_1));
  NOR2XL g856(.A (waddr[3]), .B (waddr[1]), .Y (n_0));
endmodule

module rptr_empty_ADDR_SIZE4(rempty, raddr, rptr, rq2_wptr, rinc, rclk,
     rrst_n);
  input [4:0] rq2_wptr;
  input rinc, rclk, rrst_n;
  output rempty;
  output [3:0] raddr;
  output [4:0] rptr;
  wire [4:0] rq2_wptr;
  wire rinc, rclk, rrst_n;
  wire rempty;
  wire [3:0] raddr;
  wire [4:0] rptr;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  CLKXOR2X1 g188(.A (rptr[0]), .B (raddr[1]), .Y (raddr[0]));
  CLKXOR2X1 g189(.A (rptr[1]), .B (raddr[2]), .Y (raddr[1]));
  NOR2XL g190(.A (n_22), .B (n_23), .Y (rempty));
  CLKXOR2X1 g191(.A (rptr[2]), .B (raddr[3]), .Y (raddr[2]));
  NAND4XL g192(.A (n_18), .B (n_21), .C (n_19), .D (n_20), .Y (n_23));
  AOI21X1 g193(.A0 (rq2_wptr[4]), .A1 (rptr[4]), .B0 (n_17), .Y (n_22));
  XNOR2XL g194(.A (rq2_wptr[2]), .B (rptr[2]), .Y (n_21));
  XNOR2XL g195(.A (rq2_wptr[3]), .B (rptr[3]), .Y (n_20));
  XNOR2XL g196(.A (rq2_wptr[0]), .B (rptr[0]), .Y (n_19));
  XNOR2XL g197(.A (rq2_wptr[1]), .B (rptr[1]), .Y (n_18));
  CLKXOR2X1 g198(.A (rptr[3]), .B (rptr[4]), .Y (raddr[3]));
  NOR2XL g199(.A (rq2_wptr[4]), .B (rptr[4]), .Y (n_17));
  SDFFRHQX1 \rptr_reg[3] (.RN (rrst_n), .CK (rclk), .D (n_13), .SI
       (n_14), .SE (n_16), .Q (rptr[3]));
  DFFRHQX1 \rptr_reg[4] (.RN (rrst_n), .CK (rclk), .D (n_16), .Q
       (rptr[4]));
  SDFFRHQX1 \rptr_reg[2] (.RN (rrst_n), .CK (rclk), .D (n_13), .SI
       (n_14), .SE (n_10), .Q (rptr[2]));
  OAI21X1 g136(.A0 (n_11), .A1 (rptr[4]), .B0 (n_15), .Y (n_16));
  NAND2XL g137(.A (n_11), .B (rptr[4]), .Y (n_15));
  INVX1 g138(.A (n_13), .Y (n_14));
  SDFFRHQX1 \rptr_reg[1] (.RN (rrst_n), .CK (rclk), .D (n_6), .SI
       (n_7), .SE (n_10), .Q (rptr[1]));
  OAI21X1 g140(.A0 (n_8), .A1 (raddr[3]), .B0 (n_12), .Y (n_13));
  NAND2XL g141(.A (n_8), .B (raddr[3]), .Y (n_12));
  NAND2BX1 g142(.AN (n_8), .B (raddr[3]), .Y (n_11));
  SDFFRHQX1 \rptr_reg[0] (.RN (rrst_n), .CK (rclk), .D (n_6), .SI
       (n_7), .SE (n_3), .Q (rptr[0]));
  OAI21X1 g144(.A0 (n_4), .A1 (raddr[2]), .B0 (n_9), .Y (n_10));
  NAND2XL g145(.A (n_4), .B (raddr[2]), .Y (n_9));
  NAND2BX1 g146(.AN (n_4), .B (raddr[2]), .Y (n_8));
  INVX1 g147(.A (n_6), .Y (n_7));
  OAI21X1 g148(.A0 (n_1), .A1 (raddr[1]), .B0 (n_5), .Y (n_6));
  NAND2XL g149(.A (n_1), .B (raddr[1]), .Y (n_5));
  NAND2BX1 g150(.AN (n_1), .B (raddr[1]), .Y (n_4));
  OAI21XL g151(.A0 (raddr[0]), .A1 (n_0), .B0 (n_2), .Y (n_3));
  NAND2XL g152(.A (n_0), .B (raddr[0]), .Y (n_2));
  NAND2BX1 g153(.AN (n_0), .B (raddr[0]), .Y (n_1));
  NAND2BX1 g154(.AN (rempty), .B (rinc), .Y (n_0));
endmodule

module two_ff_sync_SIZE5(q2, din, clk, rst_n);
  input [4:0] din;
  input clk, rst_n;
  output [4:0] q2;
  wire [4:0] din;
  wire clk, rst_n;
  wire [4:0] q2;
  wire [4:0] q1;
  DFFRHQX1 \q2_reg[4] (.RN (rst_n), .CK (clk), .D (q1[4]), .Q (q2[4]));
  DFFRHQX1 \q2_reg[3] (.RN (rst_n), .CK (clk), .D (q1[3]), .Q (q2[3]));
  DFFRHQX1 \q2_reg[1] (.RN (rst_n), .CK (clk), .D (q1[1]), .Q (q2[1]));
  DFFRHQX1 \q2_reg[0] (.RN (rst_n), .CK (clk), .D (q1[0]), .Q (q2[0]));
  DFFRHQX1 \q2_reg[2] (.RN (rst_n), .CK (clk), .D (q1[2]), .Q (q2[2]));
  DFFRHQX1 \q1_reg[2] (.RN (rst_n), .CK (clk), .D (din[2]), .Q (q1[2]));
  DFFRHQX1 \q1_reg[3] (.RN (rst_n), .CK (clk), .D (din[3]), .Q (q1[3]));
  DFFRHQX1 \q1_reg[4] (.RN (rst_n), .CK (clk), .D (din[4]), .Q (q1[4]));
  DFFRHQX1 \q1_reg[1] (.RN (rst_n), .CK (clk), .D (din[1]), .Q (q1[1]));
  DFFRHQX1 \q1_reg[0] (.RN (rst_n), .CK (clk), .D (din[0]), .Q (q1[0]));
endmodule

module two_ff_sync_SIZE5_1(q2, din, clk, rst_n);
  input [4:0] din;
  input clk, rst_n;
  output [4:0] q2;
  wire [4:0] din;
  wire clk, rst_n;
  wire [4:0] q2;
  wire [4:0] q1;
  DFFRHQX1 \q2_reg[4] (.RN (rst_n), .CK (clk), .D (q1[4]), .Q (q2[4]));
  DFFRHQX1 \q2_reg[3] (.RN (rst_n), .CK (clk), .D (q1[3]), .Q (q2[3]));
  DFFRHQX1 \q2_reg[1] (.RN (rst_n), .CK (clk), .D (q1[1]), .Q (q2[1]));
  DFFRHQX1 \q2_reg[0] (.RN (rst_n), .CK (clk), .D (q1[0]), .Q (q2[0]));
  DFFRHQX1 \q2_reg[2] (.RN (rst_n), .CK (clk), .D (q1[2]), .Q (q2[2]));
  DFFRHQX1 \q1_reg[2] (.RN (rst_n), .CK (clk), .D (din[2]), .Q (q1[2]));
  DFFRHQX1 \q1_reg[3] (.RN (rst_n), .CK (clk), .D (din[3]), .Q (q1[3]));
  DFFRHQX1 \q1_reg[4] (.RN (rst_n), .CK (clk), .D (din[4]), .Q (q1[4]));
  DFFRHQX1 \q1_reg[1] (.RN (rst_n), .CK (clk), .D (din[1]), .Q (q1[1]));
  DFFRHQX1 \q1_reg[0] (.RN (rst_n), .CK (clk), .D (din[0]), .Q (q1[0]));
endmodule

module wptr_full_ADDR_SIZE4(wfull, waddr, wptr, wq2_rptr, winc, wclk,
     wrst_n);
  input [4:0] wq2_rptr;
  input winc, wclk, wrst_n;
  output wfull;
  output [3:0] waddr;
  output [4:0] wptr;
  wire [4:0] wq2_rptr;
  wire winc, wclk, wrst_n;
  wire wfull;
  wire [3:0] waddr;
  wire [4:0] wptr;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  CLKXOR2X1 g195(.A (wptr[0]), .B (waddr[1]), .Y (waddr[0]));
  CLKXOR2X1 g196(.A (wptr[1]), .B (waddr[2]), .Y (waddr[1]));
  NOR4X1 g197(.A (n_20), .B (n_18), .C (n_21), .D (n_22), .Y (wfull));
  CLKXOR2X1 g198(.A (wptr[2]), .B (waddr[3]), .Y (waddr[2]));
  OAI211X1 g199(.A0 (wq2_rptr[3]), .A1 (wptr[3]), .B0 (n_17), .C0
       (n_19), .Y (n_22));
  XNOR2X1 g200(.A (wq2_rptr[4]), .B (wptr[4]), .Y (n_21));
  CLKXOR2X1 g201(.A (wq2_rptr[2]), .B (wptr[2]), .Y (n_20));
  XNOR2XL g202(.A (wq2_rptr[1]), .B (wptr[1]), .Y (n_19));
  CLKXOR2X1 g203(.A (wq2_rptr[0]), .B (wptr[0]), .Y (n_18));
  CLKXOR2X1 g204(.A (wptr[3]), .B (wptr[4]), .Y (waddr[3]));
  NAND2XL g205(.A (wq2_rptr[3]), .B (wptr[3]), .Y (n_17));
  SDFFRHQX1 \wptr_reg[3] (.RN (wrst_n), .CK (wclk), .D (n_13), .SI
       (n_14), .SE (n_16), .Q (wptr[3]));
  DFFRHQX1 \wptr_reg[4] (.RN (wrst_n), .CK (wclk), .D (n_16), .Q
       (wptr[4]));
  SDFFRHQX1 \wptr_reg[2] (.RN (wrst_n), .CK (wclk), .D (n_13), .SI
       (n_14), .SE (n_10), .Q (wptr[2]));
  OAI21X1 g140(.A0 (n_11), .A1 (wptr[4]), .B0 (n_15), .Y (n_16));
  NAND2XL g141(.A (n_11), .B (wptr[4]), .Y (n_15));
  INVX1 g142(.A (n_13), .Y (n_14));
  SDFFRHQX1 \wptr_reg[1] (.RN (wrst_n), .CK (wclk), .D (n_7), .SI
       (n_6), .SE (n_10), .Q (wptr[1]));
  OAI21X1 g144(.A0 (n_8), .A1 (waddr[3]), .B0 (n_12), .Y (n_13));
  NAND2XL g145(.A (n_8), .B (waddr[3]), .Y (n_12));
  NAND2BX1 g146(.AN (n_8), .B (waddr[3]), .Y (n_11));
  SDFFRHQX1 \wptr_reg[0] (.RN (wrst_n), .CK (wclk), .D (n_7), .SI
       (n_6), .SE (n_3), .Q (wptr[0]));
  OAI21X1 g148(.A0 (n_4), .A1 (waddr[2]), .B0 (n_9), .Y (n_10));
  NAND2XL g149(.A (n_4), .B (waddr[2]), .Y (n_9));
  NAND2BX1 g150(.AN (n_4), .B (waddr[2]), .Y (n_8));
  INVX1 g151(.A (n_6), .Y (n_7));
  AOI21X1 g152(.A0 (n_1), .A1 (waddr[1]), .B0 (n_5), .Y (n_6));
  NOR2XL g153(.A (n_1), .B (waddr[1]), .Y (n_5));
  NAND2BX1 g154(.AN (n_1), .B (waddr[1]), .Y (n_4));
  OAI21XL g155(.A0 (waddr[0]), .A1 (n_0), .B0 (n_2), .Y (n_3));
  NAND2XL g156(.A (n_0), .B (waddr[0]), .Y (n_2));
  NAND2BX1 g157(.AN (n_0), .B (waddr[0]), .Y (n_1));
  NAND2BX1 g158(.AN (wfull), .B (winc), .Y (n_0));
endmodule

module FIFO(rdata, wfull, rempty, wdata, winc, wclk, wrst_n, rinc,
     rclk, rrst_n);
  input [7:0] wdata;
  input winc, wclk, wrst_n, rinc, rclk, rrst_n;
  output [7:0] rdata;
  output wfull, rempty;
  wire [7:0] wdata;
  wire winc, wclk, wrst_n, rinc, rclk, rrst_n;
  wire [7:0] rdata;
  wire wfull, rempty;
  wire [3:0] waddr;
  wire [3:0] raddr;
  wire [7:0] rdata_raw;
  wire [4:0] rq2_wptr;
  wire [4:0] rptr;
  wire [4:0] wq2_rptr;
  wire [4:0] wptr;
  FIFO_memory_DATA_SIZE8_ADDR_SIZE4 fifomem(.rdata (rdata_raw), .wdata
       (wdata), .waddr (waddr), .raddr (raddr), .wclk_en (winc), .wfull
       (wfull), .wclk (wclk));
  rptr_empty_ADDR_SIZE4 rptr_empty_inst(.rempty (rempty), .raddr
       (raddr), .rptr (rptr), .rq2_wptr (rq2_wptr), .rinc (rinc), .rclk
       (rclk), .rrst_n (rrst_n));
  two_ff_sync_SIZE5 sync_r2w(.q2 (wq2_rptr), .din (rptr), .clk (wclk),
       .rst_n (wrst_n));
  two_ff_sync_SIZE5_1 sync_w2r(.q2 (rq2_wptr), .din (wptr), .clk
       (rclk), .rst_n (rrst_n));
  wptr_full_ADDR_SIZE4 wptr_full_inst(.wfull (wfull), .waddr (waddr),
       .wptr (wptr), .wq2_rptr (wq2_rptr), .winc (winc), .wclk (wclk),
       .wrst_n (wrst_n));
  DFFRHQX1 \rdata_reg[7] (.RN (rrst_n), .CK (rclk), .D (rdata_raw[7]),
       .Q (rdata[7]));
  DFFRHQX1 \rdata_reg[6] (.RN (rrst_n), .CK (rclk), .D (rdata_raw[6]),
       .Q (rdata[6]));
  DFFRHQX1 \rdata_reg[4] (.RN (rrst_n), .CK (rclk), .D (rdata_raw[4]),
       .Q (rdata[4]));
  DFFRHQX1 \rdata_reg[0] (.RN (rrst_n), .CK (rclk), .D (rdata_raw[0]),
       .Q (rdata[0]));
  DFFRHQX1 \rdata_reg[3] (.RN (rrst_n), .CK (rclk), .D (rdata_raw[3]),
       .Q (rdata[3]));
  DFFRHQX1 \rdata_reg[5] (.RN (rrst_n), .CK (rclk), .D (rdata_raw[5]),
       .Q (rdata[5]));
  DFFRHQX1 \rdata_reg[2] (.RN (rrst_n), .CK (rclk), .D (rdata_raw[2]),
       .Q (rdata[2]));
  DFFRHQX1 \rdata_reg[1] (.RN (rrst_n), .CK (rclk), .D (rdata_raw[1]),
       .Q (rdata[1]));
endmodule

