
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Oct 14 2025 20:51:25 IST (Oct 14 2025 15:21:25 UTC)

// Verification Directory fv/FIFO 

module FIFO_memory_DATA_SIZE8_ADDR_SIZE4(rdata, wdata, waddr, raddr,
     wclk_en, wfull, wclk);
  input [7:0] wdata;
  input [3:0] waddr, raddr;
  input wclk_en, wfull, wclk;
  output [7:0] rdata;
  wire [7:0] wdata;
  wire [3:0] waddr, raddr;
  wire wclk_en, wfull, wclk;
  wire [7:0] rdata;
  wire [7:0] \mem[0] ;
  wire [7:0] \mem[1] ;
  wire [7:0] \mem[2] ;
  wire [7:0] \mem[3] ;
  wire [7:0] \mem[4] ;
  wire [7:0] \mem[5] ;
  wire [7:0] \mem[6] ;
  wire [7:0] \mem[7] ;
  wire [7:0] \mem[8] ;
  wire [7:0] \mem[9] ;
  wire [7:0] \mem[10] ;
  wire [7:0] \mem[11] ;
  wire [7:0] \mem[12] ;
  wire [7:0] \mem[13] ;
  wire [7:0] \mem[14] ;
  wire [7:0] \mem[15] ;
  wire n_126, n_127, n_128, n_129, n_130, n_131, n_132, n_133;
  wire n_134, n_135, n_136, n_137, n_138, n_139, n_140, n_141;
  wire n_142, n_143, n_144, n_145, n_146, n_147, n_148, n_149;
  wire n_150, n_151, n_152, n_153, n_154, n_155, n_156, n_157;
  wire n_158, n_159, n_160, n_161, n_162, n_163, n_164, n_165;
  wire n_166, n_167, n_168, n_169, n_170, n_171, n_172, n_173;
  wire n_174, n_175, n_176, n_177, n_178, n_179, n_180, n_181;
  wire n_182, n_183, n_184, n_185, n_186, n_187, n_188, n_189;
  wire n_190, n_191, n_192, n_193, n_194, n_195, n_196, n_197;
  wire n_198, n_199, n_200, n_201, n_202, n_203, n_204, n_205;
  wire n_206, n_207, n_208, n_209, n_210, n_211, n_212, n_213;
  wire n_214, n_215, n_216, n_217, n_218, n_219, n_220, n_221;
  wire n_222, n_223, n_224, n_225, n_226, n_227, n_228, n_229;
  wire n_230, n_231, n_232, n_233, n_234, n_262, n_263, n_264;
  wire n_265, n_266, n_267, n_268, n_269, n_270, n_271, n_272;
  wire n_273, n_274, n_275, n_276, n_277;
  SDFFQX1 \mem_reg[0][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[0] [0]),
       .SE (n_262), .Q (\mem[0] [0]));
  SDFFQX1 \mem_reg[0][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[0] [1]),
       .SE (n_262), .Q (\mem[0] [1]));
  SDFFQX1 \mem_reg[0][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[0] [2]),
       .SE (n_262), .Q (\mem[0] [2]));
  SDFFQX1 \mem_reg[0][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[0] [3]),
       .SE (n_262), .Q (\mem[0] [3]));
  SDFFQX1 \mem_reg[0][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[0] [4]),
       .SE (n_262), .Q (\mem[0] [4]));
  SDFFQX1 \mem_reg[0][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[0] [5]),
       .SE (n_262), .Q (\mem[0] [5]));
  SDFFQX1 \mem_reg[0][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[0] [6]),
       .SE (n_262), .Q (\mem[0] [6]));
  SDFFQX1 \mem_reg[0][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[0] [7]),
       .SE (n_262), .Q (\mem[0] [7]));
  SDFFQX1 \mem_reg[1][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[1] [0]),
       .SE (n_269), .Q (\mem[1] [0]));
  SDFFQX1 \mem_reg[1][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[1] [1]),
       .SE (n_269), .Q (\mem[1] [1]));
  SDFFQX1 \mem_reg[1][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[1] [2]),
       .SE (n_269), .Q (\mem[1] [2]));
  SDFFQX1 \mem_reg[1][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[1] [3]),
       .SE (n_269), .Q (\mem[1] [3]));
  SDFFQX1 \mem_reg[1][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[1] [4]),
       .SE (n_269), .Q (\mem[1] [4]));
  SDFFQX1 \mem_reg[1][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[1] [5]),
       .SE (n_269), .Q (\mem[1] [5]));
  SDFFQX1 \mem_reg[1][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[1] [6]),
       .SE (n_269), .Q (\mem[1] [6]));
  SDFFQX1 \mem_reg[1][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[1] [7]),
       .SE (n_269), .Q (\mem[1] [7]));
  SDFFQX1 \mem_reg[2][0] (.CK (wclk), .D (\mem[2] [0]), .SI (wdata[0]),
       .SE (n_277), .Q (\mem[2] [0]));
  SDFFQX1 \mem_reg[2][1] (.CK (wclk), .D (\mem[2] [1]), .SI (wdata[1]),
       .SE (n_277), .Q (\mem[2] [1]));
  SDFFQX1 \mem_reg[2][2] (.CK (wclk), .D (\mem[2] [2]), .SI (wdata[2]),
       .SE (n_277), .Q (\mem[2] [2]));
  SDFFQX1 \mem_reg[2][3] (.CK (wclk), .D (\mem[2] [3]), .SI (wdata[3]),
       .SE (n_277), .Q (\mem[2] [3]));
  SDFFQX1 \mem_reg[2][4] (.CK (wclk), .D (\mem[2] [4]), .SI (wdata[4]),
       .SE (n_277), .Q (\mem[2] [4]));
  SDFFQX1 \mem_reg[2][5] (.CK (wclk), .D (\mem[2] [5]), .SI (wdata[5]),
       .SE (n_277), .Q (\mem[2] [5]));
  SDFFQX1 \mem_reg[2][6] (.CK (wclk), .D (\mem[2] [6]), .SI (wdata[6]),
       .SE (n_277), .Q (\mem[2] [6]));
  SDFFQX1 \mem_reg[2][7] (.CK (wclk), .D (\mem[2] [7]), .SI (wdata[7]),
       .SE (n_277), .Q (\mem[2] [7]));
  SDFFQX1 \mem_reg[3][0] (.CK (wclk), .D (\mem[3] [0]), .SI (wdata[0]),
       .SE (n_266), .Q (\mem[3] [0]));
  SDFFQX1 \mem_reg[3][1] (.CK (wclk), .D (\mem[3] [1]), .SI (wdata[1]),
       .SE (n_266), .Q (\mem[3] [1]));
  SDFFQX1 \mem_reg[3][2] (.CK (wclk), .D (\mem[3] [2]), .SI (wdata[2]),
       .SE (n_266), .Q (\mem[3] [2]));
  SDFFQX1 \mem_reg[3][3] (.CK (wclk), .D (\mem[3] [3]), .SI (wdata[3]),
       .SE (n_266), .Q (\mem[3] [3]));
  SDFFQX1 \mem_reg[3][4] (.CK (wclk), .D (\mem[3] [4]), .SI (wdata[4]),
       .SE (n_266), .Q (\mem[3] [4]));
  SDFFQX1 \mem_reg[3][5] (.CK (wclk), .D (\mem[3] [5]), .SI (wdata[5]),
       .SE (n_266), .Q (\mem[3] [5]));
  SDFFQX1 \mem_reg[3][6] (.CK (wclk), .D (\mem[3] [6]), .SI (wdata[6]),
       .SE (n_266), .Q (\mem[3] [6]));
  SDFFQX1 \mem_reg[3][7] (.CK (wclk), .D (\mem[3] [7]), .SI (wdata[7]),
       .SE (n_266), .Q (\mem[3] [7]));
  SDFFQX1 \mem_reg[4][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[4] [0]),
       .SE (n_272), .Q (\mem[4] [0]));
  SDFFQX1 \mem_reg[4][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[4] [1]),
       .SE (n_272), .Q (\mem[4] [1]));
  SDFFQX1 \mem_reg[4][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[4] [2]),
       .SE (n_272), .Q (\mem[4] [2]));
  SDFFQX1 \mem_reg[4][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[4] [3]),
       .SE (n_272), .Q (\mem[4] [3]));
  SDFFQX1 \mem_reg[4][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[4] [4]),
       .SE (n_272), .Q (\mem[4] [4]));
  SDFFQX1 \mem_reg[4][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[4] [5]),
       .SE (n_272), .Q (\mem[4] [5]));
  SDFFQX1 \mem_reg[4][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[4] [6]),
       .SE (n_272), .Q (\mem[4] [6]));
  SDFFQX1 \mem_reg[4][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[4] [7]),
       .SE (n_272), .Q (\mem[4] [7]));
  SDFFQX1 \mem_reg[5][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[5] [0]),
       .SE (n_264), .Q (\mem[5] [0]));
  SDFFQX1 \mem_reg[5][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[5] [1]),
       .SE (n_264), .Q (\mem[5] [1]));
  SDFFQX1 \mem_reg[5][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[5] [2]),
       .SE (n_264), .Q (\mem[5] [2]));
  SDFFQX1 \mem_reg[5][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[5] [3]),
       .SE (n_264), .Q (\mem[5] [3]));
  SDFFQX1 \mem_reg[5][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[5] [4]),
       .SE (n_264), .Q (\mem[5] [4]));
  SDFFQX1 \mem_reg[5][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[5] [5]),
       .SE (n_264), .Q (\mem[5] [5]));
  SDFFQX1 \mem_reg[5][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[5] [6]),
       .SE (n_264), .Q (\mem[5] [6]));
  SDFFQX1 \mem_reg[5][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[5] [7]),
       .SE (n_264), .Q (\mem[5] [7]));
  SDFFQX1 \mem_reg[6][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[6] [0]),
       .SE (n_267), .Q (\mem[6] [0]));
  SDFFQX1 \mem_reg[6][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[6] [1]),
       .SE (n_267), .Q (\mem[6] [1]));
  SDFFQX1 \mem_reg[6][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[6] [2]),
       .SE (n_267), .Q (\mem[6] [2]));
  SDFFQX1 \mem_reg[6][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[6] [3]),
       .SE (n_267), .Q (\mem[6] [3]));
  SDFFQX1 \mem_reg[6][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[6] [4]),
       .SE (n_267), .Q (\mem[6] [4]));
  SDFFQX1 \mem_reg[6][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[6] [5]),
       .SE (n_267), .Q (\mem[6] [5]));
  SDFFQX1 \mem_reg[6][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[6] [6]),
       .SE (n_267), .Q (\mem[6] [6]));
  SDFFQX1 \mem_reg[6][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[6] [7]),
       .SE (n_267), .Q (\mem[6] [7]));
  SDFFQX1 \mem_reg[7][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[7] [0]),
       .SE (n_275), .Q (\mem[7] [0]));
  SDFFQX1 \mem_reg[7][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[7] [1]),
       .SE (n_275), .Q (\mem[7] [1]));
  SDFFQX1 \mem_reg[7][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[7] [2]),
       .SE (n_275), .Q (\mem[7] [2]));
  SDFFQX1 \mem_reg[7][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[7] [3]),
       .SE (n_275), .Q (\mem[7] [3]));
  SDFFQX1 \mem_reg[7][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[7] [4]),
       .SE (n_275), .Q (\mem[7] [4]));
  SDFFQX1 \mem_reg[7][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[7] [5]),
       .SE (n_275), .Q (\mem[7] [5]));
  SDFFQX1 \mem_reg[7][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[7] [6]),
       .SE (n_275), .Q (\mem[7] [6]));
  SDFFQX1 \mem_reg[7][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[7] [7]),
       .SE (n_275), .Q (\mem[7] [7]));
  SDFFQX1 \mem_reg[8][0] (.CK (wclk), .D (\mem[8] [0]), .SI (wdata[0]),
       .SE (n_276), .Q (\mem[8] [0]));
  SDFFQX1 \mem_reg[8][1] (.CK (wclk), .D (\mem[8] [1]), .SI (wdata[1]),
       .SE (n_276), .Q (\mem[8] [1]));
  SDFFQX1 \mem_reg[8][2] (.CK (wclk), .D (\mem[8] [2]), .SI (wdata[2]),
       .SE (n_276), .Q (\mem[8] [2]));
  SDFFQX1 \mem_reg[8][3] (.CK (wclk), .D (\mem[8] [3]), .SI (wdata[3]),
       .SE (n_276), .Q (\mem[8] [3]));
  SDFFQX1 \mem_reg[8][4] (.CK (wclk), .D (\mem[8] [4]), .SI (wdata[4]),
       .SE (n_276), .Q (\mem[8] [4]));
  SDFFQX1 \mem_reg[8][5] (.CK (wclk), .D (\mem[8] [5]), .SI (wdata[5]),
       .SE (n_276), .Q (\mem[8] [5]));
  SDFFQX1 \mem_reg[8][6] (.CK (wclk), .D (\mem[8] [6]), .SI (wdata[6]),
       .SE (n_276), .Q (\mem[8] [6]));
  SDFFQX1 \mem_reg[8][7] (.CK (wclk), .D (\mem[8] [7]), .SI (wdata[7]),
       .SE (n_276), .Q (\mem[8] [7]));
  SDFFQX1 \mem_reg[9][0] (.CK (wclk), .D (\mem[9] [0]), .SI (wdata[0]),
       .SE (n_268), .Q (\mem[9] [0]));
  SDFFQX1 \mem_reg[9][1] (.CK (wclk), .D (\mem[9] [1]), .SI (wdata[1]),
       .SE (n_268), .Q (\mem[9] [1]));
  SDFFQX1 \mem_reg[9][2] (.CK (wclk), .D (\mem[9] [2]), .SI (wdata[2]),
       .SE (n_268), .Q (\mem[9] [2]));
  SDFFQX1 \mem_reg[9][3] (.CK (wclk), .D (\mem[9] [3]), .SI (wdata[3]),
       .SE (n_268), .Q (\mem[9] [3]));
  SDFFQX1 \mem_reg[9][4] (.CK (wclk), .D (\mem[9] [4]), .SI (wdata[4]),
       .SE (n_268), .Q (\mem[9] [4]));
  SDFFQX1 \mem_reg[9][5] (.CK (wclk), .D (\mem[9] [5]), .SI (wdata[5]),
       .SE (n_268), .Q (\mem[9] [5]));
  SDFFQX1 \mem_reg[9][6] (.CK (wclk), .D (\mem[9] [6]), .SI (wdata[6]),
       .SE (n_268), .Q (\mem[9] [6]));
  SDFFQX1 \mem_reg[9][7] (.CK (wclk), .D (\mem[9] [7]), .SI (wdata[7]),
       .SE (n_268), .Q (\mem[9] [7]));
  SDFFQX1 \mem_reg[10][0] (.CK (wclk), .D (\mem[10] [0]), .SI
       (wdata[0]), .SE (n_273), .Q (\mem[10] [0]));
  SDFFQX1 \mem_reg[10][1] (.CK (wclk), .D (\mem[10] [1]), .SI
       (wdata[1]), .SE (n_273), .Q (\mem[10] [1]));
  SDFFQX1 \mem_reg[10][2] (.CK (wclk), .D (\mem[10] [2]), .SI
       (wdata[2]), .SE (n_273), .Q (\mem[10] [2]));
  SDFFQX1 \mem_reg[10][3] (.CK (wclk), .D (\mem[10] [3]), .SI
       (wdata[3]), .SE (n_273), .Q (\mem[10] [3]));
  SDFFQX1 \mem_reg[10][4] (.CK (wclk), .D (\mem[10] [4]), .SI
       (wdata[4]), .SE (n_273), .Q (\mem[10] [4]));
  SDFFQX1 \mem_reg[10][5] (.CK (wclk), .D (\mem[10] [5]), .SI
       (wdata[5]), .SE (n_273), .Q (\mem[10] [5]));
  SDFFQX1 \mem_reg[10][6] (.CK (wclk), .D (\mem[10] [6]), .SI
       (wdata[6]), .SE (n_273), .Q (\mem[10] [6]));
  SDFFQX1 \mem_reg[10][7] (.CK (wclk), .D (\mem[10] [7]), .SI
       (wdata[7]), .SE (n_273), .Q (\mem[10] [7]));
  SDFFQX1 \mem_reg[11][0] (.CK (wclk), .D (\mem[11] [0]), .SI
       (wdata[0]), .SE (n_271), .Q (\mem[11] [0]));
  SDFFQX1 \mem_reg[11][1] (.CK (wclk), .D (\mem[11] [1]), .SI
       (wdata[1]), .SE (n_271), .Q (\mem[11] [1]));
  SDFFQX1 \mem_reg[11][2] (.CK (wclk), .D (\mem[11] [2]), .SI
       (wdata[2]), .SE (n_271), .Q (\mem[11] [2]));
  SDFFQX1 \mem_reg[11][3] (.CK (wclk), .D (\mem[11] [3]), .SI
       (wdata[3]), .SE (n_271), .Q (\mem[11] [3]));
  SDFFQX1 \mem_reg[11][4] (.CK (wclk), .D (\mem[11] [4]), .SI
       (wdata[4]), .SE (n_271), .Q (\mem[11] [4]));
  SDFFQX1 \mem_reg[11][5] (.CK (wclk), .D (\mem[11] [5]), .SI
       (wdata[5]), .SE (n_271), .Q (\mem[11] [5]));
  SDFFQX1 \mem_reg[11][6] (.CK (wclk), .D (\mem[11] [6]), .SI
       (wdata[6]), .SE (n_271), .Q (\mem[11] [6]));
  SDFFQX1 \mem_reg[11][7] (.CK (wclk), .D (\mem[11] [7]), .SI
       (wdata[7]), .SE (n_271), .Q (\mem[11] [7]));
  SDFFQX1 \mem_reg[12][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[12]
       [0]), .SE (n_263), .Q (\mem[12] [0]));
  SDFFQX1 \mem_reg[12][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[12]
       [1]), .SE (n_263), .Q (\mem[12] [1]));
  SDFFQX1 \mem_reg[12][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[12]
       [2]), .SE (n_263), .Q (\mem[12] [2]));
  SDFFQX1 \mem_reg[12][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[12]
       [3]), .SE (n_263), .Q (\mem[12] [3]));
  SDFFQX1 \mem_reg[12][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[12]
       [4]), .SE (n_263), .Q (\mem[12] [4]));
  SDFFQX1 \mem_reg[12][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[12]
       [5]), .SE (n_263), .Q (\mem[12] [5]));
  SDFFQX1 \mem_reg[12][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[12]
       [6]), .SE (n_263), .Q (\mem[12] [6]));
  SDFFQX1 \mem_reg[12][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[12]
       [7]), .SE (n_263), .Q (\mem[12] [7]));
  SDFFQX1 \mem_reg[13][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[13]
       [0]), .SE (n_270), .Q (\mem[13] [0]));
  SDFFQX1 \mem_reg[13][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[13]
       [1]), .SE (n_270), .Q (\mem[13] [1]));
  SDFFQX1 \mem_reg[13][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[13]
       [2]), .SE (n_270), .Q (\mem[13] [2]));
  SDFFQX1 \mem_reg[13][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[13]
       [3]), .SE (n_270), .Q (\mem[13] [3]));
  SDFFQX1 \mem_reg[13][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[13]
       [4]), .SE (n_270), .Q (\mem[13] [4]));
  SDFFQX1 \mem_reg[13][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[13]
       [5]), .SE (n_270), .Q (\mem[13] [5]));
  SDFFQX1 \mem_reg[13][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[13]
       [6]), .SE (n_270), .Q (\mem[13] [6]));
  SDFFQX1 \mem_reg[13][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[13]
       [7]), .SE (n_270), .Q (\mem[13] [7]));
  SDFFQX1 \mem_reg[14][0] (.CK (wclk), .D (\mem[14] [0]), .SI
       (wdata[0]), .SE (n_265), .Q (\mem[14] [0]));
  SDFFQX1 \mem_reg[14][1] (.CK (wclk), .D (\mem[14] [1]), .SI
       (wdata[1]), .SE (n_265), .Q (\mem[14] [1]));
  SDFFQX1 \mem_reg[14][2] (.CK (wclk), .D (\mem[14] [2]), .SI
       (wdata[2]), .SE (n_265), .Q (\mem[14] [2]));
  SDFFQX1 \mem_reg[14][3] (.CK (wclk), .D (\mem[14] [3]), .SI
       (wdata[3]), .SE (n_265), .Q (\mem[14] [3]));
  SDFFQX1 \mem_reg[14][4] (.CK (wclk), .D (\mem[14] [4]), .SI
       (wdata[4]), .SE (n_265), .Q (\mem[14] [4]));
  SDFFQX1 \mem_reg[14][5] (.CK (wclk), .D (\mem[14] [5]), .SI
       (wdata[5]), .SE (n_265), .Q (\mem[14] [5]));
  SDFFQX1 \mem_reg[14][6] (.CK (wclk), .D (\mem[14] [6]), .SI
       (wdata[6]), .SE (n_265), .Q (\mem[14] [6]));
  SDFFQX1 \mem_reg[14][7] (.CK (wclk), .D (\mem[14] [7]), .SI
       (wdata[7]), .SE (n_265), .Q (\mem[14] [7]));
  SDFFQX1 \mem_reg[15][0] (.CK (wclk), .D (\mem[15] [0]), .SI
       (wdata[0]), .SE (n_274), .Q (\mem[15] [0]));
  SDFFQX1 \mem_reg[15][1] (.CK (wclk), .D (\mem[15] [1]), .SI
       (wdata[1]), .SE (n_274), .Q (\mem[15] [1]));
  SDFFQX1 \mem_reg[15][2] (.CK (wclk), .D (\mem[15] [2]), .SI
       (wdata[2]), .SE (n_274), .Q (\mem[15] [2]));
  SDFFQX1 \mem_reg[15][3] (.CK (wclk), .D (\mem[15] [3]), .SI
       (wdata[3]), .SE (n_274), .Q (\mem[15] [3]));
  SDFFQX1 \mem_reg[15][4] (.CK (wclk), .D (\mem[15] [4]), .SI
       (wdata[4]), .SE (n_274), .Q (\mem[15] [4]));
  SDFFQX1 \mem_reg[15][5] (.CK (wclk), .D (\mem[15] [5]), .SI
       (wdata[5]), .SE (n_274), .Q (\mem[15] [5]));
  SDFFQX1 \mem_reg[15][6] (.CK (wclk), .D (\mem[15] [6]), .SI
       (wdata[6]), .SE (n_274), .Q (\mem[15] [6]));
  SDFFQX1 \mem_reg[15][7] (.CK (wclk), .D (\mem[15] [7]), .SI
       (wdata[7]), .SE (n_274), .Q (\mem[15] [7]));
  NAND4XL g4330(.A (n_212), .B (n_214), .C (n_215), .D (n_234), .Y
       (rdata[2]));
  NAND4XL g4331(.A (n_163), .B (n_198), .C (n_203), .D (n_228), .Y
       (rdata[6]));
  NAND4XL g4332(.A (n_174), .B (n_217), .C (n_181), .D (n_232), .Y
       (rdata[7]));
  NAND4XL g4333(.A (n_200), .B (n_202), .C (n_204), .D (n_231), .Y
       (rdata[1]));
  NAND4XL g4334(.A (n_165), .B (n_213), .C (n_216), .D (n_233), .Y
       (rdata[5]));
  NAND4XL g4335(.A (n_186), .B (n_187), .C (n_189), .D (n_230), .Y
       (rdata[0]));
  NAND4XL g4336(.A (n_195), .B (n_193), .C (n_188), .D (n_229), .Y
       (rdata[4]));
  NAND4XL g4337(.A (n_169), .B (n_171), .C (n_172), .D (n_227), .Y
       (rdata[3]));
  AOI221XL g4338(.A0 (\mem[9] [2]), .A1 (n_160), .B0 (\mem[11] [2]),
       .B1 (n_156), .C0 (n_225), .Y (n_234));
  AOI221XL g4339(.A0 (\mem[4] [5]), .A1 (n_161), .B0 (\mem[5] [5]), .B1
       (n_154), .C0 (n_224), .Y (n_233));
  AOI221XL g4340(.A0 (\mem[8] [7]), .A1 (n_152), .B0 (\mem[9] [7]), .B1
       (n_160), .C0 (n_223), .Y (n_232));
  AOI221XL g4341(.A0 (\mem[4] [1]), .A1 (n_161), .B0 (\mem[6] [1]), .B1
       (n_155), .C0 (n_226), .Y (n_231));
  AOI221XL g4342(.A0 (\mem[6] [0]), .A1 (n_155), .B0 (\mem[1] [0]), .B1
       (n_150), .C0 (n_220), .Y (n_230));
  AOI221XL g4343(.A0 (\mem[12] [4]), .A1 (n_148), .B0 (\mem[13] [4]),
       .B1 (n_151), .C0 (n_222), .Y (n_229));
  AOI221XL g4344(.A0 (\mem[6] [6]), .A1 (n_155), .B0 (\mem[7] [6]), .B1
       (n_157), .C0 (n_221), .Y (n_228));
  AOI221XL g4345(.A0 (\mem[6] [3]), .A1 (n_155), .B0 (\mem[1] [3]), .B1
       (n_150), .C0 (n_219), .Y (n_227));
  NAND4XL g4346(.A (n_194), .B (n_196), .C (n_197), .D (n_192), .Y
       (n_226));
  NAND4XL g4347(.A (n_207), .B (n_209), .C (n_206), .D (n_210), .Y
       (n_225));
  NAND4XL g4348(.A (n_201), .B (n_205), .C (n_208), .D (n_199), .Y
       (n_224));
  NAND4XL g4349(.A (n_167), .B (n_173), .C (n_211), .D (n_218), .Y
       (n_223));
  NAND4XL g4350(.A (n_177), .B (n_180), .C (n_175), .D (n_183), .Y
       (n_222));
  NAND4XL g4351(.A (n_170), .B (n_176), .C (n_178), .D (n_168), .Y
       (n_221));
  NAND4XL g4352(.A (n_182), .B (n_184), .C (n_185), .D (n_179), .Y
       (n_220));
  NAND4XL g4353(.A (n_190), .B (n_164), .C (n_166), .D (n_191), .Y
       (n_219));
  AOI22XL g4354(.A0 (n_155), .A1 (\mem[6] [7]), .B0 (n_157), .B1
       (\mem[7] [7]), .Y (n_218));
  AOI22XL g4355(.A0 (n_148), .A1 (\mem[12] [7]), .B0 (n_158), .B1
       (\mem[15] [7]), .Y (n_217));
  AOI22XL g4356(.A0 (n_162), .A1 (\mem[2] [5]), .B0 (n_155), .B1
       (\mem[6] [5]), .Y (n_216));
  AOI22XL g4357(.A0 (n_149), .A1 (\mem[10] [2]), .B0 (n_153), .B1
       (\mem[14] [2]), .Y (n_215));
  AOI22XL g4358(.A0 (n_152), .A1 (\mem[8] [2]), .B0 (n_151), .B1
       (\mem[13] [2]), .Y (n_214));
  AOI22XL g4359(.A0 (n_159), .A1 (\mem[0] [5]), .B0 (n_157), .B1
       (\mem[7] [5]), .Y (n_213));
  AOI22XL g4360(.A0 (n_148), .A1 (\mem[12] [2]), .B0 (n_158), .B1
       (\mem[15] [2]), .Y (n_212));
  AOI22XL g4361(.A0 (n_159), .A1 (\mem[0] [7]), .B0 (n_150), .B1
       (\mem[1] [7]), .Y (n_211));
  AOI22XL g4362(.A0 (n_162), .A1 (\mem[2] [2]), .B0 (n_147), .B1
       (\mem[3] [2]), .Y (n_210));
  AOI22XL g4363(.A0 (n_161), .A1 (\mem[4] [2]), .B0 (n_154), .B1
       (\mem[5] [2]), .Y (n_209));
  AOI22XL g4364(.A0 (n_149), .A1 (\mem[10] [5]), .B0 (n_156), .B1
       (\mem[11] [5]), .Y (n_208));
  AOI22XL g4365(.A0 (n_155), .A1 (\mem[6] [2]), .B0 (n_157), .B1
       (\mem[7] [2]), .Y (n_207));
  AOI22XL g4366(.A0 (n_159), .A1 (\mem[0] [2]), .B0 (n_150), .B1
       (\mem[1] [2]), .Y (n_206));
  AOI22XL g4367(.A0 (n_148), .A1 (\mem[12] [5]), .B0 (n_151), .B1
       (\mem[13] [5]), .Y (n_205));
  AOI22XL g4368(.A0 (n_162), .A1 (\mem[2] [1]), .B0 (n_154), .B1
       (\mem[5] [1]), .Y (n_204));
  AOI22XL g4369(.A0 (n_162), .A1 (\mem[2] [6]), .B0 (n_154), .B1
       (\mem[5] [6]), .Y (n_203));
  AOI22XL g4370(.A0 (n_159), .A1 (\mem[0] [1]), .B0 (n_147), .B1
       (\mem[3] [1]), .Y (n_202));
  AOI22XL g4371(.A0 (n_153), .A1 (\mem[14] [5]), .B0 (n_158), .B1
       (\mem[15] [5]), .Y (n_201));
  AOI22XL g4372(.A0 (n_150), .A1 (\mem[1] [1]), .B0 (n_157), .B1
       (\mem[7] [1]), .Y (n_200));
  AOI22XL g4373(.A0 (n_152), .A1 (\mem[8] [5]), .B0 (n_160), .B1
       (\mem[9] [5]), .Y (n_199));
  AOI22XL g4374(.A0 (n_161), .A1 (\mem[4] [6]), .B0 (n_150), .B1
       (\mem[1] [6]), .Y (n_198));
  AOI22XL g4375(.A0 (n_153), .A1 (\mem[14] [1]), .B0 (n_158), .B1
       (\mem[15] [1]), .Y (n_197));
  AOI22XL g4376(.A0 (n_149), .A1 (\mem[10] [1]), .B0 (n_156), .B1
       (\mem[11] [1]), .Y (n_196));
  AOI22XL g4377(.A0 (n_160), .A1 (\mem[9] [4]), .B0 (n_156), .B1
       (\mem[11] [4]), .Y (n_195));
  AOI22XL g4378(.A0 (n_148), .A1 (\mem[12] [1]), .B0 (n_151), .B1
       (\mem[13] [1]), .Y (n_194));
  AOI22XL g4379(.A0 (n_152), .A1 (\mem[8] [4]), .B0 (n_158), .B1
       (\mem[15] [4]), .Y (n_193));
  AOI22XL g4380(.A0 (n_152), .A1 (\mem[8] [1]), .B0 (n_160), .B1
       (\mem[9] [1]), .Y (n_192));
  AOI22XL g4381(.A0 (n_152), .A1 (\mem[8] [3]), .B0 (n_160), .B1
       (\mem[9] [3]), .Y (n_191));
  AOI22XL g4382(.A0 (n_148), .A1 (\mem[12] [3]), .B0 (n_151), .B1
       (\mem[13] [3]), .Y (n_190));
  AOI22XL g4383(.A0 (n_161), .A1 (\mem[4] [0]), .B0 (n_154), .B1
       (\mem[5] [0]), .Y (n_189));
  AOI22XL g4384(.A0 (n_149), .A1 (\mem[10] [4]), .B0 (n_153), .B1
       (\mem[14] [4]), .Y (n_188));
  AOI22XL g4385(.A0 (n_159), .A1 (\mem[0] [0]), .B0 (n_147), .B1
       (\mem[3] [0]), .Y (n_187));
  AOI22XL g4386(.A0 (n_162), .A1 (\mem[2] [0]), .B0 (n_157), .B1
       (\mem[7] [0]), .Y (n_186));
  AOI22XL g4387(.A0 (n_149), .A1 (\mem[10] [0]), .B0 (n_156), .B1
       (\mem[11] [0]), .Y (n_185));
  AOI22XL g4388(.A0 (n_148), .A1 (\mem[12] [0]), .B0 (n_151), .B1
       (\mem[13] [0]), .Y (n_184));
  AOI22XL g4389(.A0 (n_155), .A1 (\mem[6] [4]), .B0 (n_157), .B1
       (\mem[7] [4]), .Y (n_183));
  AOI22XL g4390(.A0 (n_153), .A1 (\mem[14] [0]), .B0 (n_158), .B1
       (\mem[15] [0]), .Y (n_182));
  AOI22XL g4391(.A0 (n_153), .A1 (\mem[14] [7]), .B0 (n_156), .B1
       (\mem[11] [7]), .Y (n_181));
  AOI22XL g4392(.A0 (n_161), .A1 (\mem[4] [4]), .B0 (n_154), .B1
       (\mem[5] [4]), .Y (n_180));
  AOI22XL g4393(.A0 (n_152), .A1 (\mem[8] [0]), .B0 (n_160), .B1
       (\mem[9] [0]), .Y (n_179));
  AOI22XL g4394(.A0 (n_153), .A1 (\mem[14] [6]), .B0 (n_158), .B1
       (\mem[15] [6]), .Y (n_178));
  AOI22XL g4395(.A0 (n_162), .A1 (\mem[2] [4]), .B0 (n_147), .B1
       (\mem[3] [4]), .Y (n_177));
  AOI22XL g4396(.A0 (n_148), .A1 (\mem[12] [6]), .B0 (n_151), .B1
       (\mem[13] [6]), .Y (n_176));
  AOI22XL g4397(.A0 (n_159), .A1 (\mem[0] [4]), .B0 (n_150), .B1
       (\mem[1] [4]), .Y (n_175));
  AOI22XL g4398(.A0 (n_149), .A1 (\mem[10] [7]), .B0 (n_151), .B1
       (\mem[13] [7]), .Y (n_174));
  AOI22XL g4399(.A0 (n_162), .A1 (\mem[2] [7]), .B0 (n_147), .B1
       (\mem[3] [7]), .Y (n_173));
  AOI22XL g4400(.A0 (n_161), .A1 (\mem[4] [3]), .B0 (n_157), .B1
       (\mem[7] [3]), .Y (n_172));
  AOI22XL g4401(.A0 (n_159), .A1 (\mem[0] [3]), .B0 (n_154), .B1
       (\mem[5] [3]), .Y (n_171));
  AOI22XL g4402(.A0 (n_149), .A1 (\mem[10] [6]), .B0 (n_156), .B1
       (\mem[11] [6]), .Y (n_170));
  AOI22XL g4403(.A0 (n_162), .A1 (\mem[2] [3]), .B0 (n_147), .B1
       (\mem[3] [3]), .Y (n_169));
  AOI22XL g4404(.A0 (n_152), .A1 (\mem[8] [6]), .B0 (n_160), .B1
       (\mem[9] [6]), .Y (n_168));
  AOI22XL g4405(.A0 (n_161), .A1 (\mem[4] [7]), .B0 (n_154), .B1
       (\mem[5] [7]), .Y (n_167));
  AOI22XL g4406(.A0 (n_153), .A1 (\mem[14] [3]), .B0 (n_158), .B1
       (\mem[15] [3]), .Y (n_166));
  AOI22XL g4407(.A0 (n_150), .A1 (\mem[1] [5]), .B0 (n_147), .B1
       (\mem[3] [5]), .Y (n_165));
  AOI22XL g4408(.A0 (n_149), .A1 (\mem[10] [3]), .B0 (n_156), .B1
       (\mem[11] [3]), .Y (n_164));
  AOI22XL g4409(.A0 (n_159), .A1 (\mem[0] [6]), .B0 (n_147), .B1
       (\mem[3] [6]), .Y (n_163));
  NOR2BXL g4410(.AN (n_141), .B (n_143), .Y (n_162));
  NOR2BXL g4411(.AN (n_141), .B (n_140), .Y (n_161));
  NOR2BXL g4412(.AN (n_146), .B (n_139), .Y (n_160));
  AND2X1 g4413(.A (n_146), .B (n_141), .Y (n_159));
  NOR2XL g4414(.A (n_144), .B (n_139), .Y (n_158));
  NOR2XL g4415(.A (n_144), .B (n_142), .Y (n_157));
  NOR2XL g4416(.A (n_143), .B (n_139), .Y (n_156));
  NOR2BXL g4417(.AN (n_141), .B (n_144), .Y (n_155));
  NOR2XL g4418(.A (n_140), .B (n_142), .Y (n_154));
  NOR2XL g4419(.A (n_144), .B (n_145), .Y (n_153));
  NOR2BXL g4420(.AN (n_146), .B (n_145), .Y (n_152));
  NOR2XL g4421(.A (n_140), .B (n_139), .Y (n_151));
  NOR2BXL g4422(.AN (n_146), .B (n_142), .Y (n_150));
  NOR2XL g4423(.A (n_143), .B (n_145), .Y (n_149));
  NOR2XL g4424(.A (n_140), .B (n_145), .Y (n_148));
  NOR2XL g4425(.A (n_143), .B (n_142), .Y (n_147));
  NOR2XL g4426(.A (raddr[2]), .B (raddr[1]), .Y (n_146));
  NAND2BXL g4427(.AN (raddr[0]), .B (raddr[3]), .Y (n_145));
  NAND2XL g4428(.A (raddr[2]), .B (raddr[1]), .Y (n_144));
  NAND2BXL g4429(.AN (raddr[2]), .B (raddr[1]), .Y (n_143));
  NAND2BXL g4430(.AN (raddr[3]), .B (raddr[0]), .Y (n_142));
  NOR2XL g4431(.A (raddr[3]), .B (raddr[0]), .Y (n_141));
  NAND2BXL g4432(.AN (raddr[1]), .B (raddr[2]), .Y (n_140));
  NAND2XL g4433(.A (raddr[3]), .B (raddr[0]), .Y (n_139));
  NAND2XL g1494(.A (n_130), .B (n_135), .Y (n_267));
  NAND2XL g1495(.A (n_128), .B (n_138), .Y (n_264));
  NOR2BXL g1496(.AN (n_135), .B (n_131), .Y (n_265));
  NOR2XL g1497(.A (n_129), .B (n_136), .Y (n_266));
  NAND2XL g1498(.A (n_128), .B (n_137), .Y (n_262));
  NAND2XL g1499(.A (n_126), .B (n_135), .Y (n_263));
  NOR2XL g1500(.A (n_127), .B (n_136), .Y (n_268));
  NAND2BXL g1501(.AN (n_136), .B (n_128), .Y (n_269));
  NAND2XL g1502(.A (n_130), .B (n_138), .Y (n_275));
  NAND2XL g1503(.A (n_128), .B (n_135), .Y (n_272));
  NOR2BXL g1504(.AN (n_137), .B (n_131), .Y (n_273));
  NOR2BXL g1505(.AN (n_138), .B (n_131), .Y (n_274));
  NOR2XL g1506(.A (n_131), .B (n_136), .Y (n_271));
  NOR2BXL g1507(.AN (n_137), .B (n_127), .Y (n_276));
  NOR2BXL g1508(.AN (n_137), .B (n_129), .Y (n_277));
  NAND2XL g1509(.A (n_126), .B (n_138), .Y (n_270));
  NOR2BXL g1510(.AN (waddr[0]), .B (n_134), .Y (n_138));
  NOR2BXL g1511(.AN (n_133), .B (waddr[0]), .Y (n_137));
  NAND2XL g1512(.A (n_133), .B (waddr[0]), .Y (n_136));
  NOR2XL g1513(.A (n_134), .B (waddr[0]), .Y (n_135));
  NAND2XL g1514(.A (waddr[2]), .B (n_132), .Y (n_134));
  NOR2BXL g1515(.AN (n_132), .B (waddr[2]), .Y (n_133));
  NOR2BXL g1516(.AN (wclk_en), .B (wfull), .Y (n_132));
  NAND2XL g1517(.A (waddr[3]), .B (waddr[1]), .Y (n_131));
  CLKINVX1 g1518(.A (n_130), .Y (n_129));
  CLKINVX1 g1519(.A (n_127), .Y (n_126));
  NOR2BXL g1520(.AN (waddr[1]), .B (waddr[3]), .Y (n_130));
  NOR2XL g1521(.A (waddr[3]), .B (waddr[1]), .Y (n_128));
  NAND2BXL g1522(.AN (waddr[1]), .B (waddr[3]), .Y (n_127));
endmodule

module rptr_empty_ADDR_SIZE4(rempty, raddr, rptr, rq2_wptr, rinc, rclk,
     rrst_n, DFT_sdi, DFT_sen);
  input [4:0] rq2_wptr;
  input rinc, rclk, rrst_n, DFT_sdi, DFT_sen;
  output rempty;
  output [3:0] raddr;
  output [4:0] rptr;
  wire [4:0] rq2_wptr;
  wire rinc, rclk, rrst_n, DFT_sdi, DFT_sen;
  wire rempty;
  wire [3:0] raddr;
  wire [4:0] rptr;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_60, n_61, n_62, n_63, n_64;
  SDFFRHQX1 \rptr_reg[0] (.RN (rrst_n), .CK (rclk), .D (n_63), .SI
       (n_41), .SE (n_64), .Q (rptr[0]));
  SDFFRHQX1 \rptr_reg[1] (.RN (rrst_n), .CK (rclk), .D (n_63), .SI
       (n_41), .SE (n_62), .Q (rptr[1]));
  SDFFRHQX1 \rptr_reg[2] (.RN (rrst_n), .CK (rclk), .D (n_61), .SI
       (n_40), .SE (n_62), .Q (rptr[2]));
  SDFFRHQX1 \rptr_reg[3] (.RN (rrst_n), .CK (rclk), .D (n_61), .SI
       (n_40), .SE (n_60), .Q (rptr[3]));
  INVXL g227(.A (n_61), .Y (n_40));
  INVXL g226(.A (n_63), .Y (n_41));
  MXI2XL g474(.A (rptr[4]), .B (n_24), .S0 (n_39), .Y (n_60));
  MXI2XL g475(.A (n_27), .B (raddr[3]), .S0 (n_38), .Y (n_61));
  NAND2XL g476(.A (raddr[3]), .B (n_38), .Y (n_39));
  MXI2XL g477(.A (raddr[2]), .B (n_32), .S0 (n_37), .Y (n_62));
  NOR2XL g478(.A (n_32), .B (n_37), .Y (n_38));
  MXI2XL g479(.A (n_33), .B (raddr[1]), .S0 (n_36), .Y (n_63));
  NAND2XL g480(.A (raddr[1]), .B (n_36), .Y (n_37));
  OAI21XL g481(.A0 (raddr[0]), .A1 (n_34), .B0 (n_35), .Y (n_64));
  NOR2BXL g482(.AN (raddr[0]), .B (n_34), .Y (n_36));
  NAND2XL g483(.A (n_34), .B (raddr[0]), .Y (n_35));
  MXI2XL g484(.A (n_33), .B (raddr[1]), .S0 (rptr[0]), .Y (raddr[0]));
  NAND2BXL g485(.AN (rempty), .B (rinc), .Y (n_34));
  CLKINVX1 g486(.A (raddr[1]), .Y (n_33));
  MXI2XL g487(.A (n_32), .B (raddr[2]), .S0 (rptr[1]), .Y (raddr[1]));
  AND2X8 g488(.A (n_30), .B (n_31), .Y (rempty));
  CLKINVX1 g489(.A (n_32), .Y (raddr[2]));
  MXI2XL g490(.A (raddr[3]), .B (n_27), .S0 (rptr[2]), .Y (n_32));
  NOR4XL g491(.A (n_28), .B (n_26), .C (n_25), .D (n_29), .Y (n_31));
  MXI2XL g492(.A (rptr[4]), .B (n_24), .S0 (rq2_wptr[4]), .Y (n_30));
  CLKXOR2X1 g493(.A (rq2_wptr[1]), .B (rptr[1]), .Y (n_29));
  CLKXOR2X1 g494(.A (rq2_wptr[0]), .B (rptr[0]), .Y (n_28));
  CLKINVX1 g495(.A (raddr[3]), .Y (n_27));
  CLKXOR2X1 g496(.A (rq2_wptr[3]), .B (rptr[3]), .Y (n_26));
  CLKXOR2X1 g497(.A (rq2_wptr[2]), .B (rptr[2]), .Y (n_25));
  MXI2XL g498(.A (n_24), .B (rptr[4]), .S0 (rptr[3]), .Y (raddr[3]));
  INVX1 g499(.A (rptr[4]), .Y (n_24));
  SDFFRHQX1 \rptr_reg[4] (.RN (rrst_n), .CK (rclk), .D (n_60), .SI
       (DFT_sdi), .SE (DFT_sen), .Q (rptr[4]));
endmodule

module two_ff_sync_SIZE5(q2, din, clk, rst_n, DFT_sdi, DFT_sen);
  input [4:0] din;
  input clk, rst_n, DFT_sdi, DFT_sen;
  output [4:0] q2;
  wire [4:0] din;
  wire clk, rst_n, DFT_sdi, DFT_sen;
  wire [4:0] q2;
  wire [4:0] q1;
  SDFFRHQX1 \q2_reg[4] (.RN (rst_n), .CK (clk), .D (q1[4]), .SI
       (q2[3]), .SE (DFT_sen), .Q (q2[4]));
  SDFFRHQX1 \q2_reg[3] (.RN (rst_n), .CK (clk), .D (q1[3]), .SI
       (q2[2]), .SE (DFT_sen), .Q (q2[3]));
  SDFFRHQX1 \q2_reg[1] (.RN (rst_n), .CK (clk), .D (q1[1]), .SI
       (q2[0]), .SE (DFT_sen), .Q (q2[1]));
  SDFFRHQX1 \q2_reg[0] (.RN (rst_n), .CK (clk), .D (q1[0]), .SI
       (q1[4]), .SE (DFT_sen), .Q (q2[0]));
  SDFFRHQX1 \q2_reg[2] (.RN (rst_n), .CK (clk), .D (q1[2]), .SI
       (q2[1]), .SE (DFT_sen), .Q (q2[2]));
  SDFFRHQX1 \q1_reg[2] (.RN (rst_n), .CK (clk), .D (din[2]), .SI
       (q1[1]), .SE (DFT_sen), .Q (q1[2]));
  SDFFRHQX1 \q1_reg[3] (.RN (rst_n), .CK (clk), .D (din[3]), .SI
       (q1[2]), .SE (DFT_sen), .Q (q1[3]));
  SDFFRHQX1 \q1_reg[4] (.RN (rst_n), .CK (clk), .D (din[4]), .SI
       (q1[3]), .SE (DFT_sen), .Q (q1[4]));
  SDFFRHQX1 \q1_reg[1] (.RN (rst_n), .CK (clk), .D (din[1]), .SI
       (q1[0]), .SE (DFT_sen), .Q (q1[1]));
  SDFFRHQX1 \q1_reg[0] (.RN (rst_n), .CK (clk), .D (din[0]), .SI
       (DFT_sdi), .SE (DFT_sen), .Q (q1[0]));
endmodule

module two_ff_sync_SIZE5_1(q2, din, clk, rst_n, DFT_sdi, DFT_sen);
  input [4:0] din;
  input clk, rst_n, DFT_sdi, DFT_sen;
  output [4:0] q2;
  wire [4:0] din;
  wire clk, rst_n, DFT_sdi, DFT_sen;
  wire [4:0] q2;
  wire [4:0] q1;
  SDFFRHQX1 \q2_reg[4] (.RN (rst_n), .CK (clk), .D (q1[4]), .SI
       (q2[3]), .SE (DFT_sen), .Q (q2[4]));
  SDFFRHQX1 \q2_reg[3] (.RN (rst_n), .CK (clk), .D (q1[3]), .SI
       (q2[2]), .SE (DFT_sen), .Q (q2[3]));
  SDFFRHQX1 \q2_reg[1] (.RN (rst_n), .CK (clk), .D (q1[1]), .SI
       (q2[0]), .SE (DFT_sen), .Q (q2[1]));
  SDFFRHQX1 \q2_reg[0] (.RN (rst_n), .CK (clk), .D (q1[0]), .SI
       (q1[4]), .SE (DFT_sen), .Q (q2[0]));
  SDFFRHQX1 \q2_reg[2] (.RN (rst_n), .CK (clk), .D (q1[2]), .SI
       (q2[1]), .SE (DFT_sen), .Q (q2[2]));
  SDFFRHQX1 \q1_reg[2] (.RN (rst_n), .CK (clk), .D (din[2]), .SI
       (q1[1]), .SE (DFT_sen), .Q (q1[2]));
  SDFFRHQX1 \q1_reg[3] (.RN (rst_n), .CK (clk), .D (din[3]), .SI
       (q1[2]), .SE (DFT_sen), .Q (q1[3]));
  SDFFRHQX1 \q1_reg[4] (.RN (rst_n), .CK (clk), .D (din[4]), .SI
       (q1[3]), .SE (DFT_sen), .Q (q1[4]));
  SDFFRHQX1 \q1_reg[1] (.RN (rst_n), .CK (clk), .D (din[1]), .SI
       (q1[0]), .SE (DFT_sen), .Q (q1[1]));
  SDFFRHQX1 \q1_reg[0] (.RN (rst_n), .CK (clk), .D (din[0]), .SI
       (DFT_sdi), .SE (DFT_sen), .Q (q1[0]));
endmodule

module wptr_full_ADDR_SIZE4(wfull, waddr, wptr, wq2_rptr, winc, wclk,
     wrst_n, DFT_sen);
  input [4:0] wq2_rptr;
  input winc, wclk, wrst_n, DFT_sen;
  output wfull;
  output [3:0] waddr;
  output [4:0] wptr;
  wire [4:0] wq2_rptr;
  wire winc, wclk, wrst_n, DFT_sen;
  wire wfull;
  wire [3:0] waddr;
  wire [4:0] wptr;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_59, n_60, n_61, n_62, n_63;
  SDFFRHQX1 \wptr_reg[0] (.RN (wrst_n), .CK (wclk), .D (n_39), .SI
       (n_62), .SE (n_63), .Q (wptr[0]));
  SDFFRHQX1 \wptr_reg[1] (.RN (wrst_n), .CK (wclk), .D (n_39), .SI
       (n_62), .SE (n_61), .Q (wptr[1]));
  SDFFRHQX1 \wptr_reg[2] (.RN (wrst_n), .CK (wclk), .D (n_60), .SI
       (n_40), .SE (n_61), .Q (wptr[2]));
  SDFFRHQX1 \wptr_reg[3] (.RN (wrst_n), .CK (wclk), .D (n_60), .SI
       (n_40), .SE (n_59), .Q (wptr[3]));
  INVXL g226(.A (n_62), .Y (n_39));
  INVXL g225(.A (n_60), .Y (n_40));
  MXI2XL g479(.A (wptr[4]), .B (n_23), .S0 (n_38), .Y (n_59));
  MXI2XL g480(.A (n_27), .B (waddr[3]), .S0 (n_37), .Y (n_60));
  NAND2XL g481(.A (waddr[3]), .B (n_37), .Y (n_38));
  MXI2XL g482(.A (waddr[2]), .B (n_31), .S0 (n_36), .Y (n_61));
  NOR2XL g483(.A (n_31), .B (n_36), .Y (n_37));
  OAI21XL g484(.A0 (n_35), .A1 (waddr[1]), .B0 (n_36), .Y (n_62));
  NAND2XL g485(.A (waddr[1]), .B (n_35), .Y (n_36));
  OAI21XL g486(.A0 (waddr[0]), .A1 (n_33), .B0 (n_34), .Y (n_63));
  NOR2BXL g487(.AN (waddr[0]), .B (n_33), .Y (n_35));
  NAND2XL g488(.A (n_33), .B (waddr[0]), .Y (n_34));
  CLKXOR2X1 g489(.A (wptr[0]), .B (waddr[1]), .Y (waddr[0]));
  NAND2BXL g490(.AN (wfull), .B (winc), .Y (n_33));
  MXI2XL g491(.A (n_31), .B (waddr[2]), .S0 (wptr[1]), .Y (waddr[1]));
  AND3X8 g492(.A (n_26), .B (n_28), .C (n_32), .Y (wfull));
  NOR2XL g493(.A (n_25), .B (n_30), .Y (n_32));
  INVX1 g494(.A (n_31), .Y (waddr[2]));
  MXI2XL g495(.A (waddr[3]), .B (n_27), .S0 (wptr[2]), .Y (n_31));
  OAI211XL g496(.A0 (wptr[3]), .A1 (wq2_rptr[3]), .B0 (n_24), .C0
       (n_29), .Y (n_30));
  MXI2XL g497(.A (n_23), .B (wptr[4]), .S0 (wq2_rptr[4]), .Y (n_29));
  XNOR2X1 g498(.A (wq2_rptr[2]), .B (wptr[2]), .Y (n_28));
  CLKINVX1 g499(.A (waddr[3]), .Y (n_27));
  XNOR2X1 g500(.A (wq2_rptr[0]), .B (wptr[0]), .Y (n_26));
  CLKXOR2X1 g501(.A (wq2_rptr[1]), .B (wptr[1]), .Y (n_25));
  MXI2XL g502(.A (n_23), .B (wptr[4]), .S0 (wptr[3]), .Y (waddr[3]));
  NAND2XL g503(.A (wq2_rptr[3]), .B (wptr[3]), .Y (n_24));
  INVX1 g504(.A (wptr[4]), .Y (n_23));
  SDFFRHQX1 \wptr_reg[4] (.RN (wrst_n), .CK (wclk), .D (n_59), .SI
       (wq2_rptr[4]), .SE (DFT_sen), .Q (wptr[4]));
endmodule

module FIFO(rdata, wfull, rempty, wdata, winc, wclk, wrst_n, rinc,
     rclk, rrst_n, scan_en, test_mode, DFT_sdi_1, DFT_sdo_1, DFT_sdi_2,
     DFT_sdo_2);
  input [7:0] wdata;
  input winc, wclk, wrst_n, rinc, rclk, rrst_n, scan_en, test_mode,
       DFT_sdi_1, DFT_sdi_2;
  output [7:0] rdata;
  output wfull, rempty, DFT_sdo_1, DFT_sdo_2;
  wire [7:0] wdata;
  wire winc, wclk, wrst_n, rinc, rclk, rrst_n, scan_en, test_mode,
       DFT_sdi_1, DFT_sdi_2;
  wire [7:0] rdata;
  wire wfull, rempty, DFT_sdo_1, DFT_sdo_2;
  wire [3:0] waddr;
  wire [3:0] raddr;
  wire [7:0] rdata_raw;
  wire [4:0] rq2_wptr;
  wire [4:0] rptr;
  wire [4:0] wq2_rptr;
  wire [4:0] wptr;
  assign DFT_sdo_2 = rdata[7];
  FIFO_memory_DATA_SIZE8_ADDR_SIZE4 fifomem(.rdata (rdata_raw), .wdata
       (wdata), .waddr (waddr), .raddr (raddr), .wclk_en (winc), .wfull
       (wfull), .wclk (wclk));
  rptr_empty_ADDR_SIZE4 rptr_empty_inst(.rempty (rempty), .raddr
       (raddr), .rptr (rptr), .rq2_wptr (rq2_wptr), .rinc (rinc), .rclk
       (rclk), .rrst_n (rrst_n), .DFT_sdi (DFT_sdi_2), .DFT_sen
       (scan_en));
  two_ff_sync_SIZE5 sync_r2w(.q2 (wq2_rptr), .din (rptr), .clk (wclk),
       .rst_n (wrst_n), .DFT_sdi (DFT_sdi_1), .DFT_sen (scan_en));
  two_ff_sync_SIZE5_1 sync_w2r(.q2 (rq2_wptr), .din ({DFT_sdo_1,
       wptr[3:0]}), .clk (rclk), .rst_n (rrst_n), .DFT_sdi (rptr[4]),
       .DFT_sen (scan_en));
  wptr_full_ADDR_SIZE4 wptr_full_inst(.wfull (wfull), .waddr (waddr),
       .wptr ({DFT_sdo_1, wptr[3:0]}), .wq2_rptr (wq2_rptr), .winc
       (winc), .wclk (wclk), .wrst_n (wrst_n), .DFT_sen (scan_en));
  SDFFRHQX8 \rdata_reg[0] (.RN (rrst_n), .CK (rclk), .D (rdata_raw[0]),
       .SI (rq2_wptr[4]), .SE (scan_en), .Q (rdata[0]));
  SDFFRHQX8 \rdata_reg[4] (.RN (rrst_n), .CK (rclk), .D (rdata_raw[4]),
       .SI (rdata[3]), .SE (scan_en), .Q (rdata[4]));
  SDFFRHQX8 \rdata_reg[7] (.RN (rrst_n), .CK (rclk), .D (rdata_raw[7]),
       .SI (rdata[6]), .SE (scan_en), .Q (rdata[7]));
  SDFFRHQX8 \rdata_reg[3] (.RN (rrst_n), .CK (rclk), .D (rdata_raw[3]),
       .SI (rdata[2]), .SE (scan_en), .Q (rdata[3]));
  SDFFRHQX8 \rdata_reg[1] (.RN (rrst_n), .CK (rclk), .D (rdata_raw[1]),
       .SI (rdata[0]), .SE (scan_en), .Q (rdata[1]));
  SDFFRHQX8 \rdata_reg[2] (.RN (rrst_n), .CK (rclk), .D (rdata_raw[2]),
       .SI (rdata[1]), .SE (scan_en), .Q (rdata[2]));
  SDFFRHQX8 \rdata_reg[5] (.RN (rrst_n), .CK (rclk), .D (rdata_raw[5]),
       .SI (rdata[4]), .SE (scan_en), .Q (rdata[5]));
  SDFFRHQX8 \rdata_reg[6] (.RN (rrst_n), .CK (rclk), .D (rdata_raw[6]),
       .SI (rdata[5]), .SE (scan_en), .Q (rdata[6]));
endmodule

