
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Nov  5 2025 00:03:45 IST (Nov  4 2025 18:33:45 UTC)

// Verification Directory fv/FIFO 

module FIFO_memory_DATA_SIZE8_ADDR_SIZE4(rdata, wdata, waddr, raddr,
     wclk_en, wfull, wclk);
  input [7:0] wdata;
  input [3:0] waddr, raddr;
  input wclk_en, wfull, wclk;
  output [7:0] rdata;
  wire [7:0] wdata;
  wire [3:0] waddr, raddr;
  wire wclk_en, wfull, wclk;
  wire [7:0] rdata;
  wire [7:0] \mem[6] ;
  wire [7:0] \mem[14] ;
  wire [7:0] \mem[7] ;
  wire [7:0] \mem[15] ;
  wire [7:0] \mem[2] ;
  wire [7:0] \mem[10] ;
  wire [7:0] \mem[3] ;
  wire [7:0] \mem[11] ;
  wire [7:0] \mem[4] ;
  wire [7:0] \mem[12] ;
  wire [7:0] \mem[5] ;
  wire [7:0] \mem[13] ;
  wire [7:0] \mem[0] ;
  wire [7:0] \mem[8] ;
  wire [7:0] \mem[1] ;
  wire [7:0] \mem[9] ;
  wire n_0, n_1, n_2, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_44, n_45, n_46, n_47, n_48, n_49, n_50;
  wire n_51, n_52, n_53, n_54, n_55, n_56, n_57, n_58;
  wire n_59, n_60, n_61, n_62, n_63, n_64, n_65, n_66;
  wire n_67, n_68, n_69, n_70, n_71, n_72, n_73, n_74;
  wire n_75, n_76, n_77, n_78;
  OAI221X1 g5585(.A0 (n_61), .A1 (n_35), .B0 (n_63), .B1 (n_34), .C0
       (n_75), .Y (rdata[2]));
  OAI221X1 g5586(.A0 (n_60), .A1 (n_34), .B0 (n_67), .B1 (n_38), .C0
       (n_71), .Y (rdata[6]));
  OAI221X1 g5587(.A0 (n_46), .A1 (n_34), .B0 (n_44), .B1 (n_38), .C0
       (n_76), .Y (rdata[7]));
  OAI221X1 g5588(.A0 (n_50), .A1 (n_34), .B0 (n_39), .B1 (n_38), .C0
       (n_73), .Y (rdata[4]));
  OAI221X1 g5589(.A0 (n_66), .A1 (n_34), .B0 (n_48), .B1 (n_38), .C0
       (n_74), .Y (rdata[0]));
  OAI221X1 g5590(.A0 (n_65), .A1 (n_34), .B0 (n_55), .B1 (n_38), .C0
       (n_78), .Y (rdata[5]));
  OAI221X1 g5591(.A0 (n_53), .A1 (n_35), .B0 (n_70), .B1 (n_38), .C0
       (n_72), .Y (rdata[1]));
  OAI221X1 g5592(.A0 (n_69), .A1 (n_35), .B0 (n_54), .B1 (n_38), .C0
       (n_77), .Y (rdata[3]));
  AOI22X1 g5593(.A0 (n_58), .A1 (n_32), .B0 (n_62), .B1 (n_36), .Y
       (n_78));
  AOI22X1 g5594(.A0 (n_64), .A1 (n_32), .B0 (n_68), .B1 (n_33), .Y
       (n_77));
  AOI22X1 g5595(.A0 (n_47), .A1 (n_32), .B0 (n_57), .B1 (n_36), .Y
       (n_76));
  AOI22X1 g5596(.A0 (n_56), .A1 (n_32), .B0 (n_59), .B1 (n_37), .Y
       (n_75));
  AOI22X1 g5597(.A0 (n_40), .A1 (n_32), .B0 (n_43), .B1 (n_36), .Y
       (n_74));
  AOI22X1 g5598(.A0 (n_41), .A1 (n_32), .B0 (n_45), .B1 (n_36), .Y
       (n_73));
  AOI22X1 g5599(.A0 (n_49), .A1 (n_32), .B0 (n_52), .B1 (n_33), .Y
       (n_72));
  AOI22X1 g5600(.A0 (n_42), .A1 (n_32), .B0 (n_51), .B1 (n_36), .Y
       (n_71));
  MXI4XL g5601(.A (\mem[6] [1]), .B (\mem[14] [1]), .C (\mem[7] [1]),
       .D (\mem[15] [1]), .S0 (raddr[3]), .S1 (raddr[0]), .Y (n_70));
  MXI4XL g5602(.A (\mem[2] [3]), .B (\mem[10] [3]), .C (\mem[3] [3]),
       .D (\mem[11] [3]), .S0 (raddr[3]), .S1 (raddr[0]), .Y (n_69));
  MX4XL g5603(.A (\mem[4] [3]), .B (\mem[12] [3]), .C (\mem[5] [3]), .D
       (\mem[13] [3]), .S0 (raddr[3]), .S1 (raddr[0]), .Y (n_68));
  MXI4XL g5604(.A (\mem[6] [6]), .B (\mem[14] [6]), .C (\mem[7] [6]),
       .D (\mem[15] [6]), .S0 (raddr[3]), .S1 (raddr[0]), .Y (n_67));
  MXI4XL g5605(.A (\mem[4] [0]), .B (\mem[12] [0]), .C (\mem[5] [0]),
       .D (\mem[13] [0]), .S0 (raddr[3]), .S1 (raddr[0]), .Y (n_66));
  MXI4XL g5606(.A (\mem[4] [5]), .B (\mem[12] [5]), .C (\mem[5] [5]),
       .D (\mem[13] [5]), .S0 (raddr[3]), .S1 (raddr[0]), .Y (n_65));
  MX4XL g5607(.A (\mem[0] [3]), .B (\mem[8] [3]), .C (\mem[1] [3]), .D
       (\mem[9] [3]), .S0 (raddr[3]), .S1 (raddr[0]), .Y (n_64));
  MXI4XL g5608(.A (\mem[4] [2]), .B (\mem[12] [2]), .C (\mem[5] [2]),
       .D (\mem[13] [2]), .S0 (raddr[3]), .S1 (raddr[0]), .Y (n_63));
  MX4XL g5609(.A (\mem[2] [5]), .B (\mem[10] [5]), .C (\mem[3] [5]), .D
       (\mem[11] [5]), .S0 (raddr[3]), .S1 (raddr[0]), .Y (n_62));
  MXI4XL g5610(.A (\mem[2] [2]), .B (\mem[10] [2]), .C (\mem[3] [2]),
       .D (\mem[11] [2]), .S0 (raddr[3]), .S1 (raddr[0]), .Y (n_61));
  MXI4XL g5611(.A (\mem[4] [6]), .B (\mem[12] [6]), .C (\mem[5] [6]),
       .D (\mem[13] [6]), .S0 (raddr[3]), .S1 (raddr[0]), .Y (n_60));
  MX4XL g5612(.A (\mem[6] [2]), .B (\mem[14] [2]), .C (\mem[7] [2]), .D
       (\mem[15] [2]), .S0 (raddr[3]), .S1 (raddr[0]), .Y (n_59));
  MX4XL g5613(.A (\mem[0] [5]), .B (\mem[8] [5]), .C (\mem[1] [5]), .D
       (\mem[9] [5]), .S0 (raddr[3]), .S1 (raddr[0]), .Y (n_58));
  MX4XL g5614(.A (\mem[2] [7]), .B (\mem[10] [7]), .C (\mem[3] [7]), .D
       (\mem[11] [7]), .S0 (raddr[3]), .S1 (raddr[0]), .Y (n_57));
  MX4XL g5615(.A (\mem[0] [2]), .B (\mem[8] [2]), .C (\mem[1] [2]), .D
       (\mem[9] [2]), .S0 (raddr[3]), .S1 (raddr[0]), .Y (n_56));
  MXI4XL g5616(.A (\mem[6] [5]), .B (\mem[14] [5]), .C (\mem[7] [5]),
       .D (\mem[15] [5]), .S0 (raddr[3]), .S1 (raddr[0]), .Y (n_55));
  MXI4XL g5617(.A (\mem[6] [3]), .B (\mem[14] [3]), .C (\mem[7] [3]),
       .D (\mem[15] [3]), .S0 (raddr[3]), .S1 (raddr[0]), .Y (n_54));
  MXI4XL g5618(.A (\mem[2] [1]), .B (\mem[10] [1]), .C (\mem[3] [1]),
       .D (\mem[11] [1]), .S0 (raddr[3]), .S1 (raddr[0]), .Y (n_53));
  MX4XL g5619(.A (\mem[4] [1]), .B (\mem[12] [1]), .C (\mem[5] [1]), .D
       (\mem[13] [1]), .S0 (raddr[3]), .S1 (raddr[0]), .Y (n_52));
  MX4XL g5620(.A (\mem[2] [6]), .B (\mem[10] [6]), .C (\mem[3] [6]), .D
       (\mem[11] [6]), .S0 (raddr[3]), .S1 (raddr[0]), .Y (n_51));
  MXI4XL g5621(.A (\mem[4] [4]), .B (\mem[12] [4]), .C (\mem[5] [4]),
       .D (\mem[13] [4]), .S0 (raddr[3]), .S1 (raddr[0]), .Y (n_50));
  MX4XL g5622(.A (\mem[0] [1]), .B (\mem[8] [1]), .C (\mem[1] [1]), .D
       (\mem[9] [1]), .S0 (raddr[3]), .S1 (raddr[0]), .Y (n_49));
  MXI4XL g5623(.A (\mem[6] [0]), .B (\mem[14] [0]), .C (\mem[7] [0]),
       .D (\mem[15] [0]), .S0 (raddr[3]), .S1 (raddr[0]), .Y (n_48));
  MX4XL g5624(.A (\mem[0] [7]), .B (\mem[8] [7]), .C (\mem[1] [7]), .D
       (\mem[9] [7]), .S0 (raddr[3]), .S1 (raddr[0]), .Y (n_47));
  MXI4XL g5625(.A (\mem[4] [7]), .B (\mem[12] [7]), .C (\mem[5] [7]),
       .D (\mem[13] [7]), .S0 (raddr[3]), .S1 (raddr[0]), .Y (n_46));
  MX4XL g5626(.A (\mem[2] [4]), .B (\mem[10] [4]), .C (\mem[3] [4]), .D
       (\mem[11] [4]), .S0 (raddr[3]), .S1 (raddr[0]), .Y (n_45));
  MXI4XL g5627(.A (\mem[6] [7]), .B (\mem[14] [7]), .C (\mem[7] [7]),
       .D (\mem[15] [7]), .S0 (raddr[3]), .S1 (raddr[0]), .Y (n_44));
  MX4XL g5628(.A (\mem[2] [0]), .B (\mem[10] [0]), .C (\mem[3] [0]), .D
       (\mem[11] [0]), .S0 (raddr[3]), .S1 (raddr[0]), .Y (n_43));
  MX4XL g5629(.A (\mem[0] [6]), .B (\mem[8] [6]), .C (\mem[1] [6]), .D
       (\mem[9] [6]), .S0 (raddr[3]), .S1 (raddr[0]), .Y (n_42));
  MX4XL g5630(.A (\mem[0] [4]), .B (\mem[8] [4]), .C (\mem[1] [4]), .D
       (\mem[9] [4]), .S0 (raddr[3]), .S1 (raddr[0]), .Y (n_41));
  MX4XL g5631(.A (\mem[0] [0]), .B (\mem[8] [0]), .C (\mem[1] [0]), .D
       (\mem[9] [0]), .S0 (raddr[3]), .S1 (raddr[0]), .Y (n_40));
  MXI4XL g5632(.A (\mem[6] [4]), .B (\mem[14] [4]), .C (\mem[7] [4]),
       .D (\mem[15] [4]), .S0 (raddr[3]), .S1 (raddr[0]), .Y (n_39));
  INVX1 g5633(.A (n_38), .Y (n_37));
  CLKINVX1 g5634(.A (n_36), .Y (n_35));
  NAND2XL g5635(.A (raddr[2]), .B (raddr[1]), .Y (n_38));
  NOR2BX1 g5636(.AN (raddr[1]), .B (raddr[2]), .Y (n_36));
  INVX1 g5637(.A (n_34), .Y (n_33));
  NAND2BX1 g5638(.AN (raddr[1]), .B (raddr[2]), .Y (n_34));
  NOR2XL g5639(.A (raddr[2]), .B (raddr[1]), .Y (n_32));
  SDFFQXL \mem_reg[0][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[0] [0]),
       .SE (n_0), .Q (\mem[0] [0]));
  SDFFQXL \mem_reg[0][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[0] [1]),
       .SE (n_0), .Q (\mem[0] [1]));
  SDFFQXL \mem_reg[0][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[0] [2]),
       .SE (n_0), .Q (\mem[0] [2]));
  SDFFQXL \mem_reg[0][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[0] [3]),
       .SE (n_0), .Q (\mem[0] [3]));
  SDFFQXL \mem_reg[0][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[0] [4]),
       .SE (n_0), .Q (\mem[0] [4]));
  SDFFQXL \mem_reg[0][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[0] [5]),
       .SE (n_0), .Q (\mem[0] [5]));
  SDFFQXL \mem_reg[0][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[0] [6]),
       .SE (n_0), .Q (\mem[0] [6]));
  SDFFQXL \mem_reg[0][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[0] [7]),
       .SE (n_0), .Q (\mem[0] [7]));
  SDFFQXL \mem_reg[1][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[1] [0]),
       .SE (n_4), .Q (\mem[1] [0]));
  SDFFQXL \mem_reg[1][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[1] [1]),
       .SE (n_4), .Q (\mem[1] [1]));
  SDFFQXL \mem_reg[1][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[1] [2]),
       .SE (n_4), .Q (\mem[1] [2]));
  SDFFQXL \mem_reg[1][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[1] [3]),
       .SE (n_4), .Q (\mem[1] [3]));
  SDFFQXL \mem_reg[1][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[1] [4]),
       .SE (n_4), .Q (\mem[1] [4]));
  SDFFQXL \mem_reg[1][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[1] [5]),
       .SE (n_4), .Q (\mem[1] [5]));
  SDFFQXL \mem_reg[1][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[1] [6]),
       .SE (n_4), .Q (\mem[1] [6]));
  SDFFQXL \mem_reg[1][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[1] [7]),
       .SE (n_4), .Q (\mem[1] [7]));
  SDFFQXL \mem_reg[2][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[2] [0]),
       .SE (n_21), .Q (\mem[2] [0]));
  SDFFQXL \mem_reg[2][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[2] [1]),
       .SE (n_21), .Q (\mem[2] [1]));
  SDFFQXL \mem_reg[2][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[2] [2]),
       .SE (n_21), .Q (\mem[2] [2]));
  SDFFQXL \mem_reg[2][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[2] [3]),
       .SE (n_21), .Q (\mem[2] [3]));
  SDFFQXL \mem_reg[2][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[2] [4]),
       .SE (n_21), .Q (\mem[2] [4]));
  SDFFQXL \mem_reg[2][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[2] [5]),
       .SE (n_21), .Q (\mem[2] [5]));
  SDFFQXL \mem_reg[2][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[2] [6]),
       .SE (n_21), .Q (\mem[2] [6]));
  SDFFQXL \mem_reg[2][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[2] [7]),
       .SE (n_21), .Q (\mem[2] [7]));
  SDFFQXL \mem_reg[3][0] (.CK (wclk), .D (\mem[3] [0]), .SI (wdata[0]),
       .SE (n_30), .Q (\mem[3] [0]));
  SDFFQXL \mem_reg[3][1] (.CK (wclk), .D (\mem[3] [1]), .SI (wdata[1]),
       .SE (n_30), .Q (\mem[3] [1]));
  SDFFQXL \mem_reg[3][2] (.CK (wclk), .D (\mem[3] [2]), .SI (wdata[2]),
       .SE (n_30), .Q (\mem[3] [2]));
  SDFFQXL \mem_reg[3][3] (.CK (wclk), .D (\mem[3] [3]), .SI (wdata[3]),
       .SE (n_30), .Q (\mem[3] [3]));
  SDFFQXL \mem_reg[3][4] (.CK (wclk), .D (\mem[3] [4]), .SI (wdata[4]),
       .SE (n_30), .Q (\mem[3] [4]));
  SDFFQXL \mem_reg[3][5] (.CK (wclk), .D (\mem[3] [5]), .SI (wdata[5]),
       .SE (n_30), .Q (\mem[3] [5]));
  SDFFQXL \mem_reg[3][6] (.CK (wclk), .D (\mem[3] [6]), .SI (wdata[6]),
       .SE (n_30), .Q (\mem[3] [6]));
  SDFFQXL \mem_reg[3][7] (.CK (wclk), .D (\mem[3] [7]), .SI (wdata[7]),
       .SE (n_30), .Q (\mem[3] [7]));
  SDFFQXL \mem_reg[4][0] (.CK (wclk), .D (\mem[4] [0]), .SI (wdata[0]),
       .SE (n_20), .Q (\mem[4] [0]));
  SDFFQXL \mem_reg[4][1] (.CK (wclk), .D (\mem[4] [1]), .SI (wdata[1]),
       .SE (n_20), .Q (\mem[4] [1]));
  SDFFQXL \mem_reg[4][2] (.CK (wclk), .D (\mem[4] [2]), .SI (wdata[2]),
       .SE (n_20), .Q (\mem[4] [2]));
  SDFFQXL \mem_reg[4][3] (.CK (wclk), .D (\mem[4] [3]), .SI (wdata[3]),
       .SE (n_20), .Q (\mem[4] [3]));
  SDFFQXL \mem_reg[4][4] (.CK (wclk), .D (\mem[4] [4]), .SI (wdata[4]),
       .SE (n_20), .Q (\mem[4] [4]));
  SDFFQXL \mem_reg[4][5] (.CK (wclk), .D (\mem[4] [5]), .SI (wdata[5]),
       .SE (n_20), .Q (\mem[4] [5]));
  SDFFQXL \mem_reg[4][6] (.CK (wclk), .D (\mem[4] [6]), .SI (wdata[6]),
       .SE (n_20), .Q (\mem[4] [6]));
  SDFFQXL \mem_reg[4][7] (.CK (wclk), .D (\mem[4] [7]), .SI (wdata[7]),
       .SE (n_20), .Q (\mem[4] [7]));
  SDFFQXL \mem_reg[5][0] (.CK (wclk), .D (\mem[5] [0]), .SI (wdata[0]),
       .SE (n_1), .Q (\mem[5] [0]));
  SDFFQXL \mem_reg[5][1] (.CK (wclk), .D (\mem[5] [1]), .SI (wdata[1]),
       .SE (n_1), .Q (\mem[5] [1]));
  SDFFQXL \mem_reg[5][2] (.CK (wclk), .D (\mem[5] [2]), .SI (wdata[2]),
       .SE (n_1), .Q (\mem[5] [2]));
  SDFFQXL \mem_reg[5][3] (.CK (wclk), .D (\mem[5] [3]), .SI (wdata[3]),
       .SE (n_1), .Q (\mem[5] [3]));
  SDFFQXL \mem_reg[5][4] (.CK (wclk), .D (\mem[5] [4]), .SI (wdata[4]),
       .SE (n_1), .Q (\mem[5] [4]));
  SDFFQXL \mem_reg[5][5] (.CK (wclk), .D (\mem[5] [5]), .SI (wdata[5]),
       .SE (n_1), .Q (\mem[5] [5]));
  SDFFQXL \mem_reg[5][6] (.CK (wclk), .D (\mem[5] [6]), .SI (wdata[6]),
       .SE (n_1), .Q (\mem[5] [6]));
  SDFFQXL \mem_reg[5][7] (.CK (wclk), .D (\mem[5] [7]), .SI (wdata[7]),
       .SE (n_1), .Q (\mem[5] [7]));
  SDFFQXL \mem_reg[6][0] (.CK (wclk), .D (\mem[6] [0]), .SI (wdata[0]),
       .SE (n_22), .Q (\mem[6] [0]));
  SDFFQXL \mem_reg[6][1] (.CK (wclk), .D (\mem[6] [1]), .SI (wdata[1]),
       .SE (n_22), .Q (\mem[6] [1]));
  SDFFQXL \mem_reg[6][2] (.CK (wclk), .D (\mem[6] [2]), .SI (wdata[2]),
       .SE (n_22), .Q (\mem[6] [2]));
  SDFFQXL \mem_reg[6][3] (.CK (wclk), .D (\mem[6] [3]), .SI (wdata[3]),
       .SE (n_22), .Q (\mem[6] [3]));
  SDFFQXL \mem_reg[6][4] (.CK (wclk), .D (\mem[6] [4]), .SI (wdata[4]),
       .SE (n_22), .Q (\mem[6] [4]));
  SDFFQXL \mem_reg[6][5] (.CK (wclk), .D (\mem[6] [5]), .SI (wdata[5]),
       .SE (n_22), .Q (\mem[6] [5]));
  SDFFQXL \mem_reg[6][6] (.CK (wclk), .D (\mem[6] [6]), .SI (wdata[6]),
       .SE (n_22), .Q (\mem[6] [6]));
  SDFFQXL \mem_reg[6][7] (.CK (wclk), .D (\mem[6] [7]), .SI (wdata[7]),
       .SE (n_22), .Q (\mem[6] [7]));
  SDFFQXL \mem_reg[7][0] (.CK (wclk), .D (\mem[7] [0]), .SI (wdata[0]),
       .SE (n_24), .Q (\mem[7] [0]));
  SDFFQXL \mem_reg[7][1] (.CK (wclk), .D (\mem[7] [1]), .SI (wdata[1]),
       .SE (n_24), .Q (\mem[7] [1]));
  SDFFQXL \mem_reg[7][2] (.CK (wclk), .D (\mem[7] [2]), .SI (wdata[2]),
       .SE (n_24), .Q (\mem[7] [2]));
  SDFFQXL \mem_reg[7][3] (.CK (wclk), .D (\mem[7] [3]), .SI (wdata[3]),
       .SE (n_24), .Q (\mem[7] [3]));
  SDFFQXL \mem_reg[7][4] (.CK (wclk), .D (\mem[7] [4]), .SI (wdata[4]),
       .SE (n_24), .Q (\mem[7] [4]));
  SDFFQXL \mem_reg[7][5] (.CK (wclk), .D (\mem[7] [5]), .SI (wdata[5]),
       .SE (n_24), .Q (\mem[7] [5]));
  SDFFQXL \mem_reg[7][6] (.CK (wclk), .D (\mem[7] [6]), .SI (wdata[6]),
       .SE (n_24), .Q (\mem[7] [6]));
  SDFFQXL \mem_reg[7][7] (.CK (wclk), .D (\mem[7] [7]), .SI (wdata[7]),
       .SE (n_24), .Q (\mem[7] [7]));
  SDFFQXL \mem_reg[8][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[8] [0]),
       .SE (n_23), .Q (\mem[8] [0]));
  SDFFQXL \mem_reg[8][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[8] [1]),
       .SE (n_23), .Q (\mem[8] [1]));
  SDFFQXL \mem_reg[8][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[8] [2]),
       .SE (n_23), .Q (\mem[8] [2]));
  SDFFQXL \mem_reg[8][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[8] [3]),
       .SE (n_23), .Q (\mem[8] [3]));
  SDFFQXL \mem_reg[8][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[8] [4]),
       .SE (n_23), .Q (\mem[8] [4]));
  SDFFQXL \mem_reg[8][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[8] [5]),
       .SE (n_23), .Q (\mem[8] [5]));
  SDFFQXL \mem_reg[8][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[8] [6]),
       .SE (n_23), .Q (\mem[8] [6]));
  SDFFQXL \mem_reg[8][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[8] [7]),
       .SE (n_23), .Q (\mem[8] [7]));
  SDFFQXL \mem_reg[9][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[9] [0]),
       .SE (n_27), .Q (\mem[9] [0]));
  SDFFQXL \mem_reg[9][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[9] [1]),
       .SE (n_27), .Q (\mem[9] [1]));
  SDFFQXL \mem_reg[9][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[9] [2]),
       .SE (n_27), .Q (\mem[9] [2]));
  SDFFQXL \mem_reg[9][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[9] [3]),
       .SE (n_27), .Q (\mem[9] [3]));
  SDFFQXL \mem_reg[9][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[9] [4]),
       .SE (n_27), .Q (\mem[9] [4]));
  SDFFQXL \mem_reg[9][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[9] [5]),
       .SE (n_27), .Q (\mem[9] [5]));
  SDFFQXL \mem_reg[9][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[9] [6]),
       .SE (n_27), .Q (\mem[9] [6]));
  SDFFQXL \mem_reg[9][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[9] [7]),
       .SE (n_27), .Q (\mem[9] [7]));
  SDFFQXL \mem_reg[10][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[10]
       [0]), .SE (n_31), .Q (\mem[10] [0]));
  SDFFQXL \mem_reg[10][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[10]
       [1]), .SE (n_31), .Q (\mem[10] [1]));
  SDFFQXL \mem_reg[10][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[10]
       [2]), .SE (n_31), .Q (\mem[10] [2]));
  SDFFQXL \mem_reg[10][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[10]
       [3]), .SE (n_31), .Q (\mem[10] [3]));
  SDFFQXL \mem_reg[10][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[10]
       [4]), .SE (n_31), .Q (\mem[10] [4]));
  SDFFQXL \mem_reg[10][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[10]
       [5]), .SE (n_31), .Q (\mem[10] [5]));
  SDFFQXL \mem_reg[10][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[10]
       [6]), .SE (n_31), .Q (\mem[10] [6]));
  SDFFQXL \mem_reg[10][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[10]
       [7]), .SE (n_31), .Q (\mem[10] [7]));
  SDFFQXL \mem_reg[11][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[11]
       [0]), .SE (n_25), .Q (\mem[11] [0]));
  SDFFQXL \mem_reg[11][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[11]
       [1]), .SE (n_25), .Q (\mem[11] [1]));
  SDFFQXL \mem_reg[11][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[11]
       [2]), .SE (n_25), .Q (\mem[11] [2]));
  SDFFQXL \mem_reg[11][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[11]
       [3]), .SE (n_25), .Q (\mem[11] [3]));
  SDFFQXL \mem_reg[11][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[11]
       [4]), .SE (n_25), .Q (\mem[11] [4]));
  SDFFQXL \mem_reg[11][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[11]
       [5]), .SE (n_25), .Q (\mem[11] [5]));
  SDFFQXL \mem_reg[11][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[11]
       [6]), .SE (n_25), .Q (\mem[11] [6]));
  SDFFQXL \mem_reg[11][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[11]
       [7]), .SE (n_25), .Q (\mem[11] [7]));
  SDFFQXL \mem_reg[12][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[12]
       [0]), .SE (n_29), .Q (\mem[12] [0]));
  SDFFQXL \mem_reg[12][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[12]
       [1]), .SE (n_29), .Q (\mem[12] [1]));
  SDFFQXL \mem_reg[12][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[12]
       [2]), .SE (n_29), .Q (\mem[12] [2]));
  SDFFQXL \mem_reg[12][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[12]
       [3]), .SE (n_29), .Q (\mem[12] [3]));
  SDFFQXL \mem_reg[12][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[12]
       [4]), .SE (n_29), .Q (\mem[12] [4]));
  SDFFQXL \mem_reg[12][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[12]
       [5]), .SE (n_29), .Q (\mem[12] [5]));
  SDFFQXL \mem_reg[12][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[12]
       [6]), .SE (n_29), .Q (\mem[12] [6]));
  SDFFQXL \mem_reg[12][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[12]
       [7]), .SE (n_29), .Q (\mem[12] [7]));
  SDFFQX1 \mem_reg[13][0] (.CK (wclk), .D (wdata[0]), .SI (\mem[13]
       [0]), .SE (n_19), .Q (\mem[13] [0]));
  SDFFQX1 \mem_reg[13][1] (.CK (wclk), .D (wdata[1]), .SI (\mem[13]
       [1]), .SE (n_19), .Q (\mem[13] [1]));
  SDFFQX1 \mem_reg[13][2] (.CK (wclk), .D (wdata[2]), .SI (\mem[13]
       [2]), .SE (n_19), .Q (\mem[13] [2]));
  SDFFQX1 \mem_reg[13][3] (.CK (wclk), .D (wdata[3]), .SI (\mem[13]
       [3]), .SE (n_19), .Q (\mem[13] [3]));
  SDFFQX1 \mem_reg[13][4] (.CK (wclk), .D (wdata[4]), .SI (\mem[13]
       [4]), .SE (n_19), .Q (\mem[13] [4]));
  SDFFQX1 \mem_reg[13][5] (.CK (wclk), .D (wdata[5]), .SI (\mem[13]
       [5]), .SE (n_19), .Q (\mem[13] [5]));
  SDFFQX1 \mem_reg[13][6] (.CK (wclk), .D (wdata[6]), .SI (\mem[13]
       [6]), .SE (n_19), .Q (\mem[13] [6]));
  SDFFQX1 \mem_reg[13][7] (.CK (wclk), .D (wdata[7]), .SI (\mem[13]
       [7]), .SE (n_19), .Q (\mem[13] [7]));
  SDFFQXL \mem_reg[14][0] (.CK (wclk), .D (\mem[14] [0]), .SI
       (wdata[0]), .SE (n_28), .Q (\mem[14] [0]));
  SDFFQXL \mem_reg[14][1] (.CK (wclk), .D (\mem[14] [1]), .SI
       (wdata[1]), .SE (n_28), .Q (\mem[14] [1]));
  SDFFQXL \mem_reg[14][2] (.CK (wclk), .D (\mem[14] [2]), .SI
       (wdata[2]), .SE (n_28), .Q (\mem[14] [2]));
  SDFFQXL \mem_reg[14][3] (.CK (wclk), .D (\mem[14] [3]), .SI
       (wdata[3]), .SE (n_28), .Q (\mem[14] [3]));
  SDFFQXL \mem_reg[14][4] (.CK (wclk), .D (\mem[14] [4]), .SI
       (wdata[4]), .SE (n_28), .Q (\mem[14] [4]));
  SDFFQXL \mem_reg[14][5] (.CK (wclk), .D (\mem[14] [5]), .SI
       (wdata[5]), .SE (n_28), .Q (\mem[14] [5]));
  SDFFQXL \mem_reg[14][6] (.CK (wclk), .D (\mem[14] [6]), .SI
       (wdata[6]), .SE (n_28), .Q (\mem[14] [6]));
  SDFFQXL \mem_reg[14][7] (.CK (wclk), .D (\mem[14] [7]), .SI
       (wdata[7]), .SE (n_28), .Q (\mem[14] [7]));
  SDFFQXL \mem_reg[15][0] (.CK (wclk), .D (\mem[15] [0]), .SI
       (wdata[0]), .SE (n_6), .Q (\mem[15] [0]));
  SDFFQXL \mem_reg[15][1] (.CK (wclk), .D (\mem[15] [1]), .SI
       (wdata[1]), .SE (n_6), .Q (\mem[15] [1]));
  SDFFQXL \mem_reg[15][2] (.CK (wclk), .D (\mem[15] [2]), .SI
       (wdata[2]), .SE (n_6), .Q (\mem[15] [2]));
  SDFFQXL \mem_reg[15][3] (.CK (wclk), .D (\mem[15] [3]), .SI
       (wdata[3]), .SE (n_6), .Q (\mem[15] [3]));
  SDFFQXL \mem_reg[15][4] (.CK (wclk), .D (\mem[15] [4]), .SI
       (wdata[4]), .SE (n_6), .Q (\mem[15] [4]));
  SDFFQXL \mem_reg[15][5] (.CK (wclk), .D (\mem[15] [5]), .SI
       (wdata[5]), .SE (n_6), .Q (\mem[15] [5]));
  SDFFQXL \mem_reg[15][6] (.CK (wclk), .D (\mem[15] [6]), .SI
       (wdata[6]), .SE (n_6), .Q (\mem[15] [6]));
  SDFFQXL \mem_reg[15][7] (.CK (wclk), .D (\mem[15] [7]), .SI
       (wdata[7]), .SE (n_6), .Q (\mem[15] [7]));
  NAND2X2 g3045(.A (n_12), .B (n_16), .Y (n_31));
  NOR2X2 g3047(.A (n_11), .B (n_17), .Y (n_30));
  NAND2X1 g3048(.A (n_7), .B (n_16), .Y (n_29));
  AND2X1 g3050(.A (n_9), .B (n_16), .Y (n_28));
  NAND2X2 g3051(.A (n_13), .B (n_2), .Y (n_27));
  NAND2X1 g3052(.A (n_18), .B (n_13), .Y (n_0));
  NAND2X2 g3053(.A (n_12), .B (n_2), .Y (n_25));
  NOR2X2 g3054(.A (n_8), .B (n_17), .Y (n_24));
  NAND2X1 g3056(.A (n_13), .B (n_16), .Y (n_23));
  AND2X1 g3057(.A (n_9), .B (n_18), .Y (n_22));
  NAND2X2 g3058(.A (n_12), .B (n_18), .Y (n_21));
  AND2X1 g3059(.A (n_7), .B (n_18), .Y (n_20));
  NAND2X2 g3060(.A (n_7), .B (n_2), .Y (n_19));
  NOR2BX2 g3061(.AN (n_5), .B (waddr[0]), .Y (n_18));
  NAND2X2 g3062(.A (waddr[0]), .B (n_5), .Y (n_17));
  NOR2X2 g3063(.A (n_15), .B (waddr[0]), .Y (n_16));
  NAND2XL g3066(.A (n_10), .B (waddr[3]), .Y (n_15));
  NOR2BX1 g3067(.AN (n_10), .B (waddr[3]), .Y (n_5));
  INVX1 g3069(.A (n_12), .Y (n_11));
  NOR2X2 g3070(.A (waddr[2]), .B (waddr[1]), .Y (n_13));
  NOR2BX1 g3071(.AN (waddr[1]), .B (waddr[2]), .Y (n_12));
  INVX1 g3072(.A (n_8), .Y (n_9));
  NOR2BX1 g3074(.AN (wclk_en), .B (wfull), .Y (n_10));
  NAND2XL g3075(.A (waddr[2]), .B (waddr[1]), .Y (n_8));
  NOR2BX1 g3076(.AN (waddr[2]), .B (waddr[1]), .Y (n_7));
  CLKAND2X2 g3080(.A (n_9), .B (n_2), .Y (n_6));
  NAND2BX2 g2(.AN (n_17), .B (n_13), .Y (n_4));
  NOR2BX2 g3084(.AN (waddr[0]), .B (n_15), .Y (n_2));
  NOR2BX2 g3085(.AN (n_7), .B (n_17), .Y (n_1));
endmodule

module rptr_empty_ADDR_SIZE4(rempty, raddr, rptr, rq2_wptr, rinc, rclk,
     rrst_n);
  input [4:0] rq2_wptr;
  input rinc, rclk, rrst_n;
  output rempty;
  output [3:0] raddr;
  output [4:0] rptr;
  wire [4:0] rq2_wptr;
  wire rinc, rclk, rrst_n;
  wire rempty;
  wire [3:0] raddr;
  wire [4:0] rptr;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  CLKXOR2X1 g188(.A (rptr[0]), .B (raddr[1]), .Y (raddr[0]));
  CLKXOR2X1 g189(.A (rptr[1]), .B (raddr[2]), .Y (raddr[1]));
  NOR2XL g190(.A (n_22), .B (n_23), .Y (rempty));
  CLKXOR2X1 g191(.A (rptr[2]), .B (raddr[3]), .Y (raddr[2]));
  NAND4XL g192(.A (n_18), .B (n_21), .C (n_19), .D (n_20), .Y (n_23));
  AOI21X1 g193(.A0 (rq2_wptr[4]), .A1 (rptr[4]), .B0 (n_17), .Y (n_22));
  XNOR2XL g194(.A (rq2_wptr[2]), .B (rptr[2]), .Y (n_21));
  XNOR2XL g195(.A (rq2_wptr[3]), .B (rptr[3]), .Y (n_20));
  XNOR2XL g196(.A (rq2_wptr[0]), .B (rptr[0]), .Y (n_19));
  XNOR2XL g197(.A (rq2_wptr[1]), .B (rptr[1]), .Y (n_18));
  CLKXOR2X2 g198(.A (rptr[4]), .B (rptr[3]), .Y (raddr[3]));
  NOR2XL g199(.A (rq2_wptr[4]), .B (rptr[4]), .Y (n_17));
  SDFFRHQX1 \rptr_reg[3] (.RN (rrst_n), .CK (rclk), .D (n_13), .SI
       (n_14), .SE (n_16), .Q (rptr[3]));
  DFFRHQX1 \rptr_reg[4] (.RN (rrst_n), .CK (rclk), .D (n_16), .Q
       (rptr[4]));
  SDFFRHQX1 \rptr_reg[2] (.RN (rrst_n), .CK (rclk), .D (n_13), .SI
       (n_14), .SE (n_10), .Q (rptr[2]));
  OAI21X1 g136(.A0 (n_11), .A1 (rptr[4]), .B0 (n_15), .Y (n_16));
  NAND2XL g137(.A (n_11), .B (rptr[4]), .Y (n_15));
  INVX1 g138(.A (n_13), .Y (n_14));
  SDFFRHQX1 \rptr_reg[1] (.RN (rrst_n), .CK (rclk), .D (n_6), .SI
       (n_7), .SE (n_10), .Q (rptr[1]));
  OAI21X1 g140(.A0 (n_8), .A1 (raddr[3]), .B0 (n_12), .Y (n_13));
  NAND2XL g141(.A (n_8), .B (raddr[3]), .Y (n_12));
  NAND2BX1 g142(.AN (n_8), .B (raddr[3]), .Y (n_11));
  SDFFRHQX1 \rptr_reg[0] (.RN (rrst_n), .CK (rclk), .D (n_6), .SI
       (n_7), .SE (n_3), .Q (rptr[0]));
  OAI21X1 g144(.A0 (n_4), .A1 (raddr[2]), .B0 (n_9), .Y (n_10));
  NAND2XL g145(.A (n_4), .B (raddr[2]), .Y (n_9));
  NAND2BX1 g146(.AN (n_4), .B (raddr[2]), .Y (n_8));
  INVX1 g147(.A (n_6), .Y (n_7));
  OAI21X1 g148(.A0 (n_1), .A1 (raddr[1]), .B0 (n_5), .Y (n_6));
  NAND2XL g149(.A (n_1), .B (raddr[1]), .Y (n_5));
  NAND2BX1 g150(.AN (n_1), .B (raddr[1]), .Y (n_4));
  OAI21XL g151(.A0 (raddr[0]), .A1 (n_0), .B0 (n_2), .Y (n_3));
  NAND2XL g152(.A (n_0), .B (raddr[0]), .Y (n_2));
  NAND2BX1 g153(.AN (n_0), .B (raddr[0]), .Y (n_1));
  NAND2BX1 g154(.AN (rempty), .B (rinc), .Y (n_0));
endmodule

module two_ff_sync_SIZE5(q2, din, clk, rst_n);
  input [4:0] din;
  input clk, rst_n;
  output [4:0] q2;
  wire [4:0] din;
  wire clk, rst_n;
  wire [4:0] q2;
  wire [4:0] q1;
  DFFRHQX1 \q2_reg[4] (.RN (rst_n), .CK (clk), .D (q1[4]), .Q (q2[4]));
  DFFRHQX1 \q2_reg[3] (.RN (rst_n), .CK (clk), .D (q1[3]), .Q (q2[3]));
  DFFRHQX1 \q2_reg[1] (.RN (rst_n), .CK (clk), .D (q1[1]), .Q (q2[1]));
  DFFRHQX1 \q2_reg[0] (.RN (rst_n), .CK (clk), .D (q1[0]), .Q (q2[0]));
  DFFRHQX1 \q2_reg[2] (.RN (rst_n), .CK (clk), .D (q1[2]), .Q (q2[2]));
  DFFRHQX1 \q1_reg[2] (.RN (rst_n), .CK (clk), .D (din[2]), .Q (q1[2]));
  DFFRHQX1 \q1_reg[3] (.RN (rst_n), .CK (clk), .D (din[3]), .Q (q1[3]));
  DFFRHQX1 \q1_reg[4] (.RN (rst_n), .CK (clk), .D (din[4]), .Q (q1[4]));
  DFFRHQX1 \q1_reg[1] (.RN (rst_n), .CK (clk), .D (din[1]), .Q (q1[1]));
  DFFRHQX1 \q1_reg[0] (.RN (rst_n), .CK (clk), .D (din[0]), .Q (q1[0]));
endmodule

module two_ff_sync_SIZE5_1(q2, din, clk, rst_n);
  input [4:0] din;
  input clk, rst_n;
  output [4:0] q2;
  wire [4:0] din;
  wire clk, rst_n;
  wire [4:0] q2;
  wire [4:0] q1;
  DFFRHQX1 \q2_reg[4] (.RN (rst_n), .CK (clk), .D (q1[4]), .Q (q2[4]));
  DFFRHQX1 \q2_reg[3] (.RN (rst_n), .CK (clk), .D (q1[3]), .Q (q2[3]));
  DFFRHQX1 \q2_reg[1] (.RN (rst_n), .CK (clk), .D (q1[1]), .Q (q2[1]));
  DFFRHQX1 \q2_reg[0] (.RN (rst_n), .CK (clk), .D (q1[0]), .Q (q2[0]));
  DFFRHQX1 \q2_reg[2] (.RN (rst_n), .CK (clk), .D (q1[2]), .Q (q2[2]));
  DFFRHQX1 \q1_reg[2] (.RN (rst_n), .CK (clk), .D (din[2]), .Q (q1[2]));
  DFFRHQX1 \q1_reg[3] (.RN (rst_n), .CK (clk), .D (din[3]), .Q (q1[3]));
  DFFRHQX1 \q1_reg[4] (.RN (rst_n), .CK (clk), .D (din[4]), .Q (q1[4]));
  DFFRHQX1 \q1_reg[1] (.RN (rst_n), .CK (clk), .D (din[1]), .Q (q1[1]));
  DFFRHQX1 \q1_reg[0] (.RN (rst_n), .CK (clk), .D (din[0]), .Q (q1[0]));
endmodule

module wptr_full_ADDR_SIZE4(wfull, waddr, wptr, wq2_rptr, winc, wclk,
     wrst_n);
  input [4:0] wq2_rptr;
  input winc, wclk, wrst_n;
  output wfull;
  output [3:0] waddr;
  output [4:0] wptr;
  wire [4:0] wq2_rptr;
  wire winc, wclk, wrst_n;
  wire wfull;
  wire [3:0] waddr;
  wire [4:0] wptr;
  wire [4:0] wbin_current;
  wire n_0, n_1, n_3, n_4, n_5, n_8, n_9, n_10;
  wire n_12, n_13, n_16, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_25, n_27, n_28, n_29, n_30, n_31;
  wire n_45, n_46, n_47;
  BUFX2 g42(.A (wbin_current[0]), .Y (waddr[0]));
  XOR3X1 g192(.A (wptr[0]), .B (wptr[1]), .C (n_31), .Y
       (wbin_current[0]));
  NOR4X1 g196(.A (n_28), .B (n_22), .C (n_20), .D (n_29), .Y (wfull));
  BUFX2 g197(.A (n_31), .Y (waddr[2]));
  CLKINVX1 g198(.A (n_30), .Y (n_31));
  MXI2XL g199(.A (n_45), .B (n_27), .S0 (wptr[2]), .Y (n_30));
  OAI211X1 g200(.A0 (wq2_rptr[3]), .A1 (wptr[3]), .B0 (n_25), .C0
       (n_21), .Y (n_29));
  MXI2XL g201(.A (wptr[4]), .B (n_23), .S0 (wq2_rptr[4]), .Y (n_28));
  CLKINVX1 g203(.A (n_45), .Y (n_27));
  BUFX2 g204(.A (n_45), .Y (waddr[3]));
  NAND2XL g208(.A (wq2_rptr[3]), .B (wptr[3]), .Y (n_25));
  XOR2XL g2(.A (wptr[1]), .B (wq2_rptr[1]), .Y (n_22));
  XNOR2XL g214(.A (wptr[2]), .B (wq2_rptr[2]), .Y (n_21));
  XOR2XL g215(.A (wptr[0]), .B (wq2_rptr[0]), .Y (n_20));
  DFFRHQX2 \wptr_reg[3] (.RN (wrst_n), .CK (wclk), .D (n_19), .Q
       (wptr[3]));
  MXI2XL g138(.A (n_17), .B (n_18), .S0 (n_46), .Y (n_19));
  SDFFRHQX1 \wptr_reg[2] (.RN (wrst_n), .CK (wclk), .D (n_10), .SI
       (n_12), .SE (n_46), .Q (wptr[2]));
  INVX1 g141(.A (n_17), .Y (n_18));
  AOI21X1 g142(.A0 (wptr[4]), .A1 (n_13), .B0 (n_16), .Y (n_17));
  NOR2XL g143(.A (wptr[4]), .B (n_13), .Y (n_16));
  SDFFRHQX1 \wptr_reg[1] (.RN (wrst_n), .CK (wclk), .D (n_12), .SI
       (n_10), .SE (n_47), .Q (wptr[1]));
  NAND2XL g147(.A (n_8), .B (waddr[3]), .Y (n_13));
  INVX1 g148(.A (n_10), .Y (n_12));
  SDFFRHQX1 \wptr_reg[0] (.RN (wrst_n), .CK (wclk), .D (n_4), .SI
       (n_3), .SE (n_47), .Q (wptr[0]));
  OAI21X1 g151(.A0 (n_5), .A1 (waddr[2]), .B0 (n_9), .Y (n_10));
  NAND2XL g152(.A (n_5), .B (waddr[2]), .Y (n_9));
  NOR2BX1 g153(.AN (waddr[2]), .B (n_5), .Y (n_8));
  NAND2X1 g156(.A (waddr[1]), .B (n_1), .Y (n_5));
  INVXL g157(.A (n_3), .Y (n_4));
  ADDHX1 g159(.A (wbin_current[0]), .B (n_0), .CO (n_1), .S (n_3));
  NOR2BX1 g160(.AN (winc), .B (wfull), .Y (n_0));
  CLKMX2X2 g216(.A (n_31), .B (n_30), .S0 (wptr[1]), .Y (waddr[1]));
  MXI2X1 g217(.A (n_23), .B (wptr[4]), .S0 (wptr[3]), .Y (n_45));
  CLKXOR2X1 g218(.A (n_8), .B (waddr[3]), .Y (n_46));
  XNOR2X1 g219(.A (n_1), .B (waddr[1]), .Y (n_47));
  DFFRX1 \wptr_reg[4] (.RN (wrst_n), .CK (wclk), .D (n_18), .Q
       (wptr[4]), .QN (n_23));
endmodule

module FIFO(rdata, wfull, rempty, wdata, winc, wclk, wrst_n, rinc,
     rclk, rrst_n);
  input [7:0] wdata;
  input winc, wclk, wrst_n, rinc, rclk, rrst_n;
  output [7:0] rdata;
  output wfull, rempty;
  wire [7:0] wdata;
  wire winc, wclk, wrst_n, rinc, rclk, rrst_n;
  wire [7:0] rdata;
  wire wfull, rempty;
  wire [3:0] waddr;
  wire [3:0] raddr;
  wire [7:0] rdata_raw;
  wire [4:0] rq2_wptr;
  wire [4:0] rptr;
  wire [4:0] wq2_rptr;
  wire [4:0] wptr;
  FIFO_memory_DATA_SIZE8_ADDR_SIZE4 fifomem(.rdata (rdata_raw), .wdata
       (wdata), .waddr (waddr), .raddr (raddr), .wclk_en (winc), .wfull
       (wfull), .wclk (wclk));
  rptr_empty_ADDR_SIZE4 rptr_empty_inst(.rempty (rempty), .raddr
       (raddr), .rptr (rptr), .rq2_wptr (rq2_wptr), .rinc (rinc), .rclk
       (rclk), .rrst_n (rrst_n));
  two_ff_sync_SIZE5 sync_r2w(.q2 (wq2_rptr), .din (rptr), .clk (wclk),
       .rst_n (wrst_n));
  two_ff_sync_SIZE5_1 sync_w2r(.q2 (rq2_wptr), .din (wptr), .clk
       (rclk), .rst_n (rrst_n));
  wptr_full_ADDR_SIZE4 wptr_full_inst(.wfull (wfull), .waddr (waddr),
       .wptr (wptr), .wq2_rptr (wq2_rptr), .winc (winc), .wclk (wclk),
       .wrst_n (wrst_n));
  DFFRHQX1 \rdata_reg[7] (.RN (rrst_n), .CK (rclk), .D (rdata_raw[7]),
       .Q (rdata[7]));
  DFFRHQX1 \rdata_reg[6] (.RN (rrst_n), .CK (rclk), .D (rdata_raw[6]),
       .Q (rdata[6]));
  DFFRHQX1 \rdata_reg[4] (.RN (rrst_n), .CK (rclk), .D (rdata_raw[4]),
       .Q (rdata[4]));
  DFFRHQX1 \rdata_reg[0] (.RN (rrst_n), .CK (rclk), .D (rdata_raw[0]),
       .Q (rdata[0]));
  DFFRHQX1 \rdata_reg[3] (.RN (rrst_n), .CK (rclk), .D (rdata_raw[3]),
       .Q (rdata[3]));
  DFFRHQX1 \rdata_reg[5] (.RN (rrst_n), .CK (rclk), .D (rdata_raw[5]),
       .Q (rdata[5]));
  DFFRHQX1 \rdata_reg[2] (.RN (rrst_n), .CK (rclk), .D (rdata_raw[2]),
       .Q (rdata[2]));
  DFFRHQX1 \rdata_reg[1] (.RN (rrst_n), .CK (rclk), .D (rdata_raw[1]),
       .Q (rdata[1]));
endmodule

