/*
###############################################################
#  Generated by:      Cadence Innovus 20.10-p004_1
#  OS:                Linux x86_64(Host ID edatools-server2.iiitd.edu.in)
#  Generated on:      Mon Nov 10 21:47:21 2025
#  Design:            FIFO
#  Command:           saveNetlist ./netlists/FIFO_post_route.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Nov  5 2025 00:03:45 IST (Nov  4 2025 18:33:45 UTC)
// Verification Directory fv/FIFO 
module FIFO_memory_DATA_SIZE8_ADDR_SIZE4 (
	rdata, 
	wdata, 
	waddr, 
	raddr, 
	wclk_en, 
	wfull, 
	wclk_clone1, 
	wclk, 
	FE_OCPN1_waddr_2);
   output [7:0] rdata;
   input [7:0] wdata;
   input [3:0] waddr;
   input [3:0] raddr;
   input wclk_en;
   input wfull;
   input wclk_clone1;
   input wclk;
   input FE_OCPN1_waddr_2;

   // Internal wires
   wire FE_PHN92_wdata_3;
   wire FE_PHN91_wdata_2;
   wire FE_PHN90_wdata_6;
   wire FE_PHN89_wdata_1;
   wire FE_PHN88_wdata_4;
   wire FE_PHN87_wdata_1;
   wire FE_PHN86_wdata_4;
   wire FE_PHN85_wdata_5;
   wire FE_PHN84_wdata_0;
   wire FE_PHN83_wdata_7;
   wire FE_PHN82_wdata_3;
   wire FE_OCPN77_n_29;
   wire FE_OCPN76_n_27;
   wire FE_OCPN75_waddr_0;
   wire FE_RN_1;
   wire FE_RN_54_0;
   wire FE_OCPN74_n_7;
   wire FE_OCPN47_n_25;
   wire FE_OCPN73_n_4;
   wire FE_OCPN45_n_27;
   wire FE_OCPN44_n_31;
   wire FE_OCPN43_n_4;
   wire FE_OCPN42_n_23;
   wire CTS_1;
   wire FE_OCPN38_n_8;
   wire FE_RN_43_0;
   wire FE_RN_32_0;
   wire FE_RN_20_0;
   wire FE_OCPN35_n_17;
   wire FE_OCPN34_n_24;
   wire FE_OCPN27_n_21;
   wire FE_OCPN25_n_0;
   wire FE_OCPN17_waddr_0;
   wire FE_OFN13_n_19;
   wire FE_OFN12_n_1;
   wire FE_OFN11_raddr_0;
   wire [7:0] \mem[6] ;
   wire [7:0] \mem[14] ;
   wire [7:0] \mem[7] ;
   wire [7:0] \mem[15] ;
   wire [7:0] \mem[2] ;
   wire [7:0] \mem[10] ;
   wire [7:0] \mem[3] ;
   wire [7:0] \mem[11] ;
   wire [7:0] \mem[4] ;
   wire [7:0] \mem[12] ;
   wire [7:0] \mem[5] ;
   wire [7:0] \mem[13] ;
   wire [7:0] \mem[0] ;
   wire [7:0] \mem[8] ;
   wire [7:0] \mem[1] ;
   wire [7:0] \mem[9] ;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;

   CLKBUFX2 FE_PHC92_wdata_3 (.A(wdata[3]),
	.Y(FE_PHN92_wdata_3));
   CLKBUFX2 FE_PHC91_wdata_2 (.A(wdata[2]),
	.Y(FE_PHN91_wdata_2));
   CLKBUFX2 FE_PHC90_wdata_6 (.A(wdata[6]),
	.Y(FE_PHN90_wdata_6));
   CLKBUFX2 FE_PHC89_wdata_1 (.A(wdata[1]),
	.Y(FE_PHN89_wdata_1));
   CLKBUFX2 FE_PHC88_wdata_4 (.A(wdata[4]),
	.Y(FE_PHN88_wdata_4));
   CLKBUFX2 FE_PHC87_wdata_1 (.A(wdata[1]),
	.Y(FE_PHN87_wdata_1));
   CLKBUFX2 FE_PHC86_wdata_4 (.A(wdata[4]),
	.Y(FE_PHN86_wdata_4));
   CLKBUFX2 FE_PHC85_wdata_5 (.A(wdata[5]),
	.Y(FE_PHN85_wdata_5));
   CLKBUFX2 FE_PHC84_wdata_0 (.A(wdata[0]),
	.Y(FE_PHN84_wdata_0));
   CLKBUFX2 FE_PHC83_wdata_7 (.A(wdata[7]),
	.Y(FE_PHN83_wdata_7));
   CLKBUFX2 FE_PHC82_wdata_3 (.A(FE_PHN92_wdata_3),
	.Y(FE_PHN82_wdata_3));
   CLKINVX3 FE_OCPC70_n_8 (.A(n_8),
	.Y(FE_OCPN38_n_8));
   BUFX20 FE_OCPC77_n_29 (.A(n_29),
	.Y(FE_OCPN77_n_29));
   CLKBUFX2 FE_OCPC76_n_27 (.A(n_27),
	.Y(FE_OCPN76_n_27));
   BUFX3 FE_OCPC75_waddr_0 (.A(waddr[0]),
	.Y(FE_OCPN75_waddr_0));
   NOR2BX4 FE_RC_80_0_dup (.AN(n_5),
	.B(FE_OCPN17_waddr_0),
	.Y(FE_RN_1));
   NOR2BX4 FE_RC_101_0 (.AN(FE_RN_43_0),
	.B(FE_OCPN17_waddr_0),
	.Y(n_16));
   NOR2BX2 FE_RC_100_0 (.AN(FE_RN_43_0),
	.B(FE_OCPN17_waddr_0),
	.Y(FE_RN_54_0));
   NAND2X2 FE_RC_99_0 (.A(n_13),
	.B(FE_RN_54_0),
	.Y(n_23));
   CLKBUFX6 FE_RC_98_0 (.A(waddr[0]),
	.Y(FE_OCPN17_waddr_0));
   NAND2X2 FE_RC_97_0 (.A(n_5),
	.B(FE_OCPN75_waddr_0),
	.Y(n_17));
   BUFX2 FE_OCPC74_n_7 (.A(n_7),
	.Y(FE_OCPN74_n_7));
   BUFX12 FE_OCPC68_n_25 (.A(n_25),
	.Y(FE_OCPN47_n_25));
   CLKBUFX2 FE_OCPC73_n_4 (.A(n_4),
	.Y(FE_OCPN73_n_4));
   BUFX12 FE_OCPC66_n_27 (.A(n_27),
	.Y(FE_OCPN45_n_27));
   BUFX12 FE_OCPC65_n_31 (.A(n_31),
	.Y(FE_OCPN44_n_31));
   BUFX12 FE_OCPC64_n_4 (.A(n_4),
	.Y(FE_OCPN43_n_4));
   BUFX12 FE_OCPC63_n_23 (.A(n_23),
	.Y(FE_OCPN42_n_23));
   CLKBUFX12 CTS_ccl_a_buf_00006 (.A(wclk),
	.Y(CTS_1));
   NOR2BX2 FE_RC_80_0 (.AN(n_5),
	.B(FE_OCPN17_waddr_0),
	.Y(n_18));
   AND2XL FE_RC_74_0 (.A(waddr[3]),
	.B(n_10),
	.Y(FE_RN_43_0));
   INVXL FE_RC_54_0 (.A(waddr[2]),
	.Y(FE_RN_32_0));
   CLKAND2X6 FE_RC_53_0 (.A(waddr[1]),
	.B(FE_RN_32_0),
	.Y(n_12));
   BUFX8 FE_OCPC55_n_24 (.A(n_24),
	.Y(FE_OCPN34_n_24));
   BUFX6 FE_OCPC53_n_17 (.A(n_17),
	.Y(FE_OCPN35_n_17));
   CLKINVX1 FE_RC_36_0 (.A(n_15),
	.Y(FE_RN_20_0));
   CLKAND2X3 FE_RC_35_0 (.A(FE_RN_20_0),
	.B(FE_OCPN17_waddr_0),
	.Y(n_2));
   CLKINVX2 FE_OCPC50_n_12 (.A(n_12),
	.Y(n_11));
   BUFX20 FE_OCPC31_n_21 (.A(n_21),
	.Y(FE_OCPN27_n_21));
   BUFX12 FE_OCPC29_n_0 (.A(n_0),
	.Y(FE_OCPN25_n_0));
   BUFX12 FE_OFC13_n_19 (.A(n_19),
	.Y(FE_OFN13_n_19));
   BUFX8 FE_OFC12_n_1 (.A(n_1),
	.Y(FE_OFN12_n_1));
   BUFX2 FE_OFC11_raddr_0 (.A(raddr[0]),
	.Y(FE_OFN11_raddr_0));
   OAI221X1 g5585 (.A0(n_61),
	.A1(n_35),
	.B0(n_63),
	.B1(n_34),
	.C0(n_75),
	.Y(rdata[2]));
   OAI221X1 g5586 (.A0(n_60),
	.A1(n_34),
	.B0(n_67),
	.B1(n_38),
	.C0(n_71),
	.Y(rdata[6]));
   OAI221X1 g5587 (.A0(n_46),
	.A1(n_34),
	.B0(n_44),
	.B1(n_38),
	.C0(n_76),
	.Y(rdata[7]));
   OAI221X1 g5588 (.A0(n_50),
	.A1(n_34),
	.B0(n_39),
	.B1(n_38),
	.C0(n_73),
	.Y(rdata[4]));
   OAI221X1 g5589 (.A0(n_66),
	.A1(n_34),
	.B0(n_48),
	.B1(n_38),
	.C0(n_74),
	.Y(rdata[0]));
   OAI221X1 g5590 (.A0(n_65),
	.A1(n_34),
	.B0(n_55),
	.B1(n_38),
	.C0(n_78),
	.Y(rdata[5]));
   OAI221X1 g5591 (.A0(n_53),
	.A1(n_35),
	.B0(n_70),
	.B1(n_38),
	.C0(n_72),
	.Y(rdata[1]));
   OAI221X1 g5592 (.A0(n_69),
	.A1(n_35),
	.B0(n_54),
	.B1(n_38),
	.C0(n_77),
	.Y(rdata[3]));
   AOI22X1 g5593 (.A0(n_58),
	.A1(n_32),
	.B0(n_62),
	.B1(n_36),
	.Y(n_78));
   AOI22X1 g5594 (.A0(n_64),
	.A1(n_32),
	.B0(n_68),
	.B1(n_33),
	.Y(n_77));
   AOI22X1 g5595 (.A0(n_47),
	.A1(n_32),
	.B0(n_57),
	.B1(n_36),
	.Y(n_76));
   AOI22X1 g5596 (.A0(n_56),
	.A1(n_32),
	.B0(n_59),
	.B1(n_37),
	.Y(n_75));
   AOI22X1 g5597 (.A0(n_40),
	.A1(n_32),
	.B0(n_43),
	.B1(n_36),
	.Y(n_74));
   AOI22X1 g5598 (.A0(n_41),
	.A1(n_32),
	.B0(n_45),
	.B1(n_36),
	.Y(n_73));
   AOI22X1 g5599 (.A0(n_49),
	.A1(n_32),
	.B0(n_52),
	.B1(n_33),
	.Y(n_72));
   AOI22X1 g5600 (.A0(n_42),
	.A1(n_32),
	.B0(n_51),
	.B1(n_36),
	.Y(n_71));
   MXI4XL g5601 (.A(\mem[6] [1]),
	.B(\mem[14] [1]),
	.C(\mem[7] [1]),
	.D(\mem[15] [1]),
	.S0(raddr[3]),
	.S1(FE_OFN11_raddr_0),
	.Y(n_70));
   MXI4XL g5602 (.A(\mem[2] [3]),
	.B(\mem[10] [3]),
	.C(\mem[3] [3]),
	.D(\mem[11] [3]),
	.S0(raddr[3]),
	.S1(FE_OFN11_raddr_0),
	.Y(n_69));
   MX4XL g5603 (.A(\mem[4] [3]),
	.B(\mem[12] [3]),
	.C(\mem[5] [3]),
	.D(\mem[13] [3]),
	.S0(raddr[3]),
	.S1(FE_OFN11_raddr_0),
	.Y(n_68));
   MXI4XL g5604 (.A(\mem[6] [6]),
	.B(\mem[14] [6]),
	.C(\mem[7] [6]),
	.D(\mem[15] [6]),
	.S0(raddr[3]),
	.S1(FE_OFN11_raddr_0),
	.Y(n_67));
   MXI4XL g5605 (.A(\mem[4] [0]),
	.B(\mem[12] [0]),
	.C(\mem[5] [0]),
	.D(\mem[13] [0]),
	.S0(raddr[3]),
	.S1(FE_OFN11_raddr_0),
	.Y(n_66));
   MXI4XL g5606 (.A(\mem[4] [5]),
	.B(\mem[12] [5]),
	.C(\mem[5] [5]),
	.D(\mem[13] [5]),
	.S0(raddr[3]),
	.S1(FE_OFN11_raddr_0),
	.Y(n_65));
   MX4XL g5607 (.A(\mem[0] [3]),
	.B(\mem[8] [3]),
	.C(\mem[1] [3]),
	.D(\mem[9] [3]),
	.S0(raddr[3]),
	.S1(FE_OFN11_raddr_0),
	.Y(n_64));
   MXI4XL g5608 (.A(\mem[4] [2]),
	.B(\mem[12] [2]),
	.C(\mem[5] [2]),
	.D(\mem[13] [2]),
	.S0(raddr[3]),
	.S1(FE_OFN11_raddr_0),
	.Y(n_63));
   MX4XL g5609 (.A(\mem[2] [5]),
	.B(\mem[10] [5]),
	.C(\mem[3] [5]),
	.D(\mem[11] [5]),
	.S0(raddr[3]),
	.S1(FE_OFN11_raddr_0),
	.Y(n_62));
   MXI4XL g5610 (.A(\mem[2] [2]),
	.B(\mem[10] [2]),
	.C(\mem[3] [2]),
	.D(\mem[11] [2]),
	.S0(raddr[3]),
	.S1(FE_OFN11_raddr_0),
	.Y(n_61));
   MXI4XL g5611 (.A(\mem[4] [6]),
	.B(\mem[12] [6]),
	.C(\mem[5] [6]),
	.D(\mem[13] [6]),
	.S0(raddr[3]),
	.S1(FE_OFN11_raddr_0),
	.Y(n_60));
   MX4XL g5612 (.A(\mem[6] [2]),
	.B(\mem[14] [2]),
	.C(\mem[7] [2]),
	.D(\mem[15] [2]),
	.S0(raddr[3]),
	.S1(FE_OFN11_raddr_0),
	.Y(n_59));
   MX4XL g5613 (.A(\mem[0] [5]),
	.B(\mem[8] [5]),
	.C(\mem[1] [5]),
	.D(\mem[9] [5]),
	.S0(raddr[3]),
	.S1(FE_OFN11_raddr_0),
	.Y(n_58));
   MX4XL g5614 (.A(\mem[2] [7]),
	.B(\mem[10] [7]),
	.C(\mem[3] [7]),
	.D(\mem[11] [7]),
	.S0(raddr[3]),
	.S1(FE_OFN11_raddr_0),
	.Y(n_57));
   MX4XL g5615 (.A(\mem[0] [2]),
	.B(\mem[8] [2]),
	.C(\mem[1] [2]),
	.D(\mem[9] [2]),
	.S0(raddr[3]),
	.S1(FE_OFN11_raddr_0),
	.Y(n_56));
   MXI4XL g5616 (.A(\mem[6] [5]),
	.B(\mem[14] [5]),
	.C(\mem[7] [5]),
	.D(\mem[15] [5]),
	.S0(raddr[3]),
	.S1(FE_OFN11_raddr_0),
	.Y(n_55));
   MXI4XL g5617 (.A(\mem[6] [3]),
	.B(\mem[14] [3]),
	.C(\mem[7] [3]),
	.D(\mem[15] [3]),
	.S0(raddr[3]),
	.S1(FE_OFN11_raddr_0),
	.Y(n_54));
   MXI4XL g5618 (.A(\mem[2] [1]),
	.B(\mem[10] [1]),
	.C(\mem[3] [1]),
	.D(\mem[11] [1]),
	.S0(raddr[3]),
	.S1(FE_OFN11_raddr_0),
	.Y(n_53));
   MX4XL g5619 (.A(\mem[4] [1]),
	.B(\mem[12] [1]),
	.C(\mem[5] [1]),
	.D(\mem[13] [1]),
	.S0(raddr[3]),
	.S1(FE_OFN11_raddr_0),
	.Y(n_52));
   MX4XL g5620 (.A(\mem[2] [6]),
	.B(\mem[10] [6]),
	.C(\mem[3] [6]),
	.D(\mem[11] [6]),
	.S0(raddr[3]),
	.S1(FE_OFN11_raddr_0),
	.Y(n_51));
   MXI4XL g5621 (.A(\mem[4] [4]),
	.B(\mem[12] [4]),
	.C(\mem[5] [4]),
	.D(\mem[13] [4]),
	.S0(raddr[3]),
	.S1(FE_OFN11_raddr_0),
	.Y(n_50));
   MX4XL g5622 (.A(\mem[0] [1]),
	.B(\mem[8] [1]),
	.C(\mem[1] [1]),
	.D(\mem[9] [1]),
	.S0(raddr[3]),
	.S1(FE_OFN11_raddr_0),
	.Y(n_49));
   MXI4XL g5623 (.A(\mem[6] [0]),
	.B(\mem[14] [0]),
	.C(\mem[7] [0]),
	.D(\mem[15] [0]),
	.S0(raddr[3]),
	.S1(raddr[0]),
	.Y(n_48));
   MX4XL g5624 (.A(\mem[0] [7]),
	.B(\mem[8] [7]),
	.C(\mem[1] [7]),
	.D(\mem[9] [7]),
	.S0(raddr[3]),
	.S1(FE_OFN11_raddr_0),
	.Y(n_47));
   MXI4XL g5625 (.A(\mem[4] [7]),
	.B(\mem[12] [7]),
	.C(\mem[5] [7]),
	.D(\mem[13] [7]),
	.S0(raddr[3]),
	.S1(FE_OFN11_raddr_0),
	.Y(n_46));
   MX4XL g5626 (.A(\mem[2] [4]),
	.B(\mem[10] [4]),
	.C(\mem[3] [4]),
	.D(\mem[11] [4]),
	.S0(raddr[3]),
	.S1(FE_OFN11_raddr_0),
	.Y(n_45));
   MXI4XL g5627 (.A(\mem[6] [7]),
	.B(\mem[14] [7]),
	.C(\mem[7] [7]),
	.D(\mem[15] [7]),
	.S0(raddr[3]),
	.S1(FE_OFN11_raddr_0),
	.Y(n_44));
   MX4XL g5628 (.A(\mem[2] [0]),
	.B(\mem[10] [0]),
	.C(\mem[3] [0]),
	.D(\mem[11] [0]),
	.S0(raddr[3]),
	.S1(FE_OFN11_raddr_0),
	.Y(n_43));
   MX4XL g5629 (.A(\mem[0] [6]),
	.B(\mem[8] [6]),
	.C(\mem[1] [6]),
	.D(\mem[9] [6]),
	.S0(raddr[3]),
	.S1(FE_OFN11_raddr_0),
	.Y(n_42));
   MX4XL g5630 (.A(\mem[0] [4]),
	.B(\mem[8] [4]),
	.C(\mem[1] [4]),
	.D(\mem[9] [4]),
	.S0(raddr[3]),
	.S1(FE_OFN11_raddr_0),
	.Y(n_41));
   MX4XL g5631 (.A(\mem[0] [0]),
	.B(\mem[8] [0]),
	.C(\mem[1] [0]),
	.D(\mem[9] [0]),
	.S0(raddr[3]),
	.S1(FE_OFN11_raddr_0),
	.Y(n_40));
   MXI4XL g5632 (.A(\mem[6] [4]),
	.B(\mem[14] [4]),
	.C(\mem[7] [4]),
	.D(\mem[15] [4]),
	.S0(raddr[3]),
	.S1(raddr[0]),
	.Y(n_39));
   INVX1 g5633 (.A(n_38),
	.Y(n_37));
   CLKINVX1 g5634 (.A(n_36),
	.Y(n_35));
   NAND2XL g5635 (.A(raddr[2]),
	.B(raddr[1]),
	.Y(n_38));
   NOR2BX1 g5636 (.AN(raddr[1]),
	.B(raddr[2]),
	.Y(n_36));
   INVX1 g5637 (.A(n_34),
	.Y(n_33));
   NAND2BX1 g5638 (.AN(raddr[1]),
	.B(raddr[2]),
	.Y(n_34));
   NOR2X1 g5639 (.A(raddr[2]),
	.B(raddr[1]),
	.Y(n_32));
   SDFFQXL \mem_reg[0][0]  (.CK(wclk_clone1),
	.D(wdata[0]),
	.Q(\mem[0] [0]),
	.SE(FE_OCPN25_n_0),
	.SI(\mem[0] [0]));
   SDFFQXL \mem_reg[0][1]  (.CK(CTS_1),
	.D(wdata[1]),
	.Q(\mem[0] [1]),
	.SE(FE_OCPN25_n_0),
	.SI(\mem[0] [1]));
   SDFFQXL \mem_reg[0][2]  (.CK(CTS_1),
	.D(wdata[2]),
	.Q(\mem[0] [2]),
	.SE(FE_OCPN25_n_0),
	.SI(\mem[0] [2]));
   SDFFQXL \mem_reg[0][3]  (.CK(CTS_1),
	.D(wdata[3]),
	.Q(\mem[0] [3]),
	.SE(FE_OCPN25_n_0),
	.SI(\mem[0] [3]));
   SDFFQXL \mem_reg[0][4]  (.CK(wclk_clone1),
	.D(wdata[4]),
	.Q(\mem[0] [4]),
	.SE(FE_OCPN25_n_0),
	.SI(\mem[0] [4]));
   SDFFQXL \mem_reg[0][5]  (.CK(wclk_clone1),
	.D(wdata[5]),
	.Q(\mem[0] [5]),
	.SE(FE_OCPN25_n_0),
	.SI(\mem[0] [5]));
   SDFFQXL \mem_reg[0][6]  (.CK(wclk_clone1),
	.D(wdata[6]),
	.Q(\mem[0] [6]),
	.SE(FE_OCPN25_n_0),
	.SI(\mem[0] [6]));
   SDFFQXL \mem_reg[0][7]  (.CK(wclk_clone1),
	.D(wdata[7]),
	.Q(\mem[0] [7]),
	.SE(FE_OCPN25_n_0),
	.SI(\mem[0] [7]));
   SDFFQXL \mem_reg[1][0]  (.CK(wclk_clone1),
	.D(wdata[0]),
	.Q(\mem[1] [0]),
	.SE(FE_OCPN43_n_4),
	.SI(\mem[1] [0]));
   SDFFQXL \mem_reg[1][1]  (.CK(wclk_clone1),
	.D(wdata[1]),
	.Q(\mem[1] [1]),
	.SE(FE_OCPN43_n_4),
	.SI(\mem[1] [1]));
   SDFFQXL \mem_reg[1][2]  (.CK(CTS_1),
	.D(wdata[2]),
	.Q(\mem[1] [2]),
	.SE(FE_OCPN43_n_4),
	.SI(\mem[1] [2]));
   SDFFQXL \mem_reg[1][3]  (.CK(CTS_1),
	.D(wdata[3]),
	.Q(\mem[1] [3]),
	.SE(FE_OCPN43_n_4),
	.SI(\mem[1] [3]));
   SDFFQXL \mem_reg[1][4]  (.CK(wclk_clone1),
	.D(wdata[4]),
	.Q(\mem[1] [4]),
	.SE(FE_OCPN73_n_4),
	.SI(\mem[1] [4]));
   SDFFQXL \mem_reg[1][5]  (.CK(wclk_clone1),
	.D(wdata[5]),
	.Q(\mem[1] [5]),
	.SE(FE_OCPN43_n_4),
	.SI(\mem[1] [5]));
   SDFFQXL \mem_reg[1][6]  (.CK(wclk_clone1),
	.D(wdata[6]),
	.Q(\mem[1] [6]),
	.SE(FE_OCPN43_n_4),
	.SI(\mem[1] [6]));
   SDFFQXL \mem_reg[1][7]  (.CK(CTS_1),
	.D(wdata[7]),
	.Q(\mem[1] [7]),
	.SE(FE_OCPN43_n_4),
	.SI(\mem[1] [7]));
   SDFFQXL \mem_reg[2][0]  (.CK(wclk_clone1),
	.D(wdata[0]),
	.Q(\mem[2] [0]),
	.SE(FE_OCPN27_n_21),
	.SI(\mem[2] [0]));
   SDFFQXL \mem_reg[2][1]  (.CK(CTS_1),
	.D(wdata[1]),
	.Q(\mem[2] [1]),
	.SE(FE_OCPN27_n_21),
	.SI(\mem[2] [1]));
   SDFFQXL \mem_reg[2][2]  (.CK(CTS_1),
	.D(FE_PHN91_wdata_2),
	.Q(\mem[2] [2]),
	.SE(FE_OCPN27_n_21),
	.SI(\mem[2] [2]));
   SDFFQXL \mem_reg[2][3]  (.CK(CTS_1),
	.D(FE_PHN92_wdata_3),
	.Q(\mem[2] [3]),
	.SE(FE_OCPN27_n_21),
	.SI(\mem[2] [3]));
   SDFFQXL \mem_reg[2][4]  (.CK(wclk_clone1),
	.D(wdata[4]),
	.Q(\mem[2] [4]),
	.SE(FE_OCPN27_n_21),
	.SI(\mem[2] [4]));
   SDFFQXL \mem_reg[2][5]  (.CK(wclk_clone1),
	.D(wdata[5]),
	.Q(\mem[2] [5]),
	.SE(FE_OCPN27_n_21),
	.SI(\mem[2] [5]));
   SDFFQXL \mem_reg[2][6]  (.CK(wclk_clone1),
	.D(wdata[6]),
	.Q(\mem[2] [6]),
	.SE(FE_OCPN27_n_21),
	.SI(\mem[2] [6]));
   SDFFQXL \mem_reg[2][7]  (.CK(CTS_1),
	.D(wdata[7]),
	.Q(\mem[2] [7]),
	.SE(FE_OCPN27_n_21),
	.SI(\mem[2] [7]));
   SDFFQXL \mem_reg[3][0]  (.CK(wclk_clone1),
	.D(\mem[3] [0]),
	.Q(\mem[3] [0]),
	.SE(n_30),
	.SI(FE_PHN84_wdata_0));
   SDFFQXL \mem_reg[3][1]  (.CK(wclk_clone1),
	.D(\mem[3] [1]),
	.Q(\mem[3] [1]),
	.SE(n_30),
	.SI(FE_PHN87_wdata_1));
   SDFFQXL \mem_reg[3][2]  (.CK(CTS_1),
	.D(\mem[3] [2]),
	.Q(\mem[3] [2]),
	.SE(n_30),
	.SI(FE_PHN91_wdata_2));
   SDFFQXL \mem_reg[3][3]  (.CK(CTS_1),
	.D(\mem[3] [3]),
	.Q(\mem[3] [3]),
	.SE(n_30),
	.SI(FE_PHN92_wdata_3));
   SDFFQXL \mem_reg[3][4]  (.CK(wclk_clone1),
	.D(\mem[3] [4]),
	.Q(\mem[3] [4]),
	.SE(n_30),
	.SI(FE_PHN86_wdata_4));
   SDFFQXL \mem_reg[3][5]  (.CK(wclk_clone1),
	.D(\mem[3] [5]),
	.Q(\mem[3] [5]),
	.SE(n_30),
	.SI(FE_PHN85_wdata_5));
   SDFFQXL \mem_reg[3][6]  (.CK(wclk_clone1),
	.D(\mem[3] [6]),
	.Q(\mem[3] [6]),
	.SE(n_30),
	.SI(FE_PHN90_wdata_6));
   SDFFQXL \mem_reg[3][7]  (.CK(wclk_clone1),
	.D(\mem[3] [7]),
	.Q(\mem[3] [7]),
	.SE(n_30),
	.SI(FE_PHN83_wdata_7));
   SDFFQXL \mem_reg[4][0]  (.CK(wclk_clone1),
	.D(\mem[4] [0]),
	.Q(\mem[4] [0]),
	.SE(n_20),
	.SI(FE_PHN84_wdata_0));
   SDFFQXL \mem_reg[4][1]  (.CK(CTS_1),
	.D(\mem[4] [1]),
	.Q(\mem[4] [1]),
	.SE(n_20),
	.SI(FE_PHN89_wdata_1));
   SDFFQXL \mem_reg[4][2]  (.CK(CTS_1),
	.D(\mem[4] [2]),
	.Q(\mem[4] [2]),
	.SE(n_20),
	.SI(FE_PHN91_wdata_2));
   SDFFQXL \mem_reg[4][3]  (.CK(CTS_1),
	.D(\mem[4] [3]),
	.Q(\mem[4] [3]),
	.SE(n_20),
	.SI(FE_PHN92_wdata_3));
   SDFFQXL \mem_reg[4][4]  (.CK(wclk_clone1),
	.D(\mem[4] [4]),
	.Q(\mem[4] [4]),
	.SE(n_20),
	.SI(FE_PHN86_wdata_4));
   SDFFQXL \mem_reg[4][5]  (.CK(CTS_1),
	.D(\mem[4] [5]),
	.Q(\mem[4] [5]),
	.SE(n_20),
	.SI(wdata[5]));
   SDFFQXL \mem_reg[4][6]  (.CK(CTS_1),
	.D(\mem[4] [6]),
	.Q(\mem[4] [6]),
	.SE(n_20),
	.SI(wdata[6]));
   SDFFQXL \mem_reg[4][7]  (.CK(CTS_1),
	.D(\mem[4] [7]),
	.Q(\mem[4] [7]),
	.SE(n_20),
	.SI(wdata[7]));
   SDFFQXL \mem_reg[5][0]  (.CK(wclk_clone1),
	.D(\mem[5] [0]),
	.Q(\mem[5] [0]),
	.SE(FE_OFN12_n_1),
	.SI(FE_PHN84_wdata_0));
   SDFFQXL \mem_reg[5][1]  (.CK(wclk_clone1),
	.D(\mem[5] [1]),
	.Q(\mem[5] [1]),
	.SE(FE_OFN12_n_1),
	.SI(FE_PHN87_wdata_1));
   SDFFQXL \mem_reg[5][2]  (.CK(CTS_1),
	.D(\mem[5] [2]),
	.Q(\mem[5] [2]),
	.SE(FE_OFN12_n_1),
	.SI(FE_PHN91_wdata_2));
   SDFFHQX1 \mem_reg[5][3]  (.CK(CTS_1),
	.D(\mem[5] [3]),
	.Q(\mem[5] [3]),
	.SE(FE_OFN12_n_1),
	.SI(FE_PHN82_wdata_3));
   SDFFQXL \mem_reg[5][4]  (.CK(wclk_clone1),
	.D(\mem[5] [4]),
	.Q(\mem[5] [4]),
	.SE(FE_OFN12_n_1),
	.SI(FE_PHN86_wdata_4));
   SDFFQXL \mem_reg[5][5]  (.CK(CTS_1),
	.D(\mem[5] [5]),
	.Q(\mem[5] [5]),
	.SE(FE_OFN12_n_1),
	.SI(wdata[5]));
   SDFFQXL \mem_reg[5][6]  (.CK(CTS_1),
	.D(\mem[5] [6]),
	.Q(\mem[5] [6]),
	.SE(FE_OFN12_n_1),
	.SI(wdata[6]));
   SDFFHQX1 \mem_reg[5][7]  (.CK(CTS_1),
	.D(\mem[5] [7]),
	.Q(\mem[5] [7]),
	.SE(FE_OFN12_n_1),
	.SI(FE_PHN83_wdata_7));
   SDFFQXL \mem_reg[6][0]  (.CK(wclk_clone1),
	.D(\mem[6] [0]),
	.Q(\mem[6] [0]),
	.SE(n_22),
	.SI(FE_PHN84_wdata_0));
   SDFFQXL \mem_reg[6][1]  (.CK(CTS_1),
	.D(\mem[6] [1]),
	.Q(\mem[6] [1]),
	.SE(n_22),
	.SI(FE_PHN89_wdata_1));
   SDFFQXL \mem_reg[6][2]  (.CK(CTS_1),
	.D(\mem[6] [2]),
	.Q(\mem[6] [2]),
	.SE(n_22),
	.SI(FE_PHN91_wdata_2));
   SDFFQXL \mem_reg[6][3]  (.CK(CTS_1),
	.D(\mem[6] [3]),
	.Q(\mem[6] [3]),
	.SE(n_22),
	.SI(FE_PHN92_wdata_3));
   SDFFQXL \mem_reg[6][4]  (.CK(wclk_clone1),
	.D(\mem[6] [4]),
	.Q(\mem[6] [4]),
	.SE(n_22),
	.SI(FE_PHN86_wdata_4));
   SDFFQXL \mem_reg[6][5]  (.CK(CTS_1),
	.D(\mem[6] [5]),
	.Q(\mem[6] [5]),
	.SE(n_22),
	.SI(wdata[5]));
   SDFFQXL \mem_reg[6][6]  (.CK(CTS_1),
	.D(\mem[6] [6]),
	.Q(\mem[6] [6]),
	.SE(n_22),
	.SI(wdata[6]));
   SDFFQXL \mem_reg[6][7]  (.CK(CTS_1),
	.D(\mem[6] [7]),
	.Q(\mem[6] [7]),
	.SE(n_22),
	.SI(wdata[7]));
   SDFFQXL \mem_reg[7][0]  (.CK(wclk_clone1),
	.D(\mem[7] [0]),
	.Q(\mem[7] [0]),
	.SE(FE_OCPN34_n_24),
	.SI(FE_PHN84_wdata_0));
   SDFFQXL \mem_reg[7][1]  (.CK(CTS_1),
	.D(\mem[7] [1]),
	.Q(\mem[7] [1]),
	.SE(FE_OCPN34_n_24),
	.SI(FE_PHN89_wdata_1));
   SDFFQXL \mem_reg[7][2]  (.CK(CTS_1),
	.D(\mem[7] [2]),
	.Q(\mem[7] [2]),
	.SE(FE_OCPN34_n_24),
	.SI(FE_PHN91_wdata_2));
   SDFFQXL \mem_reg[7][3]  (.CK(CTS_1),
	.D(\mem[7] [3]),
	.Q(\mem[7] [3]),
	.SE(FE_OCPN34_n_24),
	.SI(FE_PHN92_wdata_3));
   SDFFQXL \mem_reg[7][4]  (.CK(wclk_clone1),
	.D(\mem[7] [4]),
	.Q(\mem[7] [4]),
	.SE(FE_OCPN34_n_24),
	.SI(FE_PHN88_wdata_4));
   SDFFQXL \mem_reg[7][5]  (.CK(CTS_1),
	.D(\mem[7] [5]),
	.Q(\mem[7] [5]),
	.SE(FE_OCPN34_n_24),
	.SI(wdata[5]));
   SDFFQXL \mem_reg[7][6]  (.CK(CTS_1),
	.D(\mem[7] [6]),
	.Q(\mem[7] [6]),
	.SE(FE_OCPN34_n_24),
	.SI(wdata[6]));
   SDFFQXL \mem_reg[7][7]  (.CK(CTS_1),
	.D(\mem[7] [7]),
	.Q(\mem[7] [7]),
	.SE(FE_OCPN34_n_24),
	.SI(wdata[7]));
   SDFFQXL \mem_reg[8][0]  (.CK(wclk_clone1),
	.D(wdata[0]),
	.Q(\mem[8] [0]),
	.SE(FE_OCPN42_n_23),
	.SI(\mem[8] [0]));
   SDFFQXL \mem_reg[8][1]  (.CK(CTS_1),
	.D(wdata[1]),
	.Q(\mem[8] [1]),
	.SE(FE_OCPN42_n_23),
	.SI(\mem[8] [1]));
   SDFFQXL \mem_reg[8][2]  (.CK(CTS_1),
	.D(wdata[2]),
	.Q(\mem[8] [2]),
	.SE(FE_OCPN42_n_23),
	.SI(\mem[8] [2]));
   SDFFQXL \mem_reg[8][3]  (.CK(CTS_1),
	.D(wdata[3]),
	.Q(\mem[8] [3]),
	.SE(FE_OCPN42_n_23),
	.SI(\mem[8] [3]));
   SDFFQXL \mem_reg[8][4]  (.CK(wclk_clone1),
	.D(wdata[4]),
	.Q(\mem[8] [4]),
	.SE(FE_OCPN42_n_23),
	.SI(\mem[8] [4]));
   SDFFQXL \mem_reg[8][5]  (.CK(wclk_clone1),
	.D(wdata[5]),
	.Q(\mem[8] [5]),
	.SE(FE_OCPN42_n_23),
	.SI(\mem[8] [5]));
   SDFFQXL \mem_reg[8][6]  (.CK(wclk_clone1),
	.D(wdata[6]),
	.Q(\mem[8] [6]),
	.SE(FE_OCPN42_n_23),
	.SI(\mem[8] [6]));
   SDFFQXL \mem_reg[8][7]  (.CK(wclk_clone1),
	.D(wdata[7]),
	.Q(\mem[8] [7]),
	.SE(FE_OCPN42_n_23),
	.SI(\mem[8] [7]));
   SDFFQXL \mem_reg[9][0]  (.CK(wclk_clone1),
	.D(wdata[0]),
	.Q(\mem[9] [0]),
	.SE(FE_OCPN45_n_27),
	.SI(\mem[9] [0]));
   SDFFQXL \mem_reg[9][1]  (.CK(CTS_1),
	.D(wdata[1]),
	.Q(\mem[9] [1]),
	.SE(FE_OCPN45_n_27),
	.SI(\mem[9] [1]));
   SDFFQXL \mem_reg[9][2]  (.CK(CTS_1),
	.D(wdata[2]),
	.Q(\mem[9] [2]),
	.SE(FE_OCPN45_n_27),
	.SI(\mem[9] [2]));
   SDFFQXL \mem_reg[9][3]  (.CK(CTS_1),
	.D(wdata[3]),
	.Q(\mem[9] [3]),
	.SE(FE_OCPN45_n_27),
	.SI(\mem[9] [3]));
   SDFFQXL \mem_reg[9][4]  (.CK(wclk_clone1),
	.D(wdata[4]),
	.Q(\mem[9] [4]),
	.SE(FE_OCPN45_n_27),
	.SI(\mem[9] [4]));
   SDFFQXL \mem_reg[9][5]  (.CK(wclk_clone1),
	.D(wdata[5]),
	.Q(\mem[9] [5]),
	.SE(FE_OCPN45_n_27),
	.SI(\mem[9] [5]));
   SDFFQXL \mem_reg[9][6]  (.CK(wclk_clone1),
	.D(wdata[6]),
	.Q(\mem[9] [6]),
	.SE(FE_OCPN76_n_27),
	.SI(\mem[9] [6]));
   SDFFQXL \mem_reg[9][7]  (.CK(CTS_1),
	.D(wdata[7]),
	.Q(\mem[9] [7]),
	.SE(FE_OCPN45_n_27),
	.SI(\mem[9] [7]));
   SDFFQXL \mem_reg[10][0]  (.CK(wclk_clone1),
	.D(wdata[0]),
	.Q(\mem[10] [0]),
	.SE(FE_OCPN44_n_31),
	.SI(\mem[10] [0]));
   SDFFQXL \mem_reg[10][1]  (.CK(CTS_1),
	.D(wdata[1]),
	.Q(\mem[10] [1]),
	.SE(FE_OCPN44_n_31),
	.SI(\mem[10] [1]));
   SDFFQXL \mem_reg[10][2]  (.CK(CTS_1),
	.D(FE_PHN91_wdata_2),
	.Q(\mem[10] [2]),
	.SE(FE_OCPN44_n_31),
	.SI(\mem[10] [2]));
   SDFFQXL \mem_reg[10][3]  (.CK(CTS_1),
	.D(FE_PHN92_wdata_3),
	.Q(\mem[10] [3]),
	.SE(FE_OCPN44_n_31),
	.SI(\mem[10] [3]));
   SDFFQXL \mem_reg[10][4]  (.CK(wclk_clone1),
	.D(wdata[4]),
	.Q(\mem[10] [4]),
	.SE(FE_OCPN44_n_31),
	.SI(\mem[10] [4]));
   SDFFQXL \mem_reg[10][5]  (.CK(wclk_clone1),
	.D(wdata[5]),
	.Q(\mem[10] [5]),
	.SE(FE_OCPN44_n_31),
	.SI(\mem[10] [5]));
   SDFFQXL \mem_reg[10][6]  (.CK(wclk_clone1),
	.D(wdata[6]),
	.Q(\mem[10] [6]),
	.SE(FE_OCPN44_n_31),
	.SI(\mem[10] [6]));
   SDFFQXL \mem_reg[10][7]  (.CK(CTS_1),
	.D(wdata[7]),
	.Q(\mem[10] [7]),
	.SE(FE_OCPN44_n_31),
	.SI(\mem[10] [7]));
   SDFFQXL \mem_reg[11][0]  (.CK(wclk_clone1),
	.D(wdata[0]),
	.Q(\mem[11] [0]),
	.SE(FE_OCPN47_n_25),
	.SI(\mem[11] [0]));
   SDFFQXL \mem_reg[11][1]  (.CK(CTS_1),
	.D(wdata[1]),
	.Q(\mem[11] [1]),
	.SE(FE_OCPN47_n_25),
	.SI(\mem[11] [1]));
   SDFFQXL \mem_reg[11][2]  (.CK(CTS_1),
	.D(FE_PHN91_wdata_2),
	.Q(\mem[11] [2]),
	.SE(FE_OCPN47_n_25),
	.SI(\mem[11] [2]));
   SDFFQXL \mem_reg[11][3]  (.CK(CTS_1),
	.D(FE_PHN92_wdata_3),
	.Q(\mem[11] [3]),
	.SE(FE_OCPN47_n_25),
	.SI(\mem[11] [3]));
   SDFFQXL \mem_reg[11][4]  (.CK(wclk_clone1),
	.D(wdata[4]),
	.Q(\mem[11] [4]),
	.SE(FE_OCPN47_n_25),
	.SI(\mem[11] [4]));
   SDFFQXL \mem_reg[11][5]  (.CK(wclk_clone1),
	.D(wdata[5]),
	.Q(\mem[11] [5]),
	.SE(FE_OCPN47_n_25),
	.SI(\mem[11] [5]));
   SDFFQXL \mem_reg[11][6]  (.CK(wclk_clone1),
	.D(wdata[6]),
	.Q(\mem[11] [6]),
	.SE(FE_OCPN47_n_25),
	.SI(\mem[11] [6]));
   SDFFQXL \mem_reg[11][7]  (.CK(CTS_1),
	.D(wdata[7]),
	.Q(\mem[11] [7]),
	.SE(FE_OCPN47_n_25),
	.SI(\mem[11] [7]));
   SDFFQX4 \mem_reg[12][0]  (.CK(wclk_clone1),
	.D(FE_PHN84_wdata_0),
	.Q(\mem[12] [0]),
	.SE(FE_OCPN77_n_29),
	.SI(\mem[12] [0]));
   SDFFQXL \mem_reg[12][1]  (.CK(CTS_1),
	.D(wdata[1]),
	.Q(\mem[12] [1]),
	.SE(FE_OCPN77_n_29),
	.SI(\mem[12] [1]));
   SDFFQXL \mem_reg[12][2]  (.CK(CTS_1),
	.D(FE_PHN91_wdata_2),
	.Q(\mem[12] [2]),
	.SE(FE_OCPN77_n_29),
	.SI(\mem[12] [2]));
   SDFFQXL \mem_reg[12][3]  (.CK(CTS_1),
	.D(wdata[3]),
	.Q(\mem[12] [3]),
	.SE(FE_OCPN77_n_29),
	.SI(\mem[12] [3]));
   SDFFQXL \mem_reg[12][4]  (.CK(CTS_1),
	.D(wdata[4]),
	.Q(\mem[12] [4]),
	.SE(FE_OCPN77_n_29),
	.SI(\mem[12] [4]));
   SDFFQXL \mem_reg[12][5]  (.CK(CTS_1),
	.D(wdata[5]),
	.Q(\mem[12] [5]),
	.SE(FE_OCPN77_n_29),
	.SI(\mem[12] [5]));
   SDFFQXL \mem_reg[12][6]  (.CK(CTS_1),
	.D(wdata[6]),
	.Q(\mem[12] [6]),
	.SE(FE_OCPN77_n_29),
	.SI(\mem[12] [6]));
   SDFFQXL \mem_reg[12][7]  (.CK(CTS_1),
	.D(wdata[7]),
	.Q(\mem[12] [7]),
	.SE(FE_OCPN77_n_29),
	.SI(\mem[12] [7]));
   SDFFQX1 \mem_reg[13][0]  (.CK(wclk_clone1),
	.D(wdata[0]),
	.Q(\mem[13] [0]),
	.SE(FE_OFN13_n_19),
	.SI(\mem[13] [0]));
   SDFFQX1 \mem_reg[13][1]  (.CK(CTS_1),
	.D(wdata[1]),
	.Q(\mem[13] [1]),
	.SE(FE_OFN13_n_19),
	.SI(\mem[13] [1]));
   SDFFQX1 \mem_reg[13][2]  (.CK(CTS_1),
	.D(FE_PHN91_wdata_2),
	.Q(\mem[13] [2]),
	.SE(FE_OFN13_n_19),
	.SI(\mem[13] [2]));
   SDFFQX1 \mem_reg[13][3]  (.CK(CTS_1),
	.D(wdata[3]),
	.Q(\mem[13] [3]),
	.SE(FE_OFN13_n_19),
	.SI(\mem[13] [3]));
   SDFFQX1 \mem_reg[13][4]  (.CK(CTS_1),
	.D(wdata[4]),
	.Q(\mem[13] [4]),
	.SE(FE_OFN13_n_19),
	.SI(\mem[13] [4]));
   SDFFQX1 \mem_reg[13][5]  (.CK(CTS_1),
	.D(wdata[5]),
	.Q(\mem[13] [5]),
	.SE(FE_OFN13_n_19),
	.SI(\mem[13] [5]));
   SDFFQX1 \mem_reg[13][6]  (.CK(CTS_1),
	.D(wdata[6]),
	.Q(\mem[13] [6]),
	.SE(FE_OFN13_n_19),
	.SI(\mem[13] [6]));
   SDFFQX1 \mem_reg[13][7]  (.CK(CTS_1),
	.D(wdata[7]),
	.Q(\mem[13] [7]),
	.SE(FE_OFN13_n_19),
	.SI(\mem[13] [7]));
   SDFFQX1 \mem_reg[14][0]  (.CK(wclk_clone1),
	.D(\mem[14] [0]),
	.Q(\mem[14] [0]),
	.SE(n_28),
	.SI(wdata[0]));
   SDFFQX1 \mem_reg[14][1]  (.CK(wclk_clone1),
	.D(\mem[14] [1]),
	.Q(\mem[14] [1]),
	.SE(n_28),
	.SI(wdata[1]));
   SDFFQXL \mem_reg[14][2]  (.CK(CTS_1),
	.D(\mem[14] [2]),
	.Q(\mem[14] [2]),
	.SE(n_28),
	.SI(FE_PHN91_wdata_2));
   SDFFQXL \mem_reg[14][3]  (.CK(CTS_1),
	.D(\mem[14] [3]),
	.Q(\mem[14] [3]),
	.SE(n_28),
	.SI(FE_PHN92_wdata_3));
   SDFFQX1 \mem_reg[14][4]  (.CK(wclk_clone1),
	.D(\mem[14] [4]),
	.Q(\mem[14] [4]),
	.SE(n_28),
	.SI(wdata[4]));
   SDFFQXL \mem_reg[14][5]  (.CK(CTS_1),
	.D(\mem[14] [5]),
	.Q(\mem[14] [5]),
	.SE(n_28),
	.SI(wdata[5]));
   SDFFQXL \mem_reg[14][6]  (.CK(CTS_1),
	.D(\mem[14] [6]),
	.Q(\mem[14] [6]),
	.SE(n_28),
	.SI(wdata[6]));
   SDFFQXL \mem_reg[14][7]  (.CK(CTS_1),
	.D(\mem[14] [7]),
	.Q(\mem[14] [7]),
	.SE(n_28),
	.SI(wdata[7]));
   SDFFQXL \mem_reg[15][0]  (.CK(wclk_clone1),
	.D(\mem[15] [0]),
	.Q(\mem[15] [0]),
	.SE(n_6),
	.SI(FE_PHN84_wdata_0));
   SDFFQXL \mem_reg[15][1]  (.CK(wclk_clone1),
	.D(\mem[15] [1]),
	.Q(\mem[15] [1]),
	.SE(n_6),
	.SI(FE_PHN87_wdata_1));
   SDFFQXL \mem_reg[15][2]  (.CK(CTS_1),
	.D(\mem[15] [2]),
	.Q(\mem[15] [2]),
	.SE(n_6),
	.SI(FE_PHN91_wdata_2));
   SDFFQXL \mem_reg[15][3]  (.CK(CTS_1),
	.D(\mem[15] [3]),
	.Q(\mem[15] [3]),
	.SE(n_6),
	.SI(FE_PHN92_wdata_3));
   SDFFQXL \mem_reg[15][4]  (.CK(wclk_clone1),
	.D(\mem[15] [4]),
	.Q(\mem[15] [4]),
	.SE(n_6),
	.SI(FE_PHN86_wdata_4));
   SDFFQXL \mem_reg[15][5]  (.CK(CTS_1),
	.D(\mem[15] [5]),
	.Q(\mem[15] [5]),
	.SE(n_6),
	.SI(wdata[5]));
   SDFFQXL \mem_reg[15][6]  (.CK(CTS_1),
	.D(\mem[15] [6]),
	.Q(\mem[15] [6]),
	.SE(n_6),
	.SI(wdata[6]));
   SDFFQXL \mem_reg[15][7]  (.CK(CTS_1),
	.D(\mem[15] [7]),
	.Q(\mem[15] [7]),
	.SE(n_6),
	.SI(wdata[7]));
   NAND2X2 g3045 (.A(n_16),
	.B(n_12),
	.Y(n_31));
   NOR2X4 g3047 (.A(n_11),
	.B(FE_OCPN35_n_17),
	.Y(n_30));
   NAND2X4 g3048 (.A(n_16),
	.B(n_7),
	.Y(n_29));
   AND2X6 g3050 (.A(FE_OCPN38_n_8),
	.B(n_16),
	.Y(n_28));
   NAND2X2 g3051 (.A(n_13),
	.B(n_2),
	.Y(n_27));
   NAND2X2 g3052 (.A(n_13),
	.B(n_18),
	.Y(n_0));
   NAND2X2 g3053 (.A(n_12),
	.B(n_2),
	.Y(n_25));
   NOR2X2 g3054 (.A(n_8),
	.B(FE_OCPN35_n_17),
	.Y(n_24));
   AND2X6 g3057 (.A(FE_OCPN38_n_8),
	.B(FE_RN_1),
	.Y(n_22));
   NAND2X4 g3058 (.A(FE_RN_1),
	.B(n_12),
	.Y(n_21));
   AND2X6 g3059 (.A(FE_RN_1),
	.B(FE_OCPN74_n_7),
	.Y(n_20));
   NAND2X2 g3060 (.A(n_7),
	.B(n_2),
	.Y(n_19));
   NAND2XL g3066 (.A(n_10),
	.B(waddr[3]),
	.Y(n_15));
   NOR2BX2 g3067 (.AN(n_10),
	.B(waddr[3]),
	.Y(n_5));
   NOR2X4 g3070 (.A(FE_OCPN1_waddr_2),
	.B(waddr[1]),
	.Y(n_13));
   NOR2BX2 g3074 (.AN(wclk_en),
	.B(wfull),
	.Y(n_10));
   NAND2X2 g3075 (.A(FE_OCPN1_waddr_2),
	.B(waddr[1]),
	.Y(n_8));
   NOR2BX4 g3076 (.AN(waddr[2]),
	.B(waddr[1]),
	.Y(n_7));
   AND2X8 g3080 (.A(FE_OCPN38_n_8),
	.B(n_2),
	.Y(n_6));
   NAND2BX2 g2 (.AN(n_17),
	.B(n_13),
	.Y(n_4));
   NOR2BX2 g3085 (.AN(n_7),
	.B(FE_OCPN35_n_17),
	.Y(n_1));
endmodule

module rptr_empty_ADDR_SIZE4 (
	rempty, 
	raddr, 
	rptr, 
	rq2_wptr, 
	rinc, 
	rclk, 
	rrst_n);
   output rempty;
   output [3:0] raddr;
   output [4:0] rptr;
   input [4:0] rq2_wptr;
   input rinc;
   input rclk;
   input rrst_n;

   // Internal wires
   wire FE_OFN9_rempty;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;

   CLKBUFX12 FE_OFC9_rempty (.A(FE_OFN9_rempty),
	.Y(rempty));
   CLKXOR2X1 g188 (.A(rptr[0]),
	.B(raddr[1]),
	.Y(raddr[0]));
   CLKXOR2X1 g189 (.A(rptr[1]),
	.B(raddr[2]),
	.Y(raddr[1]));
   NOR2XL g190 (.A(n_22),
	.B(n_23),
	.Y(FE_OFN9_rempty));
   CLKXOR2X1 g191 (.A(rptr[2]),
	.B(raddr[3]),
	.Y(raddr[2]));
   NAND4XL g192 (.A(n_18),
	.B(n_21),
	.C(n_19),
	.D(n_20),
	.Y(n_23));
   AOI21X1 g193 (.A0(rq2_wptr[4]),
	.A1(rptr[4]),
	.B0(n_17),
	.Y(n_22));
   XNOR2XL g194 (.A(rq2_wptr[2]),
	.B(rptr[2]),
	.Y(n_21));
   XNOR2XL g195 (.A(rq2_wptr[3]),
	.B(rptr[3]),
	.Y(n_20));
   XNOR2XL g196 (.A(rq2_wptr[0]),
	.B(rptr[0]),
	.Y(n_19));
   XNOR2XL g197 (.A(rq2_wptr[1]),
	.B(rptr[1]),
	.Y(n_18));
   CLKXOR2X4 g198 (.A(rptr[4]),
	.B(rptr[3]),
	.Y(raddr[3]));
   NOR2XL g199 (.A(rq2_wptr[4]),
	.B(rptr[4]),
	.Y(n_17));
   SDFFRHQX1 \rptr_reg[3]  (.CK(rclk),
	.D(n_13),
	.Q(rptr[3]),
	.RN(rrst_n),
	.SE(n_16),
	.SI(n_14));
   DFFRHQX1 \rptr_reg[4]  (.CK(rclk),
	.D(n_16),
	.Q(rptr[4]),
	.RN(rrst_n));
   SDFFRHQX1 \rptr_reg[2]  (.CK(rclk),
	.D(n_13),
	.Q(rptr[2]),
	.RN(rrst_n),
	.SE(n_10),
	.SI(n_14));
   OAI21X1 g136 (.A0(n_11),
	.A1(rptr[4]),
	.B0(n_15),
	.Y(n_16));
   NAND2XL g137 (.A(n_11),
	.B(rptr[4]),
	.Y(n_15));
   INVX1 g138 (.A(n_13),
	.Y(n_14));
   SDFFRHQX1 \rptr_reg[1]  (.CK(rclk),
	.D(n_6),
	.Q(rptr[1]),
	.RN(rrst_n),
	.SE(n_10),
	.SI(n_7));
   OAI21X1 g140 (.A0(n_8),
	.A1(raddr[3]),
	.B0(n_12),
	.Y(n_13));
   NAND2XL g141 (.A(n_8),
	.B(raddr[3]),
	.Y(n_12));
   NAND2BX1 g142 (.AN(n_8),
	.B(raddr[3]),
	.Y(n_11));
   SDFFRHQX1 \rptr_reg[0]  (.CK(rclk),
	.D(n_6),
	.Q(rptr[0]),
	.RN(rrst_n),
	.SE(n_3),
	.SI(n_7));
   OAI21X1 g144 (.A0(n_4),
	.A1(raddr[2]),
	.B0(n_9),
	.Y(n_10));
   NAND2XL g145 (.A(n_4),
	.B(raddr[2]),
	.Y(n_9));
   NAND2BX1 g146 (.AN(n_4),
	.B(raddr[2]),
	.Y(n_8));
   INVX1 g147 (.A(n_6),
	.Y(n_7));
   OAI21X1 g148 (.A0(n_1),
	.A1(raddr[1]),
	.B0(n_5),
	.Y(n_6));
   NAND2XL g149 (.A(n_1),
	.B(raddr[1]),
	.Y(n_5));
   NAND2BX1 g150 (.AN(n_1),
	.B(raddr[1]),
	.Y(n_4));
   OAI21XL g151 (.A0(raddr[0]),
	.A1(n_0),
	.B0(n_2),
	.Y(n_3));
   NAND2XL g152 (.A(n_0),
	.B(raddr[0]),
	.Y(n_2));
   NAND2BX1 g153 (.AN(n_0),
	.B(raddr[0]),
	.Y(n_1));
   NAND2BX1 g154 (.AN(rempty),
	.B(rinc),
	.Y(n_0));
endmodule

module two_ff_sync_SIZE5 (
	q2, 
	din, 
	rst_n, 
	clk);
   output [4:0] q2;
   input [4:0] din;
   input rst_n;
   input clk;

   // Internal wires
   wire [4:0] q1;

   DFFRHQX1 \q2_reg[4]  (.CK(clk),
	.D(q1[4]),
	.Q(q2[4]),
	.RN(rst_n));
   DFFRHQX1 \q2_reg[3]  (.CK(clk),
	.D(q1[3]),
	.Q(q2[3]),
	.RN(rst_n));
   DFFRHQX1 \q2_reg[1]  (.CK(clk),
	.D(q1[1]),
	.Q(q2[1]),
	.RN(rst_n));
   DFFRHQX4 \q2_reg[0]  (.CK(clk),
	.D(q1[0]),
	.Q(q2[0]),
	.RN(rst_n));
   DFFRHQX1 \q2_reg[2]  (.CK(clk),
	.D(q1[2]),
	.Q(q2[2]),
	.RN(rst_n));
   DFFRHQX1 \q1_reg[2]  (.CK(clk),
	.D(din[2]),
	.Q(q1[2]),
	.RN(rst_n));
   DFFRHQX1 \q1_reg[3]  (.CK(clk),
	.D(din[3]),
	.Q(q1[3]),
	.RN(rst_n));
   DFFRHQX1 \q1_reg[4]  (.CK(clk),
	.D(din[4]),
	.Q(q1[4]),
	.RN(rst_n));
   DFFRHQX1 \q1_reg[1]  (.CK(clk),
	.D(din[1]),
	.Q(q1[1]),
	.RN(rst_n));
   DFFRHQX1 \q1_reg[0]  (.CK(clk),
	.D(din[0]),
	.Q(q1[0]),
	.RN(rst_n));
endmodule

module two_ff_sync_SIZE5_1 (
	q2, 
	din, 
	clk, 
	rst_n);
   output [4:0] q2;
   input [4:0] din;
   input clk;
   input rst_n;

   // Internal wires
   wire [4:0] q1;

   DFFRHQX1 \q2_reg[4]  (.CK(clk),
	.D(q1[4]),
	.Q(q2[4]),
	.RN(rst_n));
   DFFRHQX1 \q2_reg[3]  (.CK(clk),
	.D(q1[3]),
	.Q(q2[3]),
	.RN(rst_n));
   DFFRHQX1 \q2_reg[1]  (.CK(clk),
	.D(q1[1]),
	.Q(q2[1]),
	.RN(rst_n));
   DFFRHQX1 \q2_reg[0]  (.CK(clk),
	.D(q1[0]),
	.Q(q2[0]),
	.RN(rst_n));
   DFFRHQX1 \q2_reg[2]  (.CK(clk),
	.D(q1[2]),
	.Q(q2[2]),
	.RN(rst_n));
   DFFRHQX1 \q1_reg[2]  (.CK(clk),
	.D(din[2]),
	.Q(q1[2]),
	.RN(rst_n));
   DFFRHQX1 \q1_reg[3]  (.CK(clk),
	.D(din[3]),
	.Q(q1[3]),
	.RN(rst_n));
   DFFRHQX1 \q1_reg[4]  (.CK(clk),
	.D(din[4]),
	.Q(q1[4]),
	.RN(rst_n));
   DFFRHQX1 \q1_reg[1]  (.CK(clk),
	.D(din[1]),
	.Q(q1[1]),
	.RN(rst_n));
   DFFRHQX1 \q1_reg[0]  (.CK(clk),
	.D(din[0]),
	.Q(q1[0]),
	.RN(rst_n));
endmodule

module wptr_full_ADDR_SIZE4 (
	wfull, 
	waddr, 
	wptr, 
	wq2_rptr, 
	winc, 
	wrst_n, 
	wclk, 
	FE_OCPN0_waddr_2);
   output wfull;
   output [3:0] waddr;
   output [4:0] wptr;
   input [4:0] wq2_rptr;
   input winc;
   input wrst_n;
   input wclk;
   output FE_OCPN0_waddr_2;

   // Internal wires
   wire FE_OCPN78_n_8;
   wire FE_RN_55_0;
   wire FE_OCPN48_wptr_1;
   wire FE_RN_3;
   wire FE_RN_53_0;
   wire FE_RN_52_0;
   wire FE_RN_51_0;
   wire FE_RN_50_0;
   wire FE_RN_49_0;
   wire FE_RN_48_0;
   wire FE_OCPN72_waddr_1;
   wire FE_RN_47_0;
   wire FE_RN_2;
   wire FE_RN_45_0;
   wire FE_RN_44_0;
   wire FE_RN_41_0;
   wire FE_RN_39_0;
   wire FE_RN_37_0;
   wire FE_RN_36_0;
   wire FE_RN_35_0;
   wire FE_RN_34_0;
   wire FE_RN_33_0;
   wire FE_RN_1;
   wire FE_RN_31_0;
   wire FE_RN_28_0;
   wire FE_RN_27_0;
   wire FE_RN_26_0;
   wire FE_RN_25_0;
   wire FE_RN_24_0;
   wire FE_RN_22_0;
   wire FE_RN_21_0;
   wire FE_RN_19_0;
   wire FE_RN_18_0;
   wire FE_OCPN36_wptr_3;
   wire FE_OCPN32_wptr_2;
   wire FE_OCPN31_n_30;
   wire FE_OCPN30_n_30;
   wire FE_RN_10_0;
   wire FE_RN_9_0;
   wire FE_RN_8_0;
   wire FE_OCPN19_wptr_4;
   wire FE_OCPN18_waddr_3;
   wire FE_RN_1_0;
   wire FE_OFN15_n_30;
   wire FE_OFN14_n_17;
   wire [4:0] wbin_current;
   wire n_0;
   wire n_1;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_12;
   wire n_13;
   wire n_16;
   wire n_17;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_25;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_46;
   wire n_47;

   OAI21X1 FE_RC_104_0 (.A0(FE_OCPN0_waddr_2),
	.A1(n_5),
	.B0(n_9),
	.Y(FE_RN_1));
   CLKBUFX2 FE_OCPC78_n_8 (.A(n_8),
	.Y(FE_OCPN78_n_8));
   INVX2 FE_RC_103_0 (.A(FE_RN_55_0),
	.Y(n_8));
   NAND3X2 FE_RC_102_0 (.A(FE_OCPN0_waddr_2),
	.B(waddr[1]),
	.C(n_1),
	.Y(FE_RN_55_0));
   BUFX2 FE_OCPC69_wptr_1 (.A(FE_OCPN48_wptr_1),
	.Y(wptr[1]));
   NAND2X4 FE_RC_68_0_dup (.A(waddr[1]),
	.B(n_1),
	.Y(FE_RN_3));
   INVX1 FE_RC_96_0 (.A(n_22),
	.Y(FE_RN_52_0));
   INVX1 FE_RC_95_0 (.A(n_20),
	.Y(FE_RN_53_0));
   NOR4BBX4 FE_RC_94_0 (.AN(FE_RN_53_0),
	.BN(FE_RN_52_0),
	.C(FE_RN_47_0),
	.D(n_29),
	.Y(wfull));
   CLKBUFX3 FE_OCPC67_waddr_2 (.A(waddr[2]),
	.Y(FE_OCPN0_waddr_2));
   NAND2BX1 FE_RC_93_0 (.AN(wptr[0]),
	.B(FE_OCPN48_wptr_1),
	.Y(FE_RN_50_0));
   OAI2BB1X1 FE_RC_92_0 (.A0N(wptr[0]),
	.A1N(FE_RN_8_0),
	.B0(FE_RN_50_0),
	.Y(FE_RN_51_0));
   NOR2BX2 FE_RC_91_0 (.AN(FE_RN_51_0),
	.B(FE_OFN15_n_30),
	.Y(FE_RN_45_0));
   NOR2X2 FE_RC_90_0 (.A(wq2_rptr[3]),
	.B(wptr[3]),
	.Y(FE_RN_49_0));
   CLKINVX2 FE_RC_89_0 (.A(FE_RN_49_0),
	.Y(FE_RN_48_0));
   NAND3X4 FE_RC_88_0 (.A(FE_RN_48_0),
	.B(n_21),
	.C(n_25),
	.Y(n_29));
   CLKBUFX2 FE_OCPC72_waddr_1 (.A(waddr[1]),
	.Y(FE_OCPN72_waddr_1));
   CLKINVX2 FE_RC_87_0 (.A(FE_RN_24_0),
	.Y(FE_RN_47_0));
   OAI21X1 FE_RC_83_0_dup (.A0(FE_RN_21_0),
	.A1(FE_OCPN78_n_8),
	.B0(FE_RN_22_0),
	.Y(FE_RN_2));
   OAI21X1 FE_RC_85_0 (.A0(n_46),
	.A1(n_17),
	.B0(FE_RN_31_0),
	.Y(n_19));
   OAI2BB1X4 FE_RC_84_0 (.A0N(FE_OCPN32_wptr_2),
	.A1N(FE_OCPN18_waddr_3),
	.B0(FE_RN_39_0),
	.Y(FE_OFN15_n_30));
   OAI21X1 FE_RC_83_0 (.A0(FE_RN_21_0),
	.A1(n_8),
	.B0(FE_RN_22_0),
	.Y(n_46));
   AOI22X2 FE_RC_82_0 (.A0(FE_OCPN36_wptr_3),
	.A1(FE_OCPN19_wptr_4),
	.B0(FE_RN_1_0),
	.B1(n_23),
	.Y(FE_OCPN18_waddr_3));
   CLKINVX2 FE_RC_76_0 (.A(FE_RN_45_0),
	.Y(FE_RN_44_0));
   NAND3X4 FE_RC_75_0 (.A(FE_RN_26_0),
	.B(FE_RN_28_0),
	.C(FE_RN_44_0),
	.Y(waddr[0]));
   CLKINVX1 FE_RC_70_0 (.A(FE_OCPN32_wptr_2),
	.Y(FE_RN_41_0));
   NAND2X2 FE_RC_69_0 (.A(FE_RN_41_0),
	.B(n_27),
	.Y(FE_RN_39_0));
   NAND2X2 FE_RC_68_0 (.A(waddr[1]),
	.B(n_1),
	.Y(n_5));
   NAND2BX1 FE_RC_62_0 (.AN(wq2_rptr[0]),
	.B(wptr[0]),
	.Y(FE_RN_36_0));
   INVX1 FE_RC_61_0 (.A(wq2_rptr[0]),
	.Y(FE_RN_37_0));
   OAI21X1 FE_RC_60_0 (.A0(FE_RN_37_0),
	.A1(wptr[0]),
	.B0(FE_RN_36_0),
	.Y(n_20));
   NAND2X2 FE_RC_59_0 (.A(wq2_rptr[2]),
	.B(wptr[2]),
	.Y(FE_RN_35_0));
   OAI21X2 FE_RC_58_0 (.A0(wq2_rptr[2]),
	.A1(wptr[2]),
	.B0(FE_RN_35_0),
	.Y(n_21));
   NAND2BX1 FE_RC_57_0 (.AN(wq2_rptr[1]),
	.B(FE_OCPN48_wptr_1),
	.Y(FE_RN_33_0));
   INVX1 FE_RC_56_0 (.A(wq2_rptr[1]),
	.Y(FE_RN_34_0));
   OAI21X1 FE_RC_55_0 (.A0(FE_RN_34_0),
	.A1(FE_OCPN48_wptr_1),
	.B0(FE_RN_33_0),
	.Y(n_22));
   NAND2X1 FE_RC_51_0 (.A(n_17),
	.B(FE_RN_2),
	.Y(FE_RN_31_0));
   NAND2XL FE_RC_49_0 (.A(wptr[0]),
	.B(FE_OCPN48_wptr_1),
	.Y(FE_RN_25_0));
   NAND2BX2 FE_RC_48_0 (.AN(FE_RN_25_0),
	.B(FE_OFN15_n_30),
	.Y(FE_RN_26_0));
   NOR2XL FE_RC_47_0 (.A(wptr[0]),
	.B(wptr[1]),
	.Y(FE_RN_27_0));
   NAND2X2 FE_RC_46_0 (.A(FE_RN_27_0),
	.B(FE_OFN15_n_30),
	.Y(FE_RN_28_0));
   CLKINVX1 FE_RC_42_0 (.A(n_28),
	.Y(FE_RN_24_0));
   INVX2 FE_OCPC52_wptr_3 (.A(FE_OCPN36_wptr_3),
	.Y(FE_RN_1_0));
   BUFX3 FE_OCPC51_wptr_3 (.A(FE_OCPN36_wptr_3),
	.Y(wptr[3]));
   CLKINVX1 FE_RC_40_0 (.A(waddr[3]),
	.Y(FE_RN_21_0));
   NAND2X2 FE_RC_39_0 (.A(FE_RN_21_0),
	.B(n_8),
	.Y(FE_RN_22_0));
   NAND2XL FE_RC_33_0 (.A(waddr[3]),
	.B(waddr[2]),
	.Y(FE_RN_18_0));
   CLKINVX2 FE_RC_32_0 (.A(FE_RN_19_0),
	.Y(n_13));
   NOR2X2 FE_RC_31_0 (.A(FE_RN_18_0),
	.B(FE_RN_3),
	.Y(FE_RN_19_0));
   AOI21X2 FE_RC_30_0 (.A0(wptr[4]),
	.A1(n_13),
	.B0(n_16),
	.Y(n_17));
   BUFX2 FE_OCPC43_wptr_4 (.A(FE_OCPN19_wptr_4),
	.Y(wptr[4]));
   CLKINVX1 FE_OCPC41_wptr_2 (.A(wptr[2]),
	.Y(FE_OCPN32_wptr_2));
   BUFX2 FE_OCPC37_n_30 (.A(FE_OFN15_n_30),
	.Y(FE_OCPN31_n_30));
   INVX1 FE_OCPC36_n_30 (.A(FE_OFN15_n_30),
	.Y(FE_OCPN30_n_30));
   BUFX2 FE_OCPC35_n_30 (.A(FE_OFN15_n_30),
	.Y(waddr[2]));
   CLKINVX2 FE_RC_15_0 (.A(FE_OCPN48_wptr_1),
	.Y(FE_RN_8_0));
   NAND2X4 FE_RC_14_0 (.A(FE_RN_8_0),
	.B(FE_OCPN31_n_30),
	.Y(FE_RN_9_0));
   NAND2X4 FE_RC_13_0 (.A(wptr[1]),
	.B(FE_OCPN30_n_30),
	.Y(FE_RN_10_0));
   NAND2X8 FE_RC_12_0 (.A(FE_RN_10_0),
	.B(FE_RN_9_0),
	.Y(waddr[1]));
   BUFX2 FE_OCPC22_waddr_3 (.A(FE_OCPN18_waddr_3),
	.Y(waddr[3]));
   INVX1 FE_OFC17_n_17 (.A(n_17),
	.Y(FE_OFN14_n_17));
   CLKINVX2 FE_OFC15_waddr_3 (.A(FE_OCPN18_waddr_3),
	.Y(n_27));
   MXI2XL g201 (.A(FE_OCPN19_wptr_4),
	.B(n_23),
	.S0(wq2_rptr[4]),
	.Y(n_28));
   NAND2X2 g208 (.A(wq2_rptr[3]),
	.B(wptr[3]),
	.Y(n_25));
   DFFRHQX4 \wptr_reg[3]  (.CK(wclk),
	.D(n_19),
	.Q(FE_OCPN36_wptr_3),
	.RN(wrst_n));
   SDFFRHQX2 \wptr_reg[2]  (.CK(wclk),
	.D(n_10),
	.Q(wptr[2]),
	.RN(wrst_n),
	.SE(n_46),
	.SI(n_12));
   NOR2X2 g143 (.A(wptr[4]),
	.B(n_13),
	.Y(n_16));
   SDFFRHQX8 \wptr_reg[1]  (.CK(wclk),
	.D(n_12),
	.Q(FE_OCPN48_wptr_1),
	.RN(wrst_n),
	.SE(n_47),
	.SI(n_10));
   INVX1 g148 (.A(FE_RN_1),
	.Y(n_12));
   SDFFRHQX8 \wptr_reg[0]  (.CK(wclk),
	.D(n_4),
	.Q(wptr[0]),
	.RN(wrst_n),
	.SE(n_47),
	.SI(n_3));
   OAI21X1 g151 (.A0(n_5),
	.A1(FE_OCPN0_waddr_2),
	.B0(n_9),
	.Y(n_10));
   NAND2X2 g152 (.A(FE_OCPN0_waddr_2),
	.B(n_5),
	.Y(n_9));
   INVXL g157 (.A(n_3),
	.Y(n_4));
   ADDHX4 g159 (.A(waddr[0]),
	.B(n_0),
	.CO(n_1),
	.S(n_3));
   NOR2BX1 g160 (.AN(winc),
	.B(wfull),
	.Y(n_0));
   XNOR2X1 g219 (.A(n_1),
	.B(FE_OCPN72_waddr_1),
	.Y(n_47));
   DFFRX1 \wptr_reg[4]  (.CK(wclk),
	.D(FE_OFN14_n_17),
	.Q(FE_OCPN19_wptr_4),
	.QN(n_23),
	.RN(wrst_n));
endmodule

module FIFO (
	rdata, 
	wfull, 
	rempty, 
	wdata, 
	winc, 
	wclk, 
	wrst_n, 
	rinc, 
	rclk, 
	rrst_n);
   output [7:0] rdata;
   output wfull;
   output rempty;
   input [7:0] wdata;
   input winc;
   input wclk;
   input wrst_n;
   input rinc;
   input rclk;
   input rrst_n;

   // Internal wires
   wire FE_PHN81_rrst_n;
   wire FE_PHN80_wrst_n;
   wire FE_OCPN46_waddr_2;
   wire CTS_1;
   wire FE_OCPN12_FE_OFN10_FE_OFN8_wfull;
   wire FE_OFN10_FE_OFN8_wfull;
   wire FE_OFN7_rdata_0;
   wire FE_OFN6_rdata_1;
   wire FE_OFN5_rdata_2;
   wire FE_OFN4_rdata_3;
   wire FE_OFN3_rdata_4;
   wire FE_OFN2_rdata_5;
   wire FE_OFN1_rdata_6;
   wire FE_OFN0_rdata_7;
   wire [3:0] waddr;
   wire [3:0] raddr;
   wire [7:0] rdata_raw;
   wire [4:0] rq2_wptr;
   wire [4:0] rptr;
   wire [4:0] wq2_rptr;
   wire [4:0] wptr;

   CLKBUFX2 FE_PHC81_rrst_n (.A(rrst_n),
	.Y(FE_PHN81_rrst_n));
   CLKBUFX2 FE_PHC80_wrst_n (.A(wrst_n),
	.Y(FE_PHN80_wrst_n));
   CLKBUFX16 CTS_ccl_a_buf_00004 (.A(wclk),
	.Y(CTS_1));
   CLKBUFX2 FE_OCPC12_FE_OFN10_FE_OFN8_wfull (.A(FE_OFN10_FE_OFN8_wfull),
	.Y(FE_OCPN12_FE_OFN10_FE_OFN8_wfull));
   BUFX16 FE_OFC10_FE_OFN8_wfull (.A(FE_OCPN12_FE_OFN10_FE_OFN8_wfull),
	.Y(wfull));
   CLKBUFX12 FE_OFC7_rdata_0 (.A(FE_OFN7_rdata_0),
	.Y(rdata[0]));
   CLKBUFX12 FE_OFC6_rdata_1 (.A(FE_OFN6_rdata_1),
	.Y(rdata[1]));
   CLKBUFX12 FE_OFC5_rdata_2 (.A(FE_OFN5_rdata_2),
	.Y(rdata[2]));
   CLKBUFX12 FE_OFC4_rdata_3 (.A(FE_OFN4_rdata_3),
	.Y(rdata[3]));
   CLKBUFX12 FE_OFC3_rdata_4 (.A(FE_OFN3_rdata_4),
	.Y(rdata[4]));
   CLKBUFX12 FE_OFC2_rdata_5 (.A(FE_OFN2_rdata_5),
	.Y(rdata[5]));
   CLKBUFX12 FE_OFC1_rdata_6 (.A(FE_OFN1_rdata_6),
	.Y(rdata[6]));
   CLKBUFX12 FE_OFC0_rdata_7 (.A(FE_OFN0_rdata_7),
	.Y(rdata[7]));
   FIFO_memory_DATA_SIZE8_ADDR_SIZE4 fifomem (.rdata(rdata_raw),
	.wdata(wdata),
	.waddr(waddr),
	.raddr(raddr),
	.wclk_en(winc),
	.wfull(FE_OFN10_FE_OFN8_wfull),
	.wclk_clone1(CTS_1),
	.wclk(wclk),
	.FE_OCPN1_waddr_2(FE_OCPN46_waddr_2));
   rptr_empty_ADDR_SIZE4 rptr_empty_inst (.rempty(rempty),
	.raddr(raddr),
	.rptr(rptr),
	.rq2_wptr(rq2_wptr),
	.rinc(rinc),
	.rclk(rclk),
	.rrst_n(FE_PHN81_rrst_n));
   two_ff_sync_SIZE5 sync_r2w (.q2(wq2_rptr),
	.din(rptr),
	.rst_n(FE_PHN80_wrst_n),
	.clk(CTS_1));
   two_ff_sync_SIZE5_1 sync_w2r (.q2(rq2_wptr),
	.din(wptr),
	.clk(rclk),
	.rst_n(FE_PHN81_rrst_n));
   wptr_full_ADDR_SIZE4 wptr_full_inst (.wfull(FE_OFN10_FE_OFN8_wfull),
	.waddr(waddr),
	.wptr(wptr),
	.wq2_rptr(wq2_rptr),
	.winc(winc),
	.wrst_n(FE_PHN80_wrst_n),
	.wclk(CTS_1),
	.FE_OCPN0_waddr_2(FE_OCPN46_waddr_2));
   DFFRHQX1 \rdata_reg[7]  (.CK(rclk),
	.D(rdata_raw[7]),
	.Q(FE_OFN0_rdata_7),
	.RN(FE_PHN81_rrst_n));
   DFFRHQX1 \rdata_reg[6]  (.CK(rclk),
	.D(rdata_raw[6]),
	.Q(FE_OFN1_rdata_6),
	.RN(FE_PHN81_rrst_n));
   DFFRHQX1 \rdata_reg[4]  (.CK(rclk),
	.D(rdata_raw[4]),
	.Q(FE_OFN3_rdata_4),
	.RN(FE_PHN81_rrst_n));
   DFFRHQX1 \rdata_reg[0]  (.CK(rclk),
	.D(rdata_raw[0]),
	.Q(FE_OFN7_rdata_0),
	.RN(FE_PHN81_rrst_n));
   DFFRHQX1 \rdata_reg[3]  (.CK(rclk),
	.D(rdata_raw[3]),
	.Q(FE_OFN4_rdata_3),
	.RN(FE_PHN81_rrst_n));
   DFFRHQX1 \rdata_reg[5]  (.CK(rclk),
	.D(rdata_raw[5]),
	.Q(FE_OFN2_rdata_5),
	.RN(FE_PHN81_rrst_n));
   DFFRHQX1 \rdata_reg[2]  (.CK(rclk),
	.D(rdata_raw[2]),
	.Q(FE_OFN5_rdata_2),
	.RN(FE_PHN81_rrst_n));
   DFFRHQX1 \rdata_reg[1]  (.CK(rclk),
	.D(rdata_raw[1]),
	.Q(FE_OFN6_rdata_1),
	.RN(FE_PHN81_rrst_n));
endmodule

