
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Oct 14 2025 17:17:09 IST (Oct 14 2025 11:47:09 UTC)

// Verification Directory fv/FIFO 

module FIFO_memory_DATA_SIZE8_ADDR_SIZE4(rdata, wdata, waddr, raddr,
     wclk_en, wfull, wclk, DFT_sdi, DFT_sen, DFT_sdo);
  input [7:0] wdata;
  input [3:0] waddr, raddr;
  input wclk_en, wfull, wclk, DFT_sdi, DFT_sen;
  output [7:0] rdata;
  output DFT_sdo;
  wire [7:0] wdata;
  wire [3:0] waddr, raddr;
  wire wclk_en, wfull, wclk, DFT_sdi, DFT_sen;
  wire [7:0] rdata;
  wire DFT_sdo;
  wire [7:0] \mem[12] ;
  wire [7:0] \mem[11] ;
  wire [7:0] \mem[0] ;
  wire [7:0] \mem[5] ;
  wire [7:0] \mem[10] ;
  wire [7:0] \mem[9] ;
  wire [7:0] \mem[4] ;
  wire [7:0] \mem[3] ;
  wire [7:0] \mem[8] ;
  wire [7:0] \mem[2] ;
  wire [7:0] \mem[1] ;
  wire [7:0] \mem[7] ;
  wire [7:0] \mem[6] ;
  wire [7:0] \mem[14] ;
  wire [7:0] \mem[13] ;
  wire [7:0] \mem[15] ;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124;
  NAND4XL g2708(.A (n_102), .B (n_105), .C (n_104), .D (n_124), .Y
       (rdata[2]));
  NAND4XL g2709(.A (n_53), .B (n_88), .C (n_93), .D (n_118), .Y
       (rdata[6]));
  NAND4XL g2710(.A (n_107), .B (n_71), .C (n_64), .D (n_122), .Y
       (rdata[7]));
  NAND4XL g2711(.A (n_92), .B (n_90), .C (n_94), .D (n_121), .Y
       (rdata[1]));
  NAND4XL g2712(.A (n_106), .B (n_103), .C (n_55), .D (n_123), .Y
       (rdata[5]));
  NAND4XL g2713(.A (n_76), .B (n_77), .C (n_79), .D (n_120), .Y
       (rdata[0]));
  NAND4XL g2714(.A (n_83), .B (n_78), .C (n_85), .D (n_119), .Y
       (rdata[4]));
  NAND4XL g2715(.A (n_59), .B (n_61), .C (n_62), .D (n_117), .Y
       (rdata[3]));
  AOI221XL g2716(.A0 (\mem[12] [2]), .A1 (n_39), .B0 (\mem[11] [2]),
       .B1 (n_48), .C0 (n_115), .Y (n_124));
  AOI221XL g2717(.A0 (\mem[0] [5]), .A1 (n_52), .B0 (\mem[5] [5]), .B1
       (n_38), .C0 (n_114), .Y (n_123));
  AOI221XL g2718(.A0 (\mem[10] [7]), .A1 (n_37), .B0 (\mem[9] [7]), .B1
       (n_47), .C0 (n_113), .Y (n_122));
  AOI221XL g2719(.A0 (\mem[0] [1]), .A1 (n_52), .B0 (\mem[5] [1]), .B1
       (n_38), .C0 (n_116), .Y (n_121));
  AOI221XL g2720(.A0 (\mem[4] [0]), .A1 (n_46), .B0 (\mem[3] [0]), .B1
       (n_44), .C0 (n_110), .Y (n_120));
  AOI221XL g2721(.A0 (\mem[11] [4]), .A1 (n_48), .B0 (\mem[8] [4]), .B1
       (n_49), .C0 (n_112), .Y (n_119));
  AOI221XL g2722(.A0 (\mem[2] [6]), .A1 (n_40), .B0 (\mem[1] [6]), .B1
       (n_43), .C0 (n_111), .Y (n_118));
  AOI221XL g2723(.A0 (\mem[0] [3]), .A1 (n_52), .B0 (\mem[7] [3]), .B1
       (n_51), .C0 (n_109), .Y (n_117));
  NAND4XL g2724(.A (n_84), .B (n_86), .C (n_87), .D (n_82), .Y (n_116));
  NAND4XL g2725(.A (n_97), .B (n_99), .C (n_100), .D (n_96), .Y
       (n_115));
  NAND4XL g2726(.A (n_91), .B (n_95), .C (n_98), .D (n_89), .Y (n_114));
  NAND4XL g2727(.A (n_57), .B (n_63), .C (n_108), .D (n_101), .Y
       (n_113));
  NAND4XL g2728(.A (n_67), .B (n_70), .C (n_73), .D (n_65), .Y (n_112));
  NAND4XL g2729(.A (n_60), .B (n_66), .C (n_68), .D (n_58), .Y (n_111));
  NAND4XL g2730(.A (n_72), .B (n_74), .C (n_75), .D (n_69), .Y (n_110));
  NAND4XL g2731(.A (n_80), .B (n_54), .C (n_56), .D (n_81), .Y (n_109));
  AOI22XL g2732(.A0 (n_40), .A1 (\mem[2] [7]), .B0 (n_44), .B1
       (\mem[3] [7]), .Y (n_108));
  AOI22XL g2733(.A0 (n_39), .A1 (\mem[12] [7]), .B0 (n_48), .B1
       (\mem[11] [7]), .Y (n_107));
  AOI22XL g2734(.A0 (n_43), .A1 (\mem[1] [5]), .B0 (n_50), .B1
       (\mem[6] [5]), .Y (n_106));
  AOI22XL g2735(.A0 (n_42), .A1 (\mem[14] [2]), .B0 (n_45), .B1
       (\mem[13] [2]), .Y (n_105));
  AOI22XL g2736(.A0 (n_49), .A1 (\mem[8] [2]), .B0 (n_41), .B1
       (\mem[15] [2]), .Y (n_104));
  AOI22XL g2737(.A0 (n_46), .A1 (\mem[4] [5]), .B0 (n_44), .B1
       (\mem[3] [5]), .Y (n_103));
  AOI22XL g2738(.A0 (n_47), .A1 (\mem[9] [2]), .B0 (n_37), .B1
       (\mem[10] [2]), .Y (n_102));
  AOI22XL g2739(.A0 (n_52), .A1 (\mem[0] [7]), .B0 (n_43), .B1
       (\mem[1] [7]), .Y (n_101));
  AOI22XL g2740(.A0 (n_50), .A1 (\mem[6] [2]), .B0 (n_51), .B1
       (\mem[7] [2]), .Y (n_100));
  AOI22XL g2741(.A0 (n_46), .A1 (\mem[4] [2]), .B0 (n_38), .B1
       (\mem[5] [2]), .Y (n_99));
  AOI22XL g2742(.A0 (n_42), .A1 (\mem[14] [5]), .B0 (n_41), .B1
       (\mem[15] [5]), .Y (n_98));
  AOI22XL g2743(.A0 (n_40), .A1 (\mem[2] [2]), .B0 (n_44), .B1
       (\mem[3] [2]), .Y (n_97));
  AOI22XL g2744(.A0 (n_52), .A1 (\mem[0] [2]), .B0 (n_43), .B1
       (\mem[1] [2]), .Y (n_96));
  AOI22XL g2745(.A0 (n_39), .A1 (\mem[12] [5]), .B0 (n_45), .B1
       (\mem[13] [5]), .Y (n_95));
  AOI22XL g2746(.A0 (n_40), .A1 (\mem[2] [1]), .B0 (n_51), .B1
       (\mem[7] [1]), .Y (n_94));
  AOI22XL g2747(.A0 (n_50), .A1 (\mem[6] [6]), .B0 (n_38), .B1
       (\mem[5] [6]), .Y (n_93));
  AOI22XL g2748(.A0 (n_43), .A1 (\mem[1] [1]), .B0 (n_50), .B1
       (\mem[6] [1]), .Y (n_92));
  AOI22XL g2749(.A0 (n_37), .A1 (\mem[10] [5]), .B0 (n_48), .B1
       (\mem[11] [5]), .Y (n_91));
  AOI22XL g2750(.A0 (n_46), .A1 (\mem[4] [1]), .B0 (n_44), .B1
       (\mem[3] [1]), .Y (n_90));
  AOI22XL g2751(.A0 (n_49), .A1 (\mem[8] [5]), .B0 (n_47), .B1
       (\mem[9] [5]), .Y (n_89));
  AOI22XL g2752(.A0 (n_46), .A1 (\mem[4] [6]), .B0 (n_44), .B1
       (\mem[3] [6]), .Y (n_88));
  AOI22XL g2753(.A0 (n_42), .A1 (\mem[14] [1]), .B0 (n_41), .B1
       (\mem[15] [1]), .Y (n_87));
  AOI22XL g2754(.A0 (n_39), .A1 (\mem[12] [1]), .B0 (n_45), .B1
       (\mem[13] [1]), .Y (n_86));
  AOI22XL g2755(.A0 (n_39), .A1 (\mem[12] [4]), .B0 (n_41), .B1
       (\mem[15] [4]), .Y (n_85));
  AOI22XL g2756(.A0 (n_37), .A1 (\mem[10] [1]), .B0 (n_48), .B1
       (\mem[11] [1]), .Y (n_84));
  AOI22XL g2757(.A0 (n_47), .A1 (\mem[9] [4]), .B0 (n_42), .B1
       (\mem[14] [4]), .Y (n_83));
  AOI22XL g2758(.A0 (n_49), .A1 (\mem[8] [1]), .B0 (n_47), .B1
       (\mem[9] [1]), .Y (n_82));
  AOI22XL g2759(.A0 (n_49), .A1 (\mem[8] [3]), .B0 (n_47), .B1
       (\mem[9] [3]), .Y (n_81));
  AOI22XL g2760(.A0 (n_37), .A1 (\mem[10] [3]), .B0 (n_48), .B1
       (\mem[11] [3]), .Y (n_80));
  AOI22XL g2761(.A0 (n_50), .A1 (\mem[6] [0]), .B0 (n_38), .B1
       (\mem[5] [0]), .Y (n_79));
  AOI22XL g2762(.A0 (n_37), .A1 (\mem[10] [4]), .B0 (n_45), .B1
       (\mem[13] [4]), .Y (n_78));
  AOI22XL g2763(.A0 (n_52), .A1 (\mem[0] [0]), .B0 (n_51), .B1
       (\mem[7] [0]), .Y (n_77));
  AOI22XL g2764(.A0 (n_40), .A1 (\mem[2] [0]), .B0 (n_43), .B1
       (\mem[1] [0]), .Y (n_76));
  AOI22XL g2765(.A0 (n_42), .A1 (\mem[14] [0]), .B0 (n_41), .B1
       (\mem[15] [0]), .Y (n_75));
  AOI22XL g2766(.A0 (n_37), .A1 (\mem[10] [0]), .B0 (n_48), .B1
       (\mem[11] [0]), .Y (n_74));
  AOI22XL g2767(.A0 (n_50), .A1 (\mem[6] [4]), .B0 (n_51), .B1
       (\mem[7] [4]), .Y (n_73));
  AOI22XL g2768(.A0 (n_39), .A1 (\mem[12] [0]), .B0 (n_45), .B1
       (\mem[13] [0]), .Y (n_72));
  AOI22XL g2769(.A0 (n_42), .A1 (\mem[14] [7]), .B0 (n_45), .B1
       (\mem[13] [7]), .Y (n_71));
  AOI22XL g2770(.A0 (n_46), .A1 (\mem[4] [4]), .B0 (n_38), .B1
       (\mem[5] [4]), .Y (n_70));
  AOI22XL g2771(.A0 (n_49), .A1 (\mem[8] [0]), .B0 (n_47), .B1
       (\mem[9] [0]), .Y (n_69));
  AOI22XL g2772(.A0 (n_42), .A1 (\mem[14] [6]), .B0 (n_41), .B1
       (\mem[15] [6]), .Y (n_68));
  AOI22XL g2773(.A0 (n_40), .A1 (\mem[2] [4]), .B0 (n_44), .B1
       (\mem[3] [4]), .Y (n_67));
  AOI22XL g2774(.A0 (n_37), .A1 (\mem[10] [6]), .B0 (n_48), .B1
       (\mem[11] [6]), .Y (n_66));
  AOI22XL g2775(.A0 (n_52), .A1 (\mem[0] [4]), .B0 (n_43), .B1
       (\mem[1] [4]), .Y (n_65));
  AOI22XL g2776(.A0 (n_49), .A1 (\mem[8] [7]), .B0 (n_41), .B1
       (DFT_sdo), .Y (n_64));
  AOI22XL g2777(.A0 (n_46), .A1 (\mem[4] [7]), .B0 (n_38), .B1
       (\mem[5] [7]), .Y (n_63));
  AOI22XL g2778(.A0 (n_46), .A1 (\mem[4] [3]), .B0 (n_44), .B1
       (\mem[3] [3]), .Y (n_62));
  AOI22XL g2779(.A0 (n_40), .A1 (\mem[2] [3]), .B0 (n_43), .B1
       (\mem[1] [3]), .Y (n_61));
  AOI22XL g2780(.A0 (n_39), .A1 (\mem[12] [6]), .B0 (n_45), .B1
       (\mem[13] [6]), .Y (n_60));
  AOI22XL g2781(.A0 (n_50), .A1 (\mem[6] [3]), .B0 (n_38), .B1
       (\mem[5] [3]), .Y (n_59));
  AOI22XL g2782(.A0 (n_49), .A1 (\mem[8] [6]), .B0 (n_47), .B1
       (\mem[9] [6]), .Y (n_58));
  AOI22XL g2783(.A0 (n_50), .A1 (\mem[6] [7]), .B0 (n_51), .B1
       (\mem[7] [7]), .Y (n_57));
  AOI22XL g2784(.A0 (n_42), .A1 (\mem[14] [3]), .B0 (n_41), .B1
       (\mem[15] [3]), .Y (n_56));
  AOI22XL g2785(.A0 (n_40), .A1 (\mem[2] [5]), .B0 (n_51), .B1
       (\mem[7] [5]), .Y (n_55));
  AOI22XL g2786(.A0 (n_39), .A1 (\mem[12] [3]), .B0 (n_45), .B1
       (\mem[13] [3]), .Y (n_54));
  AOI22XL g2787(.A0 (n_52), .A1 (\mem[0] [6]), .B0 (n_51), .B1
       (\mem[7] [6]), .Y (n_53));
  AND2X1 g2788(.A (n_36), .B (n_30), .Y (n_52));
  NOR2XL g2789(.A (n_34), .B (n_32), .Y (n_51));
  NOR2BXL g2790(.AN (n_30), .B (n_34), .Y (n_50));
  NOR2BXL g2791(.AN (n_36), .B (n_35), .Y (n_49));
  NOR2XL g2792(.A (n_31), .B (n_29), .Y (n_48));
  NOR2BXL g2793(.AN (n_36), .B (n_29), .Y (n_47));
  NOR2BXL g2794(.AN (n_30), .B (n_33), .Y (n_46));
  NOR2XL g2795(.A (n_33), .B (n_29), .Y (n_45));
  NOR2XL g2796(.A (n_31), .B (n_32), .Y (n_44));
  NOR2BXL g2797(.AN (n_36), .B (n_32), .Y (n_43));
  NOR2XL g2798(.A (n_34), .B (n_35), .Y (n_42));
  NOR2XL g2799(.A (n_34), .B (n_29), .Y (n_41));
  NOR2BXL g2800(.AN (n_30), .B (n_31), .Y (n_40));
  NOR2XL g2801(.A (n_33), .B (n_35), .Y (n_39));
  NOR2XL g2802(.A (n_33), .B (n_32), .Y (n_38));
  NOR2XL g2803(.A (n_31), .B (n_35), .Y (n_37));
  NOR2XL g2804(.A (raddr[2]), .B (raddr[1]), .Y (n_36));
  NAND2BXL g2805(.AN (raddr[0]), .B (raddr[3]), .Y (n_35));
  NAND2XL g2806(.A (raddr[2]), .B (raddr[1]), .Y (n_34));
  NAND2BXL g2807(.AN (raddr[1]), .B (raddr[2]), .Y (n_33));
  NAND2BXL g2808(.AN (raddr[3]), .B (raddr[0]), .Y (n_32));
  NAND2BXL g2809(.AN (raddr[2]), .B (raddr[1]), .Y (n_31));
  NOR2XL g2810(.A (raddr[3]), .B (raddr[0]), .Y (n_30));
  NAND2XL g2811(.A (raddr[3]), .B (raddr[0]), .Y (n_29));
  SMDFFHQX1 \mem_reg[0][0] (.CK (wclk), .D0 (wdata[0]), .D1 (\mem[0]
       [0]), .S0 (n_28), .SI (DFT_sdi), .SE (DFT_sen), .Q (\mem[0]
       [0]));
  SMDFFHQX1 \mem_reg[0][1] (.CK (wclk), .D0 (wdata[1]), .D1 (\mem[0]
       [1]), .S0 (n_28), .SI (\mem[0] [0]), .SE (DFT_sen), .Q
       (\mem[0] [1]));
  SMDFFHQX1 \mem_reg[0][2] (.CK (wclk), .D0 (wdata[2]), .D1 (\mem[0]
       [2]), .S0 (n_28), .SI (\mem[0] [1]), .SE (DFT_sen), .Q
       (\mem[0] [2]));
  SMDFFHQX1 \mem_reg[0][3] (.CK (wclk), .D0 (wdata[3]), .D1 (\mem[0]
       [3]), .S0 (n_28), .SI (\mem[0] [2]), .SE (DFT_sen), .Q
       (\mem[0] [3]));
  SMDFFHQX1 \mem_reg[0][4] (.CK (wclk), .D0 (wdata[4]), .D1 (\mem[0]
       [4]), .S0 (n_28), .SI (\mem[0] [3]), .SE (DFT_sen), .Q
       (\mem[0] [4]));
  SMDFFHQX1 \mem_reg[0][5] (.CK (wclk), .D0 (wdata[5]), .D1 (\mem[0]
       [5]), .S0 (n_28), .SI (\mem[0] [4]), .SE (DFT_sen), .Q
       (\mem[0] [5]));
  SMDFFHQX1 \mem_reg[0][6] (.CK (wclk), .D0 (wdata[6]), .D1 (\mem[0]
       [6]), .S0 (n_28), .SI (\mem[0] [5]), .SE (DFT_sen), .Q
       (\mem[0] [6]));
  SMDFFHQX1 \mem_reg[0][7] (.CK (wclk), .D0 (wdata[7]), .D1 (\mem[0]
       [7]), .S0 (n_28), .SI (\mem[0] [6]), .SE (DFT_sen), .Q
       (\mem[0] [7]));
  SMDFFHQX1 \mem_reg[1][0] (.CK (wclk), .D0 (wdata[0]), .D1 (\mem[1]
       [0]), .S0 (n_19), .SI (\mem[0] [7]), .SE (DFT_sen), .Q
       (\mem[1] [0]));
  SMDFFHQX1 \mem_reg[1][1] (.CK (wclk), .D0 (wdata[1]), .D1 (\mem[1]
       [1]), .S0 (n_19), .SI (\mem[1] [0]), .SE (DFT_sen), .Q
       (\mem[1] [1]));
  SMDFFHQX1 \mem_reg[1][2] (.CK (wclk), .D0 (wdata[2]), .D1 (\mem[1]
       [2]), .S0 (n_19), .SI (\mem[1] [1]), .SE (DFT_sen), .Q
       (\mem[1] [2]));
  SMDFFHQX1 \mem_reg[1][3] (.CK (wclk), .D0 (wdata[3]), .D1 (\mem[1]
       [3]), .S0 (n_19), .SI (\mem[1] [2]), .SE (DFT_sen), .Q
       (\mem[1] [3]));
  SMDFFHQX1 \mem_reg[1][4] (.CK (wclk), .D0 (wdata[4]), .D1 (\mem[1]
       [4]), .S0 (n_19), .SI (\mem[1] [3]), .SE (DFT_sen), .Q
       (\mem[1] [4]));
  SMDFFHQX1 \mem_reg[1][5] (.CK (wclk), .D0 (wdata[5]), .D1 (\mem[1]
       [5]), .S0 (n_19), .SI (\mem[1] [4]), .SE (DFT_sen), .Q
       (\mem[1] [5]));
  SMDFFHQX1 \mem_reg[1][6] (.CK (wclk), .D0 (wdata[6]), .D1 (\mem[1]
       [6]), .S0 (n_19), .SI (\mem[1] [5]), .SE (DFT_sen), .Q
       (\mem[1] [6]));
  SMDFFHQX1 \mem_reg[1][7] (.CK (wclk), .D0 (wdata[7]), .D1 (\mem[1]
       [7]), .S0 (n_19), .SI (\mem[1] [6]), .SE (DFT_sen), .Q
       (\mem[1] [7]));
  SMDFFHQX1 \mem_reg[2][0] (.CK (wclk), .D0 (wdata[0]), .D1 (\mem[2]
       [0]), .S0 (n_13), .SI (\mem[1] [7]), .SE (DFT_sen), .Q
       (\mem[2] [0]));
  SMDFFHQX1 \mem_reg[2][1] (.CK (wclk), .D0 (wdata[1]), .D1 (\mem[2]
       [1]), .S0 (n_13), .SI (\mem[2] [0]), .SE (DFT_sen), .Q
       (\mem[2] [1]));
  SMDFFHQX1 \mem_reg[2][2] (.CK (wclk), .D0 (wdata[2]), .D1 (\mem[2]
       [2]), .S0 (n_13), .SI (\mem[2] [1]), .SE (DFT_sen), .Q
       (\mem[2] [2]));
  SMDFFHQX1 \mem_reg[2][3] (.CK (wclk), .D0 (wdata[3]), .D1 (\mem[2]
       [3]), .S0 (n_13), .SI (\mem[2] [2]), .SE (DFT_sen), .Q
       (\mem[2] [3]));
  SMDFFHQX1 \mem_reg[2][4] (.CK (wclk), .D0 (wdata[4]), .D1 (\mem[2]
       [4]), .S0 (n_13), .SI (\mem[2] [3]), .SE (DFT_sen), .Q
       (\mem[2] [4]));
  SMDFFHQX1 \mem_reg[2][5] (.CK (wclk), .D0 (wdata[5]), .D1 (\mem[2]
       [5]), .S0 (n_13), .SI (\mem[2] [4]), .SE (DFT_sen), .Q
       (\mem[2] [5]));
  SMDFFHQX1 \mem_reg[2][6] (.CK (wclk), .D0 (wdata[6]), .D1 (\mem[2]
       [6]), .S0 (n_13), .SI (\mem[2] [5]), .SE (DFT_sen), .Q
       (\mem[2] [6]));
  SMDFFHQX1 \mem_reg[2][7] (.CK (wclk), .D0 (wdata[7]), .D1 (\mem[2]
       [7]), .S0 (n_13), .SI (\mem[2] [6]), .SE (DFT_sen), .Q
       (\mem[2] [7]));
  SMDFFHQX1 \mem_reg[3][0] (.CK (wclk), .D0 (\mem[3] [0]), .D1
       (wdata[0]), .S0 (n_27), .SI (\mem[2] [7]), .SE (DFT_sen), .Q
       (\mem[3] [0]));
  SMDFFHQX1 \mem_reg[3][1] (.CK (wclk), .D0 (\mem[3] [1]), .D1
       (wdata[1]), .S0 (n_27), .SI (\mem[3] [0]), .SE (DFT_sen), .Q
       (\mem[3] [1]));
  SMDFFHQX1 \mem_reg[3][2] (.CK (wclk), .D0 (\mem[3] [2]), .D1
       (wdata[2]), .S0 (n_27), .SI (\mem[3] [1]), .SE (DFT_sen), .Q
       (\mem[3] [2]));
  SMDFFHQX1 \mem_reg[3][3] (.CK (wclk), .D0 (\mem[3] [3]), .D1
       (wdata[3]), .S0 (n_27), .SI (\mem[3] [2]), .SE (DFT_sen), .Q
       (\mem[3] [3]));
  SMDFFHQX1 \mem_reg[3][4] (.CK (wclk), .D0 (\mem[3] [4]), .D1
       (wdata[4]), .S0 (n_27), .SI (\mem[3] [3]), .SE (DFT_sen), .Q
       (\mem[3] [4]));
  SMDFFHQX1 \mem_reg[3][5] (.CK (wclk), .D0 (\mem[3] [5]), .D1
       (wdata[5]), .S0 (n_27), .SI (\mem[3] [4]), .SE (DFT_sen), .Q
       (\mem[3] [5]));
  SMDFFHQX1 \mem_reg[3][6] (.CK (wclk), .D0 (\mem[3] [6]), .D1
       (wdata[6]), .S0 (n_27), .SI (\mem[3] [5]), .SE (DFT_sen), .Q
       (\mem[3] [6]));
  SMDFFHQX1 \mem_reg[3][7] (.CK (wclk), .D0 (\mem[3] [7]), .D1
       (wdata[7]), .S0 (n_27), .SI (\mem[3] [6]), .SE (DFT_sen), .Q
       (\mem[3] [7]));
  SMDFFHQX1 \mem_reg[4][0] (.CK (wclk), .D0 (wdata[0]), .D1 (\mem[4]
       [0]), .S0 (n_18), .SI (\mem[3] [7]), .SE (DFT_sen), .Q
       (\mem[4] [0]));
  SMDFFHQX1 \mem_reg[4][1] (.CK (wclk), .D0 (wdata[1]), .D1 (\mem[4]
       [1]), .S0 (n_18), .SI (\mem[4] [0]), .SE (DFT_sen), .Q
       (\mem[4] [1]));
  SMDFFHQX1 \mem_reg[4][2] (.CK (wclk), .D0 (wdata[2]), .D1 (\mem[4]
       [2]), .S0 (n_18), .SI (\mem[4] [1]), .SE (DFT_sen), .Q
       (\mem[4] [2]));
  SMDFFHQX1 \mem_reg[4][3] (.CK (wclk), .D0 (wdata[3]), .D1 (\mem[4]
       [3]), .S0 (n_18), .SI (\mem[4] [2]), .SE (DFT_sen), .Q
       (\mem[4] [3]));
  SMDFFHQX1 \mem_reg[4][4] (.CK (wclk), .D0 (wdata[4]), .D1 (\mem[4]
       [4]), .S0 (n_18), .SI (\mem[4] [3]), .SE (DFT_sen), .Q
       (\mem[4] [4]));
  SMDFFHQX1 \mem_reg[4][5] (.CK (wclk), .D0 (wdata[5]), .D1 (\mem[4]
       [5]), .S0 (n_18), .SI (\mem[4] [4]), .SE (DFT_sen), .Q
       (\mem[4] [5]));
  SMDFFHQX1 \mem_reg[4][6] (.CK (wclk), .D0 (wdata[6]), .D1 (\mem[4]
       [6]), .S0 (n_18), .SI (\mem[4] [5]), .SE (DFT_sen), .Q
       (\mem[4] [6]));
  SMDFFHQX1 \mem_reg[4][7] (.CK (wclk), .D0 (wdata[7]), .D1 (\mem[4]
       [7]), .S0 (n_18), .SI (\mem[4] [6]), .SE (DFT_sen), .Q
       (\mem[4] [7]));
  SMDFFHQX1 \mem_reg[5][0] (.CK (wclk), .D0 (wdata[0]), .D1 (\mem[5]
       [0]), .S0 (n_16), .SI (\mem[4] [7]), .SE (DFT_sen), .Q
       (\mem[5] [0]));
  SMDFFHQX1 \mem_reg[5][1] (.CK (wclk), .D0 (wdata[1]), .D1 (\mem[5]
       [1]), .S0 (n_16), .SI (\mem[5] [0]), .SE (DFT_sen), .Q
       (\mem[5] [1]));
  SMDFFHQX1 \mem_reg[5][2] (.CK (wclk), .D0 (wdata[2]), .D1 (\mem[5]
       [2]), .S0 (n_16), .SI (\mem[5] [1]), .SE (DFT_sen), .Q
       (\mem[5] [2]));
  SMDFFHQX1 \mem_reg[5][3] (.CK (wclk), .D0 (wdata[3]), .D1 (\mem[5]
       [3]), .S0 (n_16), .SI (\mem[5] [2]), .SE (DFT_sen), .Q
       (\mem[5] [3]));
  SMDFFHQX1 \mem_reg[5][4] (.CK (wclk), .D0 (wdata[4]), .D1 (\mem[5]
       [4]), .S0 (n_16), .SI (\mem[5] [3]), .SE (DFT_sen), .Q
       (\mem[5] [4]));
  SMDFFHQX1 \mem_reg[5][5] (.CK (wclk), .D0 (wdata[5]), .D1 (\mem[5]
       [5]), .S0 (n_16), .SI (\mem[5] [4]), .SE (DFT_sen), .Q
       (\mem[5] [5]));
  SMDFFHQX1 \mem_reg[5][6] (.CK (wclk), .D0 (wdata[6]), .D1 (\mem[5]
       [6]), .S0 (n_16), .SI (\mem[5] [5]), .SE (DFT_sen), .Q
       (\mem[5] [6]));
  SMDFFHQX1 \mem_reg[5][7] (.CK (wclk), .D0 (wdata[7]), .D1 (\mem[5]
       [7]), .S0 (n_16), .SI (\mem[5] [6]), .SE (DFT_sen), .Q
       (\mem[5] [7]));
  SMDFFHQX1 \mem_reg[6][0] (.CK (wclk), .D0 (wdata[0]), .D1 (\mem[6]
       [0]), .S0 (n_21), .SI (\mem[5] [7]), .SE (DFT_sen), .Q
       (\mem[6] [0]));
  SMDFFHQX1 \mem_reg[6][1] (.CK (wclk), .D0 (wdata[1]), .D1 (\mem[6]
       [1]), .S0 (n_21), .SI (\mem[6] [0]), .SE (DFT_sen), .Q
       (\mem[6] [1]));
  SMDFFHQX1 \mem_reg[6][2] (.CK (wclk), .D0 (wdata[2]), .D1 (\mem[6]
       [2]), .S0 (n_21), .SI (\mem[6] [1]), .SE (DFT_sen), .Q
       (\mem[6] [2]));
  SMDFFHQX1 \mem_reg[6][3] (.CK (wclk), .D0 (wdata[3]), .D1 (\mem[6]
       [3]), .S0 (n_21), .SI (\mem[6] [2]), .SE (DFT_sen), .Q
       (\mem[6] [3]));
  SMDFFHQX1 \mem_reg[6][4] (.CK (wclk), .D0 (wdata[4]), .D1 (\mem[6]
       [4]), .S0 (n_21), .SI (\mem[6] [3]), .SE (DFT_sen), .Q
       (\mem[6] [4]));
  SMDFFHQX1 \mem_reg[6][5] (.CK (wclk), .D0 (wdata[5]), .D1 (\mem[6]
       [5]), .S0 (n_21), .SI (\mem[6] [4]), .SE (DFT_sen), .Q
       (\mem[6] [5]));
  SMDFFHQX1 \mem_reg[6][6] (.CK (wclk), .D0 (wdata[6]), .D1 (\mem[6]
       [6]), .S0 (n_21), .SI (\mem[6] [5]), .SE (DFT_sen), .Q
       (\mem[6] [6]));
  SMDFFHQX1 \mem_reg[6][7] (.CK (wclk), .D0 (wdata[7]), .D1 (\mem[6]
       [7]), .S0 (n_21), .SI (\mem[6] [6]), .SE (DFT_sen), .Q
       (\mem[6] [7]));
  SMDFFHQX1 \mem_reg[7][0] (.CK (wclk), .D0 (wdata[0]), .D1 (\mem[7]
       [0]), .S0 (n_20), .SI (\mem[6] [7]), .SE (DFT_sen), .Q
       (\mem[7] [0]));
  SMDFFHQX1 \mem_reg[7][1] (.CK (wclk), .D0 (wdata[1]), .D1 (\mem[7]
       [1]), .S0 (n_20), .SI (\mem[7] [0]), .SE (DFT_sen), .Q
       (\mem[7] [1]));
  SMDFFHQX1 \mem_reg[7][2] (.CK (wclk), .D0 (wdata[2]), .D1 (\mem[7]
       [2]), .S0 (n_20), .SI (\mem[7] [1]), .SE (DFT_sen), .Q
       (\mem[7] [2]));
  SMDFFHQX1 \mem_reg[7][3] (.CK (wclk), .D0 (wdata[3]), .D1 (\mem[7]
       [3]), .S0 (n_20), .SI (\mem[7] [2]), .SE (DFT_sen), .Q
       (\mem[7] [3]));
  SMDFFHQX1 \mem_reg[7][4] (.CK (wclk), .D0 (wdata[4]), .D1 (\mem[7]
       [4]), .S0 (n_20), .SI (\mem[7] [3]), .SE (DFT_sen), .Q
       (\mem[7] [4]));
  SMDFFHQX1 \mem_reg[7][5] (.CK (wclk), .D0 (wdata[5]), .D1 (\mem[7]
       [5]), .S0 (n_20), .SI (\mem[7] [4]), .SE (DFT_sen), .Q
       (\mem[7] [5]));
  SMDFFHQX1 \mem_reg[7][6] (.CK (wclk), .D0 (wdata[6]), .D1 (\mem[7]
       [6]), .S0 (n_20), .SI (\mem[7] [5]), .SE (DFT_sen), .Q
       (\mem[7] [6]));
  SMDFFHQX1 \mem_reg[7][7] (.CK (wclk), .D0 (wdata[7]), .D1 (\mem[7]
       [7]), .S0 (n_20), .SI (\mem[7] [6]), .SE (DFT_sen), .Q
       (\mem[7] [7]));
  SMDFFHQX1 \mem_reg[8][0] (.CK (wclk), .D0 (wdata[0]), .D1 (\mem[8]
       [0]), .S0 (n_15), .SI (\mem[7] [7]), .SE (DFT_sen), .Q
       (\mem[8] [0]));
  SMDFFHQX1 \mem_reg[8][1] (.CK (wclk), .D0 (wdata[1]), .D1 (\mem[8]
       [1]), .S0 (n_15), .SI (\mem[8] [0]), .SE (DFT_sen), .Q
       (\mem[8] [1]));
  SMDFFHQX1 \mem_reg[8][2] (.CK (wclk), .D0 (wdata[2]), .D1 (\mem[8]
       [2]), .S0 (n_15), .SI (\mem[8] [1]), .SE (DFT_sen), .Q
       (\mem[8] [2]));
  SMDFFHQX1 \mem_reg[8][3] (.CK (wclk), .D0 (wdata[3]), .D1 (\mem[8]
       [3]), .S0 (n_15), .SI (\mem[8] [2]), .SE (DFT_sen), .Q
       (\mem[8] [3]));
  SMDFFHQX1 \mem_reg[8][4] (.CK (wclk), .D0 (wdata[4]), .D1 (\mem[8]
       [4]), .S0 (n_15), .SI (\mem[8] [3]), .SE (DFT_sen), .Q
       (\mem[8] [4]));
  SMDFFHQX1 \mem_reg[8][5] (.CK (wclk), .D0 (wdata[5]), .D1 (\mem[8]
       [5]), .S0 (n_15), .SI (\mem[8] [4]), .SE (DFT_sen), .Q
       (\mem[8] [5]));
  SMDFFHQX1 \mem_reg[8][6] (.CK (wclk), .D0 (wdata[6]), .D1 (\mem[8]
       [6]), .S0 (n_15), .SI (\mem[8] [5]), .SE (DFT_sen), .Q
       (\mem[8] [6]));
  SMDFFHQX1 \mem_reg[8][7] (.CK (wclk), .D0 (wdata[7]), .D1 (\mem[8]
       [7]), .S0 (n_15), .SI (\mem[8] [6]), .SE (DFT_sen), .Q
       (\mem[8] [7]));
  SMDFFHQX1 \mem_reg[9][0] (.CK (wclk), .D0 (\mem[9] [0]), .D1
       (wdata[0]), .S0 (n_22), .SI (\mem[8] [7]), .SE (DFT_sen), .Q
       (\mem[9] [0]));
  SMDFFHQX1 \mem_reg[9][1] (.CK (wclk), .D0 (\mem[9] [1]), .D1
       (wdata[1]), .S0 (n_22), .SI (\mem[9] [0]), .SE (DFT_sen), .Q
       (\mem[9] [1]));
  SMDFFHQX1 \mem_reg[9][2] (.CK (wclk), .D0 (\mem[9] [2]), .D1
       (wdata[2]), .S0 (n_22), .SI (\mem[9] [1]), .SE (DFT_sen), .Q
       (\mem[9] [2]));
  SMDFFHQX1 \mem_reg[9][3] (.CK (wclk), .D0 (\mem[9] [3]), .D1
       (wdata[3]), .S0 (n_22), .SI (\mem[9] [2]), .SE (DFT_sen), .Q
       (\mem[9] [3]));
  SMDFFHQX1 \mem_reg[9][4] (.CK (wclk), .D0 (\mem[9] [4]), .D1
       (wdata[4]), .S0 (n_22), .SI (\mem[9] [3]), .SE (DFT_sen), .Q
       (\mem[9] [4]));
  SMDFFHQX1 \mem_reg[9][5] (.CK (wclk), .D0 (\mem[9] [5]), .D1
       (wdata[5]), .S0 (n_22), .SI (\mem[9] [4]), .SE (DFT_sen), .Q
       (\mem[9] [5]));
  SMDFFHQX1 \mem_reg[9][6] (.CK (wclk), .D0 (\mem[9] [6]), .D1
       (wdata[6]), .S0 (n_22), .SI (\mem[9] [5]), .SE (DFT_sen), .Q
       (\mem[9] [6]));
  SMDFFHQX1 \mem_reg[9][7] (.CK (wclk), .D0 (\mem[9] [7]), .D1
       (wdata[7]), .S0 (n_22), .SI (\mem[9] [6]), .SE (DFT_sen), .Q
       (\mem[9] [7]));
  SMDFFHQX1 \mem_reg[10][0] (.CK (wclk), .D0 (\mem[10] [0]), .D1
       (wdata[0]), .S0 (n_17), .SI (\mem[9] [7]), .SE (DFT_sen), .Q
       (\mem[10] [0]));
  SMDFFHQX1 \mem_reg[10][1] (.CK (wclk), .D0 (\mem[10] [1]), .D1
       (wdata[1]), .S0 (n_17), .SI (\mem[10] [0]), .SE (DFT_sen), .Q
       (\mem[10] [1]));
  SMDFFHQX1 \mem_reg[10][2] (.CK (wclk), .D0 (\mem[10] [2]), .D1
       (wdata[2]), .S0 (n_17), .SI (\mem[10] [1]), .SE (DFT_sen), .Q
       (\mem[10] [2]));
  SMDFFHQX1 \mem_reg[10][3] (.CK (wclk), .D0 (\mem[10] [3]), .D1
       (wdata[3]), .S0 (n_17), .SI (\mem[10] [2]), .SE (DFT_sen), .Q
       (\mem[10] [3]));
  SMDFFHQX1 \mem_reg[10][4] (.CK (wclk), .D0 (\mem[10] [4]), .D1
       (wdata[4]), .S0 (n_17), .SI (\mem[10] [3]), .SE (DFT_sen), .Q
       (\mem[10] [4]));
  SMDFFHQX1 \mem_reg[10][5] (.CK (wclk), .D0 (\mem[10] [5]), .D1
       (wdata[5]), .S0 (n_17), .SI (\mem[10] [4]), .SE (DFT_sen), .Q
       (\mem[10] [5]));
  SMDFFHQX1 \mem_reg[10][6] (.CK (wclk), .D0 (\mem[10] [6]), .D1
       (wdata[6]), .S0 (n_17), .SI (\mem[10] [5]), .SE (DFT_sen), .Q
       (\mem[10] [6]));
  SMDFFHQX1 \mem_reg[10][7] (.CK (wclk), .D0 (\mem[10] [7]), .D1
       (wdata[7]), .S0 (n_17), .SI (\mem[10] [6]), .SE (DFT_sen), .Q
       (\mem[10] [7]));
  SMDFFHQX1 \mem_reg[11][0] (.CK (wclk), .D0 (\mem[11] [0]), .D1
       (wdata[0]), .S0 (n_24), .SI (\mem[10] [7]), .SE (DFT_sen), .Q
       (\mem[11] [0]));
  SMDFFHQX1 \mem_reg[11][1] (.CK (wclk), .D0 (\mem[11] [1]), .D1
       (wdata[1]), .S0 (n_24), .SI (\mem[11] [0]), .SE (DFT_sen), .Q
       (\mem[11] [1]));
  SMDFFHQX1 \mem_reg[11][2] (.CK (wclk), .D0 (\mem[11] [2]), .D1
       (wdata[2]), .S0 (n_24), .SI (\mem[11] [1]), .SE (DFT_sen), .Q
       (\mem[11] [2]));
  SMDFFHQX1 \mem_reg[11][3] (.CK (wclk), .D0 (\mem[11] [3]), .D1
       (wdata[3]), .S0 (n_24), .SI (\mem[11] [2]), .SE (DFT_sen), .Q
       (\mem[11] [3]));
  SMDFFHQX1 \mem_reg[11][4] (.CK (wclk), .D0 (\mem[11] [4]), .D1
       (wdata[4]), .S0 (n_24), .SI (\mem[11] [3]), .SE (DFT_sen), .Q
       (\mem[11] [4]));
  SMDFFHQX1 \mem_reg[11][5] (.CK (wclk), .D0 (\mem[11] [5]), .D1
       (wdata[5]), .S0 (n_24), .SI (\mem[11] [4]), .SE (DFT_sen), .Q
       (\mem[11] [5]));
  SMDFFHQX1 \mem_reg[11][6] (.CK (wclk), .D0 (\mem[11] [6]), .D1
       (wdata[6]), .S0 (n_24), .SI (\mem[11] [5]), .SE (DFT_sen), .Q
       (\mem[11] [6]));
  SMDFFHQX1 \mem_reg[11][7] (.CK (wclk), .D0 (\mem[11] [7]), .D1
       (wdata[7]), .S0 (n_24), .SI (\mem[11] [6]), .SE (DFT_sen), .Q
       (\mem[11] [7]));
  SMDFFHQX1 \mem_reg[12][0] (.CK (wclk), .D0 (wdata[0]), .D1
       (\mem[12] [0]), .S0 (n_26), .SI (\mem[11] [7]), .SE (DFT_sen),
       .Q (\mem[12] [0]));
  SMDFFHQX1 \mem_reg[12][1] (.CK (wclk), .D0 (wdata[1]), .D1
       (\mem[12] [1]), .S0 (n_26), .SI (\mem[12] [0]), .SE (DFT_sen),
       .Q (\mem[12] [1]));
  SMDFFHQX1 \mem_reg[12][2] (.CK (wclk), .D0 (wdata[2]), .D1
       (\mem[12] [2]), .S0 (n_26), .SI (\mem[12] [1]), .SE (DFT_sen),
       .Q (\mem[12] [2]));
  SMDFFHQX1 \mem_reg[12][3] (.CK (wclk), .D0 (wdata[3]), .D1
       (\mem[12] [3]), .S0 (n_26), .SI (\mem[12] [2]), .SE (DFT_sen),
       .Q (\mem[12] [3]));
  SMDFFHQX1 \mem_reg[12][4] (.CK (wclk), .D0 (wdata[4]), .D1
       (\mem[12] [4]), .S0 (n_26), .SI (\mem[12] [3]), .SE (DFT_sen),
       .Q (\mem[12] [4]));
  SMDFFHQX1 \mem_reg[12][5] (.CK (wclk), .D0 (wdata[5]), .D1
       (\mem[12] [5]), .S0 (n_26), .SI (\mem[12] [4]), .SE (DFT_sen),
       .Q (\mem[12] [5]));
  SMDFFHQX1 \mem_reg[12][6] (.CK (wclk), .D0 (wdata[6]), .D1
       (\mem[12] [6]), .S0 (n_26), .SI (\mem[12] [5]), .SE (DFT_sen),
       .Q (\mem[12] [6]));
  SMDFFHQX1 \mem_reg[12][7] (.CK (wclk), .D0 (wdata[7]), .D1
       (\mem[12] [7]), .S0 (n_26), .SI (\mem[12] [6]), .SE (DFT_sen),
       .Q (\mem[12] [7]));
  SMDFFHQX1 \mem_reg[13][0] (.CK (wclk), .D0 (wdata[0]), .D1
       (\mem[13] [0]), .S0 (n_14), .SI (\mem[12] [7]), .SE (DFT_sen),
       .Q (\mem[13] [0]));
  SMDFFHQX1 \mem_reg[13][1] (.CK (wclk), .D0 (wdata[1]), .D1
       (\mem[13] [1]), .S0 (n_14), .SI (\mem[13] [0]), .SE (DFT_sen),
       .Q (\mem[13] [1]));
  SMDFFHQX1 \mem_reg[13][2] (.CK (wclk), .D0 (wdata[2]), .D1
       (\mem[13] [2]), .S0 (n_14), .SI (\mem[13] [1]), .SE (DFT_sen),
       .Q (\mem[13] [2]));
  SMDFFHQX1 \mem_reg[13][3] (.CK (wclk), .D0 (wdata[3]), .D1
       (\mem[13] [3]), .S0 (n_14), .SI (\mem[13] [2]), .SE (DFT_sen),
       .Q (\mem[13] [3]));
  SMDFFHQX1 \mem_reg[13][4] (.CK (wclk), .D0 (wdata[4]), .D1
       (\mem[13] [4]), .S0 (n_14), .SI (\mem[13] [3]), .SE (DFT_sen),
       .Q (\mem[13] [4]));
  SMDFFHQX1 \mem_reg[13][5] (.CK (wclk), .D0 (wdata[5]), .D1
       (\mem[13] [5]), .S0 (n_14), .SI (\mem[13] [4]), .SE (DFT_sen),
       .Q (\mem[13] [5]));
  SMDFFHQX1 \mem_reg[13][6] (.CK (wclk), .D0 (wdata[6]), .D1
       (\mem[13] [6]), .S0 (n_14), .SI (\mem[13] [5]), .SE (DFT_sen),
       .Q (\mem[13] [6]));
  SMDFFHQX1 \mem_reg[13][7] (.CK (wclk), .D0 (wdata[7]), .D1
       (\mem[13] [7]), .S0 (n_14), .SI (\mem[13] [6]), .SE (DFT_sen),
       .Q (\mem[13] [7]));
  SMDFFHQX1 \mem_reg[14][0] (.CK (wclk), .D0 (wdata[0]), .D1
       (\mem[14] [0]), .S0 (n_25), .SI (\mem[13] [7]), .SE (DFT_sen),
       .Q (\mem[14] [0]));
  SMDFFHQX1 \mem_reg[14][1] (.CK (wclk), .D0 (wdata[1]), .D1
       (\mem[14] [1]), .S0 (n_25), .SI (\mem[14] [0]), .SE (DFT_sen),
       .Q (\mem[14] [1]));
  SMDFFHQX1 \mem_reg[14][2] (.CK (wclk), .D0 (wdata[2]), .D1
       (\mem[14] [2]), .S0 (n_25), .SI (\mem[14] [1]), .SE (DFT_sen),
       .Q (\mem[14] [2]));
  SMDFFHQX1 \mem_reg[14][3] (.CK (wclk), .D0 (wdata[3]), .D1
       (\mem[14] [3]), .S0 (n_25), .SI (\mem[14] [2]), .SE (DFT_sen),
       .Q (\mem[14] [3]));
  SMDFFHQX1 \mem_reg[14][4] (.CK (wclk), .D0 (wdata[4]), .D1
       (\mem[14] [4]), .S0 (n_25), .SI (\mem[14] [3]), .SE (DFT_sen),
       .Q (\mem[14] [4]));
  SMDFFHQX1 \mem_reg[14][5] (.CK (wclk), .D0 (wdata[5]), .D1
       (\mem[14] [5]), .S0 (n_25), .SI (\mem[14] [4]), .SE (DFT_sen),
       .Q (\mem[14] [5]));
  SMDFFHQX1 \mem_reg[14][6] (.CK (wclk), .D0 (wdata[6]), .D1
       (\mem[14] [6]), .S0 (n_25), .SI (\mem[14] [5]), .SE (DFT_sen),
       .Q (\mem[14] [6]));
  SMDFFHQX1 \mem_reg[14][7] (.CK (wclk), .D0 (wdata[7]), .D1
       (\mem[14] [7]), .S0 (n_25), .SI (\mem[14] [6]), .SE (DFT_sen),
       .Q (\mem[14] [7]));
  SMDFFHQX1 \mem_reg[15][0] (.CK (wclk), .D0 (\mem[15] [0]), .D1
       (wdata[0]), .S0 (n_23), .SI (\mem[14] [7]), .SE (DFT_sen), .Q
       (\mem[15] [0]));
  SMDFFHQX1 \mem_reg[15][1] (.CK (wclk), .D0 (\mem[15] [1]), .D1
       (wdata[1]), .S0 (n_23), .SI (\mem[15] [0]), .SE (DFT_sen), .Q
       (\mem[15] [1]));
  SMDFFHQX1 \mem_reg[15][2] (.CK (wclk), .D0 (\mem[15] [2]), .D1
       (wdata[2]), .S0 (n_23), .SI (\mem[15] [1]), .SE (DFT_sen), .Q
       (\mem[15] [2]));
  SMDFFHQX1 \mem_reg[15][3] (.CK (wclk), .D0 (\mem[15] [3]), .D1
       (wdata[3]), .S0 (n_23), .SI (\mem[15] [2]), .SE (DFT_sen), .Q
       (\mem[15] [3]));
  SMDFFHQX1 \mem_reg[15][4] (.CK (wclk), .D0 (\mem[15] [4]), .D1
       (wdata[4]), .S0 (n_23), .SI (\mem[15] [3]), .SE (DFT_sen), .Q
       (\mem[15] [4]));
  SMDFFHQX1 \mem_reg[15][5] (.CK (wclk), .D0 (\mem[15] [5]), .D1
       (wdata[5]), .S0 (n_23), .SI (\mem[15] [4]), .SE (DFT_sen), .Q
       (\mem[15] [5]));
  SMDFFHQX1 \mem_reg[15][6] (.CK (wclk), .D0 (\mem[15] [6]), .D1
       (wdata[6]), .S0 (n_23), .SI (\mem[15] [5]), .SE (DFT_sen), .Q
       (\mem[15] [6]));
  SMDFFHQX1 \mem_reg[15][7] (.CK (wclk), .D0 (DFT_sdo), .D1 (wdata[7]),
       .S0 (n_23), .SI (\mem[15] [6]), .SE (DFT_sen), .Q (DFT_sdo));
  NAND2XL g827(.A (n_2), .B (n_12), .Y (n_28));
  NOR2XL g828(.A (n_0), .B (n_11), .Y (n_27));
  NAND2XL g829(.A (n_5), .B (n_9), .Y (n_26));
  NAND2BXL g830(.AN (n_4), .B (n_9), .Y (n_25));
  NOR2XL g831(.A (n_4), .B (n_11), .Y (n_24));
  NOR2XL g832(.A (n_4), .B (n_10), .Y (n_23));
  NOR2XL g833(.A (n_6), .B (n_11), .Y (n_22));
  NAND2XL g834(.A (n_1), .B (n_9), .Y (n_21));
  OR2X1 g835(.A (n_0), .B (n_10), .Y (n_20));
  NAND2BXL g836(.AN (n_11), .B (n_2), .Y (n_19));
  NAND2XL g837(.A (n_2), .B (n_9), .Y (n_18));
  NOR2BXL g838(.AN (n_12), .B (n_4), .Y (n_17));
  NAND2BXL g839(.AN (n_10), .B (n_2), .Y (n_16));
  NAND2XL g840(.A (n_5), .B (n_12), .Y (n_15));
  OR2X1 g841(.A (n_6), .B (n_10), .Y (n_14));
  NAND2XL g842(.A (n_1), .B (n_12), .Y (n_13));
  NOR2BXL g843(.AN (n_7), .B (waddr[0]), .Y (n_12));
  NAND2XL g844(.A (n_7), .B (waddr[0]), .Y (n_11));
  NAND2BXL g845(.AN (n_8), .B (waddr[0]), .Y (n_10));
  NOR2XL g846(.A (n_8), .B (waddr[0]), .Y (n_9));
  NAND2XL g847(.A (waddr[2]), .B (n_3), .Y (n_8));
  NOR2BXL g848(.AN (n_3), .B (waddr[2]), .Y (n_7));
  CLKINVX1 g849(.A (n_6), .Y (n_5));
  NAND2BXL g850(.AN (waddr[1]), .B (waddr[3]), .Y (n_6));
  NAND2XL g851(.A (waddr[3]), .B (waddr[1]), .Y (n_4));
  CLKINVX1 g852(.A (n_1), .Y (n_0));
  NOR2BXL g853(.AN (wclk_en), .B (wfull), .Y (n_3));
  NOR2XL g854(.A (waddr[3]), .B (waddr[1]), .Y (n_2));
  NOR2BXL g855(.AN (waddr[1]), .B (waddr[3]), .Y (n_1));
endmodule

module rptr_empty_ADDR_SIZE4(rempty, raddr, rptr, rq2_wptr, rinc, rclk,
     rrst_n, DFT_sdi, DFT_sen);
  input [4:0] rq2_wptr;
  input rinc, rclk, rrst_n, DFT_sdi, DFT_sen;
  output rempty;
  output [3:0] raddr;
  output [4:0] rptr;
  wire [4:0] rq2_wptr;
  wire rinc, rclk, rrst_n, DFT_sdi, DFT_sen;
  wire rempty;
  wire [3:0] raddr;
  wire [4:0] rptr;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_21, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_40;
  CLKXOR2X1 g203(.A (rptr[0]), .B (raddr[1]), .Y (raddr[0]));
  CLKXOR2X1 g204(.A (rptr[1]), .B (raddr[2]), .Y (raddr[1]));
  AND2X8 g205(.A (n_29), .B (n_30), .Y (rempty));
  CLKXOR2X1 g206(.A (rptr[2]), .B (raddr[3]), .Y (raddr[2]));
  NOR4XL g207(.A (n_27), .B (n_25), .C (n_26), .D (n_28), .Y (n_30));
  OAI21XL g208(.A0 (rptr[4]), .A1 (rq2_wptr[4]), .B0 (n_24), .Y (n_29));
  CLKXOR2X1 g209(.A (rq2_wptr[2]), .B (rptr[2]), .Y (n_28));
  CLKXOR2X1 g210(.A (rq2_wptr[3]), .B (rptr[3]), .Y (n_27));
  CLKXOR2X1 g211(.A (rq2_wptr[0]), .B (rptr[0]), .Y (n_26));
  CLKXOR2X1 g212(.A (rq2_wptr[1]), .B (rptr[1]), .Y (n_25));
  CLKXOR2X1 g213(.A (rptr[4]), .B (rptr[3]), .Y (raddr[3]));
  NAND2XL g214(.A (rptr[4]), .B (rq2_wptr[4]), .Y (n_24));
  SDFFRHQX1 \rptr_reg[3] (.RN (rrst_n), .CK (rclk), .D (n_40), .SI
       (rptr[2]), .SE (DFT_sen), .Q (rptr[3]));
  SDFFRHQX1 \rptr_reg[2] (.RN (rrst_n), .CK (rclk), .D (n_21), .SI
       (rptr[1]), .SE (DFT_sen), .Q (rptr[2]));
  SDFFRHQX1 \rptr_reg[4] (.RN (rrst_n), .CK (rclk), .D (n_19), .SI
       (rptr[3]), .SE (DFT_sen), .Q (rptr[4]));
  OAI21XL g138(.A0 (n_15), .A1 (n_10), .B0 (n_17), .Y (n_21));
  OAI21XL g140(.A0 (n_13), .A1 (rptr[4]), .B0 (n_18), .Y (n_19));
  NAND2XL g141(.A (rptr[4]), .B (n_13), .Y (n_18));
  NAND2XL g142(.A (n_10), .B (n_15), .Y (n_17));
  SDFFRHQX1 \rptr_reg[1] (.RN (rrst_n), .CK (rclk), .D (n_16), .SI
       (rptr[0]), .SE (DFT_sen), .Q (rptr[1]));
  OAI21XL g144(.A0 (n_10), .A1 (n_6), .B0 (n_12), .Y (n_16));
  OAI21XL g145(.A0 (n_8), .A1 (raddr[3]), .B0 (n_14), .Y (n_15));
  NAND2XL g146(.A (raddr[3]), .B (n_8), .Y (n_14));
  NAND2XL g147(.A (n_6), .B (n_10), .Y (n_12));
  NAND2BXL g148(.AN (n_8), .B (raddr[3]), .Y (n_13));
  SDFFRHQX1 \rptr_reg[0] (.RN (rrst_n), .CK (rclk), .D (n_11), .SI
       (DFT_sdi), .SE (DFT_sen), .Q (rptr[0]));
  OAI21XL g150(.A0 (n_6), .A1 (n_3), .B0 (n_7), .Y (n_11));
  AOI21XL g151(.A0 (raddr[2]), .A1 (n_4), .B0 (n_9), .Y (n_10));
  NOR2XL g152(.A (raddr[2]), .B (n_4), .Y (n_9));
  NAND2XL g153(.A (n_3), .B (n_6), .Y (n_7));
  NAND2BXL g154(.AN (n_4), .B (raddr[2]), .Y (n_8));
  OAI21XL g155(.A0 (n_1), .A1 (raddr[1]), .B0 (n_5), .Y (n_6));
  NAND2XL g156(.A (raddr[1]), .B (n_1), .Y (n_5));
  NAND2BXL g157(.AN (n_1), .B (raddr[1]), .Y (n_4));
  AOI21XL g158(.A0 (n_0), .A1 (raddr[0]), .B0 (n_2), .Y (n_3));
  NOR2XL g159(.A (n_0), .B (raddr[0]), .Y (n_2));
  NAND2BXL g160(.AN (n_0), .B (raddr[0]), .Y (n_1));
  NAND2BXL g161(.AN (rempty), .B (rinc), .Y (n_0));
  XOR2XL g2(.A (n_19), .B (n_15), .Y (n_40));
endmodule

module two_ff_sync_SIZE5(q2, din, clk, rst_n, DFT_sdi, DFT_sen);
  input [4:0] din;
  input clk, rst_n, DFT_sdi, DFT_sen;
  output [4:0] q2;
  wire [4:0] din;
  wire clk, rst_n, DFT_sdi, DFT_sen;
  wire [4:0] q2;
  wire [4:0] q1;
  SDFFRHQX1 \q2_reg[4] (.RN (rst_n), .CK (clk), .D (q1[4]), .SI
       (q2[3]), .SE (DFT_sen), .Q (q2[4]));
  SDFFRHQX1 \q2_reg[3] (.RN (rst_n), .CK (clk), .D (q1[3]), .SI
       (q2[2]), .SE (DFT_sen), .Q (q2[3]));
  SDFFRHQX1 \q2_reg[1] (.RN (rst_n), .CK (clk), .D (q1[1]), .SI
       (q2[0]), .SE (DFT_sen), .Q (q2[1]));
  SDFFRHQX1 \q2_reg[0] (.RN (rst_n), .CK (clk), .D (q1[0]), .SI
       (q1[4]), .SE (DFT_sen), .Q (q2[0]));
  SDFFRHQX1 \q2_reg[2] (.RN (rst_n), .CK (clk), .D (q1[2]), .SI
       (q2[1]), .SE (DFT_sen), .Q (q2[2]));
  SDFFRHQX1 \q1_reg[2] (.RN (rst_n), .CK (clk), .D (din[2]), .SI
       (q1[1]), .SE (DFT_sen), .Q (q1[2]));
  SDFFRHQX1 \q1_reg[3] (.RN (rst_n), .CK (clk), .D (din[3]), .SI
       (q1[2]), .SE (DFT_sen), .Q (q1[3]));
  SDFFRHQX1 \q1_reg[4] (.RN (rst_n), .CK (clk), .D (din[4]), .SI
       (q1[3]), .SE (DFT_sen), .Q (q1[4]));
  SDFFRHQX1 \q1_reg[1] (.RN (rst_n), .CK (clk), .D (din[1]), .SI
       (q1[0]), .SE (DFT_sen), .Q (q1[1]));
  SDFFRHQX1 \q1_reg[0] (.RN (rst_n), .CK (clk), .D (din[0]), .SI
       (DFT_sdi), .SE (DFT_sen), .Q (q1[0]));
endmodule

module two_ff_sync_SIZE5_25(q2, din, clk, rst_n, DFT_sdi, DFT_sen);
  input [4:0] din;
  input clk, rst_n, DFT_sdi, DFT_sen;
  output [4:0] q2;
  wire [4:0] din;
  wire clk, rst_n, DFT_sdi, DFT_sen;
  wire [4:0] q2;
  wire [4:0] q1;
  SDFFRHQX1 \q2_reg[4] (.RN (rst_n), .CK (clk), .D (q1[4]), .SI
       (q2[3]), .SE (DFT_sen), .Q (q2[4]));
  SDFFRHQX1 \q2_reg[3] (.RN (rst_n), .CK (clk), .D (q1[3]), .SI
       (q2[2]), .SE (DFT_sen), .Q (q2[3]));
  SDFFRHQX1 \q2_reg[1] (.RN (rst_n), .CK (clk), .D (q1[1]), .SI
       (q2[0]), .SE (DFT_sen), .Q (q2[1]));
  SDFFRHQX1 \q2_reg[0] (.RN (rst_n), .CK (clk), .D (q1[0]), .SI
       (q1[4]), .SE (DFT_sen), .Q (q2[0]));
  SDFFRHQX1 \q2_reg[2] (.RN (rst_n), .CK (clk), .D (q1[2]), .SI
       (q2[1]), .SE (DFT_sen), .Q (q2[2]));
  SDFFRHQX1 \q1_reg[2] (.RN (rst_n), .CK (clk), .D (din[2]), .SI
       (q1[1]), .SE (DFT_sen), .Q (q1[2]));
  SDFFRHQX1 \q1_reg[3] (.RN (rst_n), .CK (clk), .D (din[3]), .SI
       (q1[2]), .SE (DFT_sen), .Q (q1[3]));
  SDFFRHQX1 \q1_reg[4] (.RN (rst_n), .CK (clk), .D (din[4]), .SI
       (q1[3]), .SE (DFT_sen), .Q (q1[4]));
  SDFFRHQX1 \q1_reg[1] (.RN (rst_n), .CK (clk), .D (din[1]), .SI
       (q1[0]), .SE (DFT_sen), .Q (q1[1]));
  SDFFRHQX1 \q1_reg[0] (.RN (rst_n), .CK (clk), .D (din[0]), .SI
       (DFT_sdi), .SE (DFT_sen), .Q (q1[0]));
endmodule

module wptr_full_ADDR_SIZE4(wfull, waddr, wptr, wq2_rptr, winc, wclk,
     wrst_n, DFT_sen);
  input [4:0] wq2_rptr;
  input winc, wclk, wrst_n, DFT_sen;
  output wfull;
  output [3:0] waddr;
  output [4:0] wptr;
  wire [4:0] wq2_rptr;
  wire winc, wclk, wrst_n, DFT_sen;
  wire wfull;
  wire [3:0] waddr;
  wire [4:0] wptr;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_21, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_40;
  CLKXOR2X1 g201(.A (wptr[0]), .B (waddr[1]), .Y (waddr[0]));
  CLKXOR2X1 g202(.A (wptr[1]), .B (waddr[2]), .Y (waddr[1]));
  AND2X8 g203(.A (n_28), .B (n_30), .Y (wfull));
  CLKXOR2X1 g204(.A (wptr[2]), .B (waddr[3]), .Y (waddr[2]));
  NOR3XL g205(.A (n_27), .B (n_25), .C (n_29), .Y (n_30));
  OAI211XL g206(.A0 (wptr[3]), .A1 (wq2_rptr[3]), .B0 (n_24), .C0
       (n_26), .Y (n_29));
  CLKXOR2X1 g207(.A (wq2_rptr[4]), .B (wptr[4]), .Y (n_28));
  CLKXOR2X1 g208(.A (wq2_rptr[2]), .B (wptr[2]), .Y (n_27));
  XNOR2X1 g209(.A (wq2_rptr[0]), .B (wptr[0]), .Y (n_26));
  CLKXOR2X1 g210(.A (wq2_rptr[1]), .B (wptr[1]), .Y (n_25));
  CLKXOR2X1 g211(.A (wptr[4]), .B (wptr[3]), .Y (waddr[3]));
  NAND2XL g212(.A (wptr[3]), .B (wq2_rptr[3]), .Y (n_24));
  SDFFRHQX1 \wptr_reg[3] (.RN (wrst_n), .CK (wclk), .D (n_40), .SI
       (wptr[2]), .SE (DFT_sen), .Q (wptr[3]));
  SDFFRHQX1 \wptr_reg[2] (.RN (wrst_n), .CK (wclk), .D (n_21), .SI
       (wptr[1]), .SE (DFT_sen), .Q (wptr[2]));
  SDFFRHQX1 \wptr_reg[4] (.RN (wrst_n), .CK (wclk), .D (n_19), .SI
       (wptr[3]), .SE (DFT_sen), .Q (wptr[4]));
  OAI21XL g142(.A0 (n_15), .A1 (n_10), .B0 (n_17), .Y (n_21));
  OAI21XL g144(.A0 (n_13), .A1 (wptr[4]), .B0 (n_18), .Y (n_19));
  NAND2XL g145(.A (wptr[4]), .B (n_13), .Y (n_18));
  NAND2XL g146(.A (n_10), .B (n_15), .Y (n_17));
  SDFFRHQX1 \wptr_reg[1] (.RN (wrst_n), .CK (wclk), .D (n_16), .SI
       (wptr[0]), .SE (DFT_sen), .Q (wptr[1]));
  OAI21XL g148(.A0 (n_10), .A1 (n_6), .B0 (n_12), .Y (n_16));
  OAI21XL g149(.A0 (n_8), .A1 (waddr[3]), .B0 (n_14), .Y (n_15));
  NAND2XL g150(.A (waddr[3]), .B (n_8), .Y (n_14));
  NAND2XL g151(.A (n_6), .B (n_10), .Y (n_12));
  NAND2BXL g152(.AN (n_8), .B (waddr[3]), .Y (n_13));
  SDFFRHQX1 \wptr_reg[0] (.RN (wrst_n), .CK (wclk), .D (n_11), .SI
       (wq2_rptr[4]), .SE (DFT_sen), .Q (wptr[0]));
  OAI21XL g154(.A0 (n_6), .A1 (n_3), .B0 (n_7), .Y (n_11));
  AOI21XL g155(.A0 (waddr[2]), .A1 (n_4), .B0 (n_9), .Y (n_10));
  NOR2XL g156(.A (waddr[2]), .B (n_4), .Y (n_9));
  NAND2XL g157(.A (n_3), .B (n_6), .Y (n_7));
  NAND2BXL g158(.AN (n_4), .B (waddr[2]), .Y (n_8));
  OAI21XL g159(.A0 (n_1), .A1 (waddr[1]), .B0 (n_5), .Y (n_6));
  NAND2XL g160(.A (waddr[1]), .B (n_1), .Y (n_5));
  NAND2BXL g161(.AN (n_1), .B (waddr[1]), .Y (n_4));
  AOI21XL g162(.A0 (n_0), .A1 (waddr[0]), .B0 (n_2), .Y (n_3));
  NOR2XL g163(.A (n_0), .B (waddr[0]), .Y (n_2));
  NAND2BXL g164(.AN (n_0), .B (waddr[0]), .Y (n_1));
  NAND2BXL g165(.AN (wfull), .B (winc), .Y (n_0));
  XOR2XL g2(.A (n_19), .B (n_15), .Y (n_40));
endmodule

module FIFO(rdata, wfull, rempty, wdata, winc, wclk, wrst_n, rinc,
     rclk, rrst_n, scan_en, test_mode, DFT_sdi_1, DFT_sdo_1, DFT_sdi_2,
     DFT_sdo_2);
  input [7:0] wdata;
  input winc, wclk, wrst_n, rinc, rclk, rrst_n, scan_en, test_mode,
       DFT_sdi_1, DFT_sdi_2;
  output [7:0] rdata;
  output wfull, rempty, DFT_sdo_1, DFT_sdo_2;
  wire [7:0] wdata;
  wire winc, wclk, wrst_n, rinc, rclk, rrst_n, scan_en, test_mode,
       DFT_sdi_1, DFT_sdi_2;
  wire [7:0] rdata;
  wire wfull, rempty, DFT_sdo_1, DFT_sdo_2;
  wire [3:0] waddr;
  wire [3:0] raddr;
  wire [7:0] rdata_raw;
  wire [4:0] rq2_wptr;
  wire [4:0] rptr;
  wire [4:0] wq2_rptr;
  wire [4:0] wptr;
  wire n_18;
  assign DFT_sdo_2 = rdata[7];
  FIFO_memory_DATA_SIZE8_ADDR_SIZE4 fifomem(.rdata (rdata_raw), .wdata
       (wdata), .waddr (waddr), .raddr (raddr), .wclk_en (winc), .wfull
       (wfull), .wclk (wclk), .DFT_sdi (DFT_sdi_1), .DFT_sen (scan_en),
       .DFT_sdo (n_18));
  rptr_empty_ADDR_SIZE4 rptr_empty_inst(.rempty (rempty), .raddr
       (raddr), .rptr (rptr), .rq2_wptr (rq2_wptr), .rinc (rinc), .rclk
       (rclk), .rrst_n (rrst_n), .DFT_sdi (DFT_sdi_2), .DFT_sen
       (scan_en));
  two_ff_sync_SIZE5 sync_r2w(.q2 (wq2_rptr), .din (rptr), .clk (wclk),
       .rst_n (wrst_n), .DFT_sdi (n_18), .DFT_sen (scan_en));
  two_ff_sync_SIZE5_25 sync_w2r(.q2 (rq2_wptr), .din ({DFT_sdo_1,
       wptr[3:0]}), .clk (rclk), .rst_n (rrst_n), .DFT_sdi (rptr[4]),
       .DFT_sen (scan_en));
  wptr_full_ADDR_SIZE4 wptr_full_inst(.wfull (wfull), .waddr (waddr),
       .wptr ({DFT_sdo_1, wptr[3:0]}), .wq2_rptr (wq2_rptr), .winc
       (winc), .wclk (wclk), .wrst_n (wrst_n), .DFT_sen (scan_en));
  SDFFRHQX8 \rdata_reg[7] (.RN (rrst_n), .CK (rclk), .D (rdata_raw[7]),
       .SI (rdata[6]), .SE (scan_en), .Q (rdata[7]));
  SDFFRHQX8 \rdata_reg[6] (.RN (rrst_n), .CK (rclk), .D (rdata_raw[6]),
       .SI (rdata[5]), .SE (scan_en), .Q (rdata[6]));
  SDFFRHQX8 \rdata_reg[4] (.RN (rrst_n), .CK (rclk), .D (rdata_raw[4]),
       .SI (rdata[3]), .SE (scan_en), .Q (rdata[4]));
  SDFFRHQX8 \rdata_reg[0] (.RN (rrst_n), .CK (rclk), .D (rdata_raw[0]),
       .SI (rq2_wptr[4]), .SE (scan_en), .Q (rdata[0]));
  SDFFRHQX8 \rdata_reg[3] (.RN (rrst_n), .CK (rclk), .D (rdata_raw[3]),
       .SI (rdata[2]), .SE (scan_en), .Q (rdata[3]));
  SDFFRHQX8 \rdata_reg[5] (.RN (rrst_n), .CK (rclk), .D (rdata_raw[5]),
       .SI (rdata[4]), .SE (scan_en), .Q (rdata[5]));
  SDFFRHQX8 \rdata_reg[2] (.RN (rrst_n), .CK (rclk), .D (rdata_raw[2]),
       .SI (rdata[1]), .SE (scan_en), .Q (rdata[2]));
  SDFFRHQX8 \rdata_reg[1] (.RN (rrst_n), .CK (rclk), .D (rdata_raw[1]),
       .SI (rdata[0]), .SE (scan_en), .Q (rdata[1]));
endmodule

