###############################################################
#  Generated by:      Cadence Innovus 20.10-p004_1
#  OS:                Linux x86_64(Host ID edatools-server2.iiitd.edu.in)
#  Generated on:      Mon Nov 10 21:23:29 2025
#  Design:            FIFO
#  Command:           create_ccopt_clock_tree_spec -file file_cts.spec -keep_all_sdc_clocks -views view1
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# Pin offsets inferred from set_clock_latency assertions:
set_ccopt_property insertion_delay -pin {wptr_full_inst/wptr_reg[4]/CK} 0.019

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin rclk true
set_ccopt_property cts_is_sdc_clock_root -pin wclk true

# Clocks present at pin wclk
#   wclk (period 2.000ns) in timing_config sdc1([/home/vishal25157/Desktop/cmos65/90nm/pd_0.8/constraints.sdc])
create_ccopt_clock_tree -name wclk -source wclk -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner delay1 -early -clock_tree wclk 0.020

set_ccopt_property target_max_trans_sdc -delay_corner delay1 -late -clock_tree wclk 0.200
# Clock period setting for source pin of wclk
set_ccopt_property clock_period -pin wclk 2

# Clocks present at pin rclk
#   rclk (period 4.000ns) in timing_config sdc1([/home/vishal25157/Desktop/cmos65/90nm/pd_0.8/constraints.sdc])
create_ccopt_clock_tree -name rclk -source rclk -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner delay1 -early -clock_tree rclk 0.020

set_ccopt_property target_max_trans_sdc -delay_corner delay1 -late -clock_tree rclk 0.200
# Clock period setting for source pin of rclk
set_ccopt_property clock_period -pin rclk 4

# Skew group to balance non generated clock:rclk in timing_config:sdc1 (sdc /home/vishal25157/Desktop/cmos65/90nm/pd_0.8/constraints.sdc)
create_ccopt_skew_group -name rclk/sdc1 -sources rclk -auto_sinks
set_ccopt_property include_source_latency -skew_group rclk/sdc1 true
set_ccopt_property extracted_from_clock_name -skew_group rclk/sdc1 rclk
set_ccopt_property extracted_from_constraint_mode_name -skew_group rclk/sdc1 sdc1
set_ccopt_property extracted_from_delay_corners -skew_group rclk/sdc1 delay1

# Skew group to balance non generated clock:wclk in timing_config:sdc1 (sdc /home/vishal25157/Desktop/cmos65/90nm/pd_0.8/constraints.sdc)
create_ccopt_skew_group -name wclk/sdc1 -sources wclk -auto_sinks
set_ccopt_property include_source_latency -skew_group wclk/sdc1 true
set_ccopt_property extracted_from_clock_name -skew_group wclk/sdc1 wclk
set_ccopt_property extracted_from_constraint_mode_name -skew_group wclk/sdc1 sdc1
set_ccopt_property extracted_from_delay_corners -skew_group wclk/sdc1 delay1


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

